// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (003-dictionary-codegen, T024). DO NOT EDIT.
// <vXX>/Messages.hpp — typed-message flyweights ([2c §4.7];
// data-model Entity 1; AC-G1..G8/G11). Shape oracle:
// specs/003-dictionary-codegen/contracts/generated_message.hpp.
#pragma once
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <fixpp/dict/field_traits.hpp>
#include <fixpp/dict/version_profile.hpp>
#include <fixpp/wire/message_view_contract.hpp>
#include <cstdint>
#include <expected>
#include <memory_resource>
#include <string_view>
#include <utility>

namespace fixpp::vt11::groups {  // shared repeating-group flyweights (AC-G5/AC-G6)

    class G_627 {
    public:
        G_627() noexcept = default;
        explicit G_627(::fixpp::wire::entry_context ctx) noexcept
            : ctx_(ctx) {}
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    hop_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(::fixpp::wire::get(ctx_.span, 628, ctx_.hooks, ctx_.gen)); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    hop_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(::fixpp::wire::get(ctx_.span, 629, ctx_.hooks, ctx_.gen)); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    hop_ref_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(::fixpp::wire::get(ctx_.span, 630, ctx_.hooks, ctx_.gen)); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return ::fixpp::wire::get(ctx_.span, tag, ctx_.hooks, ctx_.gen); }
    private:
        ::fixpp::wire::entry_context ctx_{};
    };

}  // namespace fixpp::vt11::groups

namespace fixpp::vt11 {

// owning_<Msg> defined in <vXX>/Reify.hpp (US2/T032); forward-declared
// here so the per-message owning_message_traits specialisation is
// well-formed (AC-G7a / seam #18).
class owning_Heartbeat;
class owning_TestRequest;
class owning_ResendRequest;
class owning_Reject;
class owning_SequenceReset;
class owning_Logout;
class owning_Logon;
class owning_XMLnonFIX;

class Heartbeat {
public:
    static constexpr ::std::string_view msg_type_v = "0";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit Heartbeat(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    test_req_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<112>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(Heartbeat) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

class TestRequest {
public:
    static constexpr ::std::string_view msg_type_v = "1";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit TestRequest(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    test_req_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<112>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(TestRequest) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

class ResendRequest {
public:
    static constexpr ::std::string_view msg_type_v = "2";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit ResendRequest(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    begin_seq_no() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<7>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    end_seq_no() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<16>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(ResendRequest) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

class Reject {
public:
    static constexpr ::std::string_view msg_type_v = "3";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit Reject(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    ref_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<45>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    text() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<58>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    encoded_text_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<354>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    encoded_text() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<355>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    ref_tag_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<371>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    ref_msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<372>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    session_reject_reason() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<373>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    ref_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1130>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    ref_cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1131>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    ref_appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1406>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(Reject) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

class SequenceReset {
public:
    static constexpr ::std::string_view msg_type_v = "4";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit SequenceReset(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    new_seq_no() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<36>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    gap_fill_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<123>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(SequenceReset) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

class Logout {
public:
    static constexpr ::std::string_view msg_type_v = "5";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit Logout(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    text() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<58>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    encoded_text_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<354>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    encoded_text() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<355>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    session_status() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1409>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(Logout) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

class Logon {
public:
    static constexpr ::std::string_view msg_type_v = "A";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit Logon(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    text() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<58>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    raw_data_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<95>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    raw_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<96>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    encrypt_method() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<98>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    heart_bt_int() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<108>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    reset_seq_num_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<141>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    encoded_text_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<354>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    encoded_text() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<355>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    max_message_size() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<383>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    test_message_indicator() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<464>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    username() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<553>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    password() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<554>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    next_expected_msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<789>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    new_password() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<925>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    default_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1137>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    encrypted_password_method() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1400>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    encrypted_password_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1401>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    encrypted_password() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1402>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    encrypted_new_password_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1403>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    encrypted_new_password() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1404>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    default_appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1407>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    default_cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1408>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    session_status() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1409>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(Logon) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

class XMLnonFIX {
public:
    static constexpr ::std::string_view msg_type_v = "n";
    static constexpr ::fixpp::dict::application_version version_v =
        ::fixpp::dict::application_version::Unknown;

    explicit XMLnonFIX(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view [[clang::lifetimebound]]) noexcept
        : view_(view) {}

    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    begin_string() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<8>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    body_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<9>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    check_sum() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<10>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    msg_seq_num() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<34>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    msg_type() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<35>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_dup_flag() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<43>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<49>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<50>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<52>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<56>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<57>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    signature() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<89>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    secure_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<90>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    secure_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<91>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    signature_length() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<93>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<bool>
    poss_resend() const noexcept
    { return ::fixpp::dict::decode_field<bool>(view_.template get<97>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<115>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<116>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    orig_sending_time() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<122>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_comp_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_sub_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    sender_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<142>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    target_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<143>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    on_behalf_of_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<144>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    deliver_to_location_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<145>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    xml_data_len() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<212>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    xml_data() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<213>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    message_encoding() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<347>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    last_msg_seq_num_processed() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<369>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1128>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::string_view>
    cstm_appl_ver_id() const noexcept [[clang::lifetimebound]]
    { return ::fixpp::dict::decode_field<::std::string_view>(view_.template get<1129>()); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::std::int32_t>
    appl_ext_id() const noexcept
    { return ::fixpp::dict::decode_field<::std::int32_t>(view_.template get<1156>()); }
    [[nodiscard]] inline ::fixpp::wire::group_view<::fixpp::vt11::groups::G_627>
    hops() const noexcept [[clang::lifetimebound]]
    { return view_.template group<627, ::fixpp::vt11::groups::G_627>(); }
    [[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::wire::field_view>
    field_value(::std::uint16_t tag) const noexcept [[clang::lifetimebound]]
    { return view_.get(tag); }
    [[nodiscard]] inline ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const&
    view() const noexcept [[clang::lifetimebound]] { return view_; }

private:
    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& view_;
};
static_assert(sizeof(XMLnonFIX) == sizeof(::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const*));

}  // namespace fixpp::vt11
