// SPDX-License-Identifier: AGPL-3.0-or-later
//
// tests/interop/thorny/recovery/021-poss-dup-malformed-dup-rejected_test.cpp
//   — 021 T009 [US2] live malformed-duplicate interop cell.
//
// Scenario: both engines (QuickFIX-cpp, QuickFIX-J) × both roles (fixpp-initiator,
// fixpp-acceptor). The parent harness feeds a PossDupFlag(43)=Y message that is
// MISSING OrigSendingTime(122). Per FIX-SL §4.1.4 / §4.5.2, fixpp must:
//   (a) emit a session-level Reject(35=3) with RefTagID(371)=122 and
//       SessionRejectReason(373)=1 (RequiredTagMissing);
//   (b) stay Active — no Logout, no Disconnected.
//
// This matches QuickFIX-cpp v1.16.0 + QuickFIX-J 3.0.1 behavior when
// RequiresOrigSendingTime=Y (QFJ default). Run QFJ with its DEFAULT config.
//
// LIVE CELL: requires a counterparty. Cells SKIP cleanly when
// INTEROP_<TOKEN>_PORT is unset (FR-023). The golden diff is checked in the
// parent harness's `_finalize` via `interop_golden_check --check
// verbatim-poss-dup`; it fails closed (no skip).
//
// Golden normalization profile: {52, 122, 10} (quickstart §2):
//   - 52  SendingTime — live wall-clock
//   - 122 OrigSendingTime — absent in malformed frame but present in Reject;
//         excluded so a present-but-different timestamp never fails the diff
//   - 10  CheckSum — recomputed from body
// Structural tags compared verbatim: 34/43/35/371/373 — gate-biting.
//
// Anchors: tasks.md T009; contracts/session-possdup.md C1; quickstart.md §2;
//          specs/021-inbound-possdup-origsendingtime/ (FR-007/SC-002/SC-004).
//
// KNOWN LIMITATION: golden capture deferred to a live paired run; golden files
// must be generated by running `run_interop_cell.py --update-goldens` with the
// parent harness and counterparties active. See specs/021.../KNOWN-LIMITATIONS.md.
//
// [const §XV.9]: tests/-only.

#include <gtest/gtest.h>

#include <chrono>
#include <fixpp/session/engine.hpp>
#include <fixpp/session/session.hpp>
#include <fixpp/session/session_fsm.hpp>
#include <string>
#include <tuple>

#include "happy/hp_support.hpp"
#include "support/scenario_descriptor.hpp"

using namespace std::chrono_literals;
using fixpp::interop::Counterparty;
using fixpp::interop::Role;
using fixpp::session::fsm_state;

namespace {

// ── SC-004 gate-bite negative tests (T009) ────────────────────────────────────
//
// Structural tags under the poss_dup profile {52,122,10}: 34, 43, 35, 371, 373.
// Mutating any INCLUDED tag must cause diff_transcripts() to bite.
// NEVER mutate 52, 122, 10 (canonicalized → false non-biting pass).

TEST(MalformedDupRejectedGateBite, MutatedTag371RefTagIDCausesGateBite) {
    // Synthetic Reject(35=3) with RefTagID(371)=122 (the missing OrigSendingTime tag).
    // Tag 371 is COMPARED under {52,122,10} — mutation must bite.
    const char* expected_text =
        "> 8=FIX.4.4\\x0135=3\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=2\\x01371=122\\x01373=1"
        "\\x0152=20260603-10:00:00.000\\x0110=001\\x01\n";
    // Actual: RefTagID mutated from 122 to 11 (wrong tag reference).
    const char* actual_text =
        "> 8=FIX.4.4\\x0135=3\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=2\\x01371=11\\x01373=1"
        "\\x0152=20260603-10:00:00.000\\x0110=001\\x01\n";

    const auto expected_frames = fixpp::interop::parse_golden(expected_text);
    const auto actual_frames = fixpp::interop::parse_golden(actual_text);

    ASSERT_EQ(expected_frames.size(), actual_frames.size());

    const fixpp::interop::DiffResult result = fixpp::interop::diff_transcripts(
        expected_frames, actual_frames, fixpp::interop::poss_dup_profile_excluded_tags());

    EXPECT_FALSE(static_cast<bool>(result))
        << "gate-bite FAILED: diff_transcripts() reported match when tag 371 differs";
    EXPECT_EQ(result.status, fixpp::interop::DiffStatus::mismatch)
        << "Expected DiffStatus::mismatch when RefTagID(371) is mutated";
    EXPECT_NE(result.detail.find("371"), std::string::npos)
        << "detail should mention tag 371; got: " << result.detail;
}

TEST(MalformedDupRejectedGateBite, MutatedTag373SessionRejectReasonCausesGateBite) {
    // Tag 373 (SessionRejectReason) is COMPARED under {52,122,10}.
    // Arm C requires 373=1 (RequiredTagMissing); mutation to 2 must bite.
    const char* expected_text =
        "> 8=FIX.4.4\\x0135=3\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=2\\x01371=122\\x01373=1"
        "\\x0152=20260603-10:00:00.000\\x0110=001\\x01\n";
    // Actual: SessionRejectReason mutated from 1 to 2 (different reject reason).
    const char* actual_text =
        "> 8=FIX.4.4\\x0135=3\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=2\\x01371=122\\x01373=2"
        "\\x0152=20260603-10:00:00.000\\x0110=001\\x01\n";

    const auto expected_frames = fixpp::interop::parse_golden(expected_text);
    const auto actual_frames = fixpp::interop::parse_golden(actual_text);

    ASSERT_EQ(expected_frames.size(), actual_frames.size());

    const fixpp::interop::DiffResult result = fixpp::interop::diff_transcripts(
        expected_frames, actual_frames, fixpp::interop::poss_dup_profile_excluded_tags());

    EXPECT_FALSE(static_cast<bool>(result))
        << "gate-bite FAILED: diff_transcripts() reported match when tag 373 differs";
    EXPECT_EQ(result.status, fixpp::interop::DiffStatus::mismatch)
        << "Expected DiffStatus::mismatch when SessionRejectReason(373) is mutated";
    EXPECT_NE(result.detail.find("373"), std::string::npos)
        << "detail should mention tag 373; got: " << result.detail;
}

// ── T009 live cell: both engines × both roles ──────────────────────────────────
//
// Scenario: the parent harness feeds a 43=Y message missing 122. fixpp must emit
// Reject(35=3, 371=122, 373=1) and stay Active.
//
// In-process witnesses:
//   (a) FSM stays Active after the Reject (SC-002/FR-007).
//   (b) No disconnection occurs (no Logout).
//
// Golden assertion: diff using poss_dup profile {52,122,10}; tags 371/373/43/35
// compared verbatim (gate-biting per SC-004). Golden captured at first paired run.

class MalformedDupRejected : public ::testing::TestWithParam<std::tuple<Counterparty, Role>> {};

TEST_P(MalformedDupRejected, MissingOrigSendingTimeTriggersRejectAndSessionSurvives) {
    const auto [counterparty, role] = GetParam();
    namespace hp = fixpp::interop::hp;

    // ── Skip when no counterparty is present (FR-023) ─────────────────────────
    INTEROP_REQUIRE_COUNTERPARTY(hp::counterparty_token(counterparty).c_str());

    const char* dir = hp::tls_fixture_dir();
    if (dir == nullptr || dir[0] == '\0') {
        GTEST_SKIP() << "FIXPP_TLS_FIXTURE_DIR not set";
    }
    auto factory = hp::make_interop_tls_factory(dir);
    ASSERT_NE(factory, nullptr) << "baseline TLS factory build failed";

    const auto endpoint = hp::cell_endpoint(counterparty, role);
    ASSERT_TRUE(endpoint.has_value())
        << "cell endpoint unresolved (parent harness did not lease a port)";

    fixpp::interop::InteropEngineFixture fx;
    auto cfg =
        hp::make_session_config(role, "FIX.4.4", factory, fx.ioc().get_executor(), *endpoint);
    const auto id = fixpp::session::SessionId::from_config(cfg);
    ASSERT_TRUE(fx.engine().register_session(std::move(cfg)).has_value())
        << "register_session failed";

    fx.start();

    // ── Drive to Active ────────────────────────────────────────────────────────
    const auto reached = hp::drive_to_active(fx, id, 5s);
    EXPECT_EQ(reached, fsm_state::Active)
        << "session did not reach Active against " << hp::counterparty_token(counterparty)
        << "; state=" << static_cast<int>(reached);
    if (reached != fsm_state::Active) {
        hp::expect_graceful_stop(fx);
        return;
    }

    // ── Malformed-dup window: parent feeds 43=Y message with no 122 ───────────
    // fixpp emits Reject(35=3, 371=122, 373=1) and stays Active. The golden
    // records the inbound malformed frame + the outbound Reject, compared under
    // the poss_dup profile {52,122,10}.
    //
    // Wait up to 10 s for the Reject/survival window to complete. A down-peer or
    // absent parent harness config causes the cell to remain Active with no change
    // — the FSM-Active assertion below still passes (conservative: no false failure).
    fx.run_until(
        [&] {
            auto ss = fx.engine().lookup(id);
            // We do not have a dedicated "Reject emitted" observable from outside
            // Session internals. The golden assertion (below) verifies the Reject
            // was actually sent. Here we wait a bounded window for the exchange.
            return ss == nullptr || ss->state() != fsm_state::Active;
        },
        10s);

    auto s = fx.engine().lookup(id);
    ASSERT_NE(s, nullptr) << "session disappeared during malformed-dup window";

    // ── In-process witness (a): FSM stays Active (SC-002/FR-007) ─────────────
    EXPECT_EQ(s->state(), fsm_state::Active)
        << "fixpp session left Active after receiving a malformed PossDup (43=Y, no 122); "
           "must stay Active with a Reject emitted (SC-002/FR-007/Arm-C)";

    // ── Golden assertion: poss_dup profile {52,122,10} ────────────────────────
    // Tags 35/43/371/373 compared verbatim (gate-biting). Checked in the
    // parent harness's `_finalize` via `interop_golden_check
    // --check verbatim-poss-dup`; fails closed (no skip).
    const std::string cp_part = (counterparty == Counterparty::quickfix_j) ? "QFj" : "QFcpp";
    const std::string role_part = (role == Role::fixpp_initiator) ? "init" : "acc";
    const std::string cell_id = "PD-" + cp_part + "-" + role_part + "-fix44-malformed-dup-rejected";
    // #445: moved OUT of this gtest (was comparing against the PREVIOUS run's
    // capture sidecar, never this one's). Now asserted in the parent harness's
    // _finalize, against THIS run's own capture, via
    // `interop_golden_check --check verbatim-poss-dup`.

    // ── Graceful stop ─────────────────────────────────────────────────────────
    hp::expect_graceful_stop(fx);
}

INSTANTIATE_TEST_SUITE_P(
    Fix44, MalformedDupRejected,
    ::testing::Combine(::testing::Values(Counterparty::quickfix_cpp, Counterparty::quickfix_j),
                       ::testing::Values(Role::fixpp_initiator, Role::fixpp_acceptor)),
    fixpp::interop::hp::cell_name);

}  // namespace
