// SPDX-License-Identifier: AGPL-3.0-or-later
//
// tests/interop/thorny/recovery/021-poss-dup-replay-survives_test.cpp
//   — 021 T006 [US1] live PossDup replay-survives interop cell.
//
// Scenario: both engines (QuickFIX-cpp, QuickFIX-J) × both roles (fixpp-initiator,
// fixpp-acceptor). The parent harness drives a ResendRequest→replay sequence so the
// counterparty re-sends an already-seen message with PossDupFlag(43)=Y. The fixpp
// session under test must:
//   (a) remain in state Active throughout (not Logout, not Disconnected);
//   (b) emit no Logout frame on receipt of the replayed message.
//
// LIVE CELL: requires a counterparty. Cells SKIP cleanly when
// INTEROP_<TOKEN>_PORT is unset (FR-023). The golden diff is checked in the
// parent harness's `_finalize` via `interop_golden_check --check
// verbatim-poss-dup`; it fails closed (no skip).
//
// Golden normalization profile: {52, 122, 10} (quickstart §2):
//   - 52  SendingTime — live wall-clock
//   - 122 OrigSendingTime — replay timestamp, live wall-clock
//   - 10  CheckSum — recomputed from body
// Structural tags compared verbatim: 34/43/35 — gate-biting.
//
// Anchors: tasks.md T006; contracts/session-possdup.md C1; quickstart.md §2;
//          specs/021-inbound-possdup-origsendingtime/ (FR-007/SC-001/SC-004).
//
// KNOWN LIMITATION: golden capture deferred to a live paired run; golden files
// must be generated by running `run_interop_cell.py --update-goldens` with the
// parent harness and counterparties active. See specs/021.../KNOWN-LIMITATIONS.md.
//
// [const §XV.9]: tests/-only.

#include <gtest/gtest.h>

#include <chrono>
#include <fixpp/session/engine.hpp>
#include <fixpp/session/session.hpp>
#include <fixpp/session/session_fsm.hpp>
#include <string>
#include <tuple>

#include "happy/hp_support.hpp"
#include "support/scenario_descriptor.hpp"

using namespace std::chrono_literals;
using fixpp::interop::Counterparty;
using fixpp::interop::Role;
using fixpp::session::fsm_state;

namespace {

// ── SC-004 gate-bite negative test (T006 — PossDupFlag(43) must be verbatim) ──
//
// Mutate tag 43 (PossDupFlag) — which is a COMPARED tag under the poss_dup
// profile {52,122,10} — and assert diff_transcripts() bites with
// DiffStatus::mismatch.  NEVER mutate 52, 122, or 10 (canonicalized → would
// yield a false non-biting "pass", violating SC-004).

TEST(PossDupReplaySurvivesGateBite, MutatedTag43PossDupFlagCausesGateBite) {
    // Synthetic replayed frame (35=D) carrying PossDupFlag(43)=Y and
    // OrigSendingTime(122). Tag 43 is a COMPARED tag under {52,122,10}.
    const char* expected_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=2\\x0143=Y\\x01122=20260603-10:00:00.000"
        "\\x0152=20260603-10:00:01.000\\x0110=001\\x01\n";
    // Actual: PossDupFlag absent (43=N instead of 43=Y) — mutation.
    const char* actual_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=2\\x0143=N\\x01122=20260603-10:00:00.000"
        "\\x0152=20260603-10:00:01.000\\x0110=001\\x01\n";

    // Under poss_dup_profile_excluded_tags() == {52, 122, 10}:
    //   - tag 52  (SendingTime)     is excluded → equal regardless of value.
    //   - tag 122 (OrigSendingTime) is excluded → equal regardless of value.
    //   - tag 10  (CheckSum)        is excluded → equal regardless of value.
    //   - tag 43  (PossDupFlag)     is INCLUDED → must match verbatim → MISMATCH.
    const auto expected_frames = fixpp::interop::parse_golden(expected_text);
    const auto actual_frames = fixpp::interop::parse_golden(actual_text);

    ASSERT_EQ(expected_frames.size(), actual_frames.size());

    const fixpp::interop::DiffResult result = fixpp::interop::diff_transcripts(
        expected_frames, actual_frames, fixpp::interop::poss_dup_profile_excluded_tags());

    EXPECT_FALSE(static_cast<bool>(result))
        << "gate-bite FAILED: diff_transcripts() reported match when tag 43 differs";
    EXPECT_EQ(result.status, fixpp::interop::DiffStatus::mismatch)
        << "Expected DiffStatus::mismatch when PossDupFlag(43) is mutated";
    EXPECT_NE(result.detail.find("43"), std::string::npos)
        << "detail should mention tag 43; got: " << result.detail;
}

TEST(PossDupReplaySurvivesGateBite, MutatedTag34MsgSeqNumCausesGateBite) {
    // Tag 34 (MsgSeqNum) is a COMPARED tag under {52,122,10} — mutation must bite.
    const char* expected_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=2\\x0143=Y\\x01122=20260603-10:00:00.000"
        "\\x0152=20260603-10:00:01.000\\x0110=001\\x01\n";
    // Actual: MsgSeqNum mutated from 2 to 5.
    const char* actual_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=5\\x0143=Y\\x01122=20260603-10:00:00.000"
        "\\x0152=20260603-10:00:01.000\\x0110=001\\x01\n";

    const auto expected_frames = fixpp::interop::parse_golden(expected_text);
    const auto actual_frames = fixpp::interop::parse_golden(actual_text);

    ASSERT_EQ(expected_frames.size(), actual_frames.size());

    const fixpp::interop::DiffResult result = fixpp::interop::diff_transcripts(
        expected_frames, actual_frames, fixpp::interop::poss_dup_profile_excluded_tags());

    EXPECT_FALSE(static_cast<bool>(result))
        << "gate-bite FAILED: diff_transcripts() reported match when tag 34 differs";
    EXPECT_EQ(result.status, fixpp::interop::DiffStatus::mismatch)
        << "Expected DiffStatus::mismatch when MsgSeqNum(34) is mutated";
    EXPECT_NE(result.detail.find("34"), std::string::npos)
        << "detail should mention tag 34; got: " << result.detail;
}

// ── T006 live cell: both engines × both roles ──────────────────────────────────
//
// Scenario: drive a real ResendRequest→replay so the counterparty re-sends an
// already-seen application message with PossDupFlag(43)=Y; fixpp session must
// stay Active and emit no Logout.
//
// The parent harness configures the counterparty to emit one application message
// (e.g. 35=D seq=2), then sends a ResendRequest asking for it to be replayed.
// The replay carries 43=Y and 122=<original sending time>.
//
// In-process witnesses:
//   (a) FSM stays Active throughout (no Logout, no Disconnected).
//   (b) Expected inbound seqnum does NOT advance past its pre-replay value
//       (Arm A: too-low replayed dup is tolerated without seqnum advance — FR-001).
//
// Golden assertion: diff using poss_dup_profile {52,122,10}; skip if golden
// absent (capture deferred to first paired live run).

class PossDupReplaySurvives : public ::testing::TestWithParam<std::tuple<Counterparty, Role>> {};

TEST_P(PossDupReplaySurvives, ReplayedPossDupFrameDoesNotDisconnect) {
    const auto [counterparty, role] = GetParam();
    namespace hp = fixpp::interop::hp;

    // ── Skip when no counterparty is present (FR-023) ─────────────────────────
    INTEROP_REQUIRE_COUNTERPARTY(hp::counterparty_token(counterparty).c_str());

    const char* dir = hp::tls_fixture_dir();
    if (dir == nullptr || dir[0] == '\0') {
        GTEST_SKIP() << "FIXPP_TLS_FIXTURE_DIR not set";
    }
    auto factory = hp::make_interop_tls_factory(dir);
    ASSERT_NE(factory, nullptr) << "baseline TLS factory build failed";

    const auto endpoint = hp::cell_endpoint(counterparty, role);
    ASSERT_TRUE(endpoint.has_value())
        << "cell endpoint unresolved (parent harness did not lease a port)";

    fixpp::interop::InteropEngineFixture fx;
    auto cfg =
        hp::make_session_config(role, "FIX.4.4", factory, fx.ioc().get_executor(), *endpoint);
    const auto id = fixpp::session::SessionId::from_config(cfg);
    ASSERT_TRUE(fx.engine().register_session(std::move(cfg)).has_value())
        << "register_session failed";

    fx.start();

    // ── Drive to Active ────────────────────────────────────────────────────────
    const auto reached = hp::drive_to_active(fx, id, 5s);
    EXPECT_EQ(reached, fsm_state::Active)
        << "session did not reach Active against " << hp::counterparty_token(counterparty)
        << "; state=" << static_cast<int>(reached);
    if (reached != fsm_state::Active) {
        hp::expect_graceful_stop(fx);
        return;
    }

    auto s = fx.engine().lookup(id);
    ASSERT_NE(s, nullptr) << "session not established";

    // ── Snapshot inbound seqnum before the replay window ─────────────────────
    // After the replay, the inbound seqnum must NOT have advanced (Arm A: replayed
    // too-low dup is tolerated without seqnum advance — FR-001 / INV-1).
    const auto inbound_before_replay = s->seqnum_mgr_test_access().next_inbound_unsafe();

    // ── Replay window: wait for parent to drive ResendRequest→replay ──────────
    // The parent harness withholds one outbound frame, then sends a ResendRequest
    // causing the counterparty to replay it with 43=Y. fixpp must stay Active.
    // Wait up to 20 s for the replay to complete.
    fx.run_until(
        [&] {
            auto ss = fx.engine().lookup(id);
            return ss == nullptr || ss->state() != fsm_state::Active;
        },
        20s);

    s = fx.engine().lookup(id);
    ASSERT_NE(s, nullptr) << "session disappeared during replay window";

    // ── In-process witness (a): FSM stays Active (SC-001/FR-007) ─────────────
    EXPECT_EQ(s->state(), fsm_state::Active)
        << "fixpp session left Active after receiving a replayed PossDup(43=Y) frame; "
           "must stay Active (SC-001/FR-007 — inbound PossDup tolerance)";

    // ── In-process witness (b): inbound seqnum did NOT advance ───────────────
    // A too-low replayed duplicate does not advance the expected inbound sequence
    // (Arm A: tolerated without advance — FR-001/INV-1).
    // NOTE: if the parent also sent additional non-dup frames in the window, the
    // seqnum may have advanced. The gate here is that fixpp stayed Active — the
    // inbound seqnum invariant is validated more precisely by the unit tests in
    // tests/session/test_inbound_poss_dup_tolerance.cpp (T004).
    const auto inbound_after = s->seqnum_mgr_test_access().next_inbound_unsafe();
    (void)inbound_before_replay;  // used via golden + unit tests; live state may include additional
                                  // frames
    EXPECT_GE(inbound_after, inbound_before_replay)
        << "inbound seqnum regressed (should be >= pre-replay value)";

    // ── Golden assertion: poss_dup profile {52,122,10} ────────────────────────
    // Structural tags 34/43/35 compared verbatim (gate-biting). Golden captured
    // by `run_interop_cell.py --update-goldens` at first paired run; absent → skip.
    const std::string cp_part = (counterparty == Counterparty::quickfix_j) ? "QFj" : "QFcpp";
    const std::string role_part = (role == Role::fixpp_initiator) ? "init" : "acc";
    const std::string cell_id =
        "PD-" + cp_part + "-" + role_part + "-fix44-poss-dup-replay-survives";
    // #445: moved OUT of this gtest (was comparing against the PREVIOUS run's
    // capture sidecar, never this one's). Now asserted in the parent harness's
    // _finalize, against THIS run's own capture, via
    // `interop_golden_check --check verbatim-poss-dup`.

    // ── Graceful stop ─────────────────────────────────────────────────────────
    hp::expect_graceful_stop(fx);
}

INSTANTIATE_TEST_SUITE_P(
    Fix44, PossDupReplaySurvives,
    ::testing::Combine(::testing::Values(Counterparty::quickfix_cpp, Counterparty::quickfix_j),
                       ::testing::Values(Role::fixpp_initiator, Role::fixpp_acceptor)),
    fixpp::interop::hp::cell_name);

}  // namespace
