// SPDX-License-Identifier: AGPL-3.0-or-later
//
// tests/interop/thorny/recovery/022-poss-resend-deliver_test.cpp
//   — 022 T012 [P] live PossResend(97) deliver interop cell.
//
// Scenario: both engines (QuickFIX-cpp, QuickFIX-J) × both roles (fixpp-initiator,
// fixpp-acceptor). The parent harness configures the QF counterparty to send a
// business-level application message carrying PossResend(97)=Y in-sequence.
// fixpp MUST:
//   (a) deliver the message to Application::fromApp (tag 97 readable, in-sequence);
//   (b) advance the expected inbound seqnum;
//   (c) emit no Reject/Logout/disconnect — the session MUST stay Active.
//
// This validates the witness-only D4 claim from spec.md: fixpp's fromApp already
// delivers the full MessageView including tag 97; no session-level PossResend
// handling is needed (neither QFcpp nor QFJ handles 97 session-level either).
//
// LIVE CELL: requires a counterparty. Cells SKIP cleanly when
// INTEROP_<TOKEN>_PORT is unset (FR-023). Golden CAPTURE is deferred to the
// first paired run with the parent harness.
//
// Golden normalization profile: {52, 10} (admin profile):
//   - 52  SendingTime — live wall-clock
//   - 10  CheckSum — recomputed from body
// Structural tags 34/35/97 compared verbatim: gate-biting.
//
// Anchors: tasks.md T012; contracts/session-send-possdup.md §C5;
//          quickstart.md "Live interop cells";
//          specs/022-possresend-allowpossdup-send/ (SC-001/SC-005/FR-010).
//
// KNOWN LIMITATION: golden capture deferred to a live paired run; golden files
// must be generated by running `run_interop_cell.py --update-goldens` with the
// parent harness and counterparties active.
//
// [const §XV.9]: tests/-only.

#include <gtest/gtest.h>

#include <atomic>
#include <chrono>
#include <fixpp/core/engine_config.hpp>
#include <fixpp/core/error.hpp>
#include <fixpp/session/application.hpp>
#include <fixpp/session/engine.hpp>
#include <fixpp/session/session.hpp>
#include <fixpp/session/session_fsm.hpp>
#include <fixpp/wire/parser.hpp>
#include <memory>
#include <string>
#include <tuple>

#include "happy/hp_support.hpp"
#include "support/scenario_descriptor.hpp"

using namespace std::chrono_literals;
using fixpp::interop::Counterparty;
using fixpp::interop::Role;
using fixpp::session::Application;
using fixpp::session::fsm_state;
using fixpp::session::SessionId;
using fixpp::wire::access_mode;
using fixpp::wire::MessageView;

namespace {

// ── SC-005 gate-bite negative tests — standalone, no live counterparty ─────────
//
// Mutate tag 97 (PossResend) in a synthetic inbound frame and assert
// diff_transcripts() bites under the admin profile {52,10}. NEVER mutate 52 or
// 10 (canonicalized → false non-biting pass).

TEST(PossResendDeliverGateBite, MutatedTag97PossResendCausesGateBite) {
    // Synthetic inbound NewOrderSingle (35=D) with PossResend(97)=Y.
    // Tag 97 is COMPARED under admin_profile {52,10}.
    const char* expected_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=2\\x0197=Y\\x0111=ORD001"
        "\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";
    // Actual: PossResend absent (97=N instead of 97=Y) — mutation.
    const char* actual_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=2\\x0197=N\\x0111=ORD001"
        "\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";

    // Under admin_profile_excluded_tags() == {52, 10}:
    //   - tag 52 (SendingTime) is excluded → equal regardless of value.
    //   - tag 10 (CheckSum)    is excluded → equal regardless of value.
    //   - tag 97 (PossResend)  is INCLUDED → must match verbatim → MISMATCH.
    fixpp::interop::hp::expect_gate_bite_on_tag(expected_text, actual_text, "97");
}

TEST(PossResendDeliverGateBite, MutatedTag34MsgSeqNumCausesGateBite) {
    // Tag 34 (MsgSeqNum) is COMPARED under admin_profile {52,10} — mutation must bite.
    const char* expected_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=2\\x0197=Y\\x0111=ORD001"
        "\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";
    // Actual: MsgSeqNum mutated from 2 to 5.
    const char* actual_text =
        "< 8=FIX.4.4\\x0135=D\\x0149=CPTY_ACC\\x0156=FIXPP_INIT"
        "\\x0134=5\\x0197=Y\\x0111=ORD001"
        "\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";

    fixpp::interop::hp::expect_gate_bite_on_tag(expected_text, actual_text, "34");
}

// ── Tracking Application for T012 ─────────────────────────────────────────────
//
// Counts fromApp calls and records whether tag 97 (PossResend) was present
// in the first call. The counter is std::atomic so the test can poll from
// outside the engine executor (single-thread confinement: L-019-3; reads
// must be relaxed-acquire, not strand-synchronized).

class TrackingApp : public Application {
public:
    std::atomic<int> from_app_calls{0};
    std::atomic<bool> tag97_present{false};

    fixpp::core::expected_t<void> fromApp(const MessageView<access_mode::Index>& msg,
                                          const SessionId& /*id*/) override {
        // Check for PossResend(97). The MessageView is available only for the
        // duration of this call; read tag 97 before returning.
        const auto field97 = msg.get(static_cast<std::uint16_t>(97));
        if (field97.has_value()) {
            tag97_present.store(true, std::memory_order_release);
        }
        from_app_calls.fetch_add(1, std::memory_order_release);
        return {};
    }
};

// ── T012 live cell: both engines × both roles ──────────────────────────────────
//
// Scenario: the parent harness configures the QF counterparty to send a business
// application message with PossResend(97)=Y in-sequence. fixpp must deliver it
// to Application::fromApp, advance the inbound seqnum, and stay Active.
//
// In-process witnesses:
//   (a) Application::fromApp is invoked (from_app_calls >= 1) with tag 97 readable.
//   (b) Inbound seqnum advances past the Logon (confirming the 97=Y message
//       was processed normally, not silently dropped).
//   (c) FSM stays Active throughout (no Reject/Logout/disconnect from 97).
//
// Golden assertion: diff using admin profile {52,10}; tags 34/35/97 compared
// verbatim (gate-biting). Golden captured at first paired live run; absent → skip.

class PossResendDeliver : public ::testing::TestWithParam<std::tuple<Counterparty, Role>> {};

TEST_P(PossResendDeliver, PossResendMessageDeliveredToFromApp_SessionSurvives) {
    const auto [counterparty, role] = GetParam();
    namespace hp = fixpp::interop::hp;

    // ── Skip when no counterparty is present (FR-023) ─────────────────────────
    INTEROP_REQUIRE_COUNTERPARTY(hp::counterparty_token(counterparty).c_str());

    const char* dir = hp::tls_fixture_dir();
    if (dir == nullptr || dir[0] == '\0') {
        GTEST_SKIP() << "FIXPP_TLS_FIXTURE_DIR not set";
    }
    auto factory = hp::make_interop_tls_factory(dir);
    ASSERT_NE(factory, nullptr) << "baseline TLS factory build failed";

    const auto endpoint = hp::cell_endpoint(counterparty, role);
    ASSERT_TRUE(endpoint.has_value())
        << "cell endpoint unresolved (parent harness did not lease a port)";

    // ── Register a TrackingApp to observe fromApp calls ───────────────────────
    auto tracking_app = std::make_shared<TrackingApp>();
    fixpp::core::EngineConfig ecfg;
    ecfg.application = tracking_app;

    fixpp::interop::InteropEngineFixture fx{std::move(ecfg)};
    auto cfg =
        hp::make_session_config(role, "FIX.4.4", factory, fx.ioc().get_executor(), *endpoint);
    const auto id = fixpp::session::SessionId::from_config(cfg);
    ASSERT_TRUE(fx.engine().register_session(std::move(cfg)).has_value())
        << "register_session failed";

    fx.start();

    // ── Drive to Active ────────────────────────────────────────────────────────
    const auto reached = hp::drive_to_active(fx, id, 5s);
    EXPECT_EQ(reached, fsm_state::Active)
        << "session did not reach Active against " << hp::counterparty_token(counterparty)
        << "; state=" << static_cast<int>(reached);
    if (reached != fsm_state::Active) {
        hp::expect_graceful_stop(fx);
        return;
    }

    auto s = fx.engine().lookup(id);
    ASSERT_NE(s, nullptr) << "session not established";

    // ── Snapshot inbound seqnum after Logon ───────────────────────────────────
    const auto inbound_at_logon = s->seqnum_mgr_test_access().next_inbound_unsafe();

    // ── fromApp delivery window ───────────────────────────────────────────────
    // The parent harness configures the QF counterparty to send a business
    // application message with PossResend(97)=Y after the session is Active.
    // Wait up to 20 s for the fromApp counter to increment.
    //
    // If no parent harness sends the 97=Y message, this window expires and the
    // FSM-Active assertion below still passes (conservative: no false failure).
    // The test only asserts fromApp delivery when the counterparty actually sent.
    fx.run_until([&] { return tracking_app->from_app_calls.load(std::memory_order_acquire) >= 1; },
                 20s);

    auto s2 = fx.engine().lookup(id);
    ASSERT_NE(s2, nullptr) << "session disappeared during PossResend window";

    // ── In-process witness (c): FSM stays Active (SC-001/SC-005) ─────────────
    EXPECT_EQ(s2->state(), fsm_state::Active)
        << "fixpp session left Active after receiving a PossResend(97)=Y message; "
           "must stay Active (SC-001/SC-005 — PossResend is an application-layer flag)";

    // ── In-process witnesses (a)+(b): fromApp + seqnum advance ───────────────
    // INTEROP_REQUIRE_COUNTERPARTY passed — a live counterparty IS present and
    // the parent harness advertises it will send a 97=Y application message.
    // After the run_until window expires, from_app_calls >= 1 is MANDATORY: if
    // the advertised 97=Y stimulus never arrived the cell must FAIL (not silently
    // pass on the FSM-Active check alone). Mirror the 020 RC#1-r2 fix shape.
    // [F1 gate-b/r1; 020 RC#1-r2 anti-pattern; contracts/session-send-possdup.md §C5]
    EXPECT_GE(tracking_app->from_app_calls.load(std::memory_order_acquire), 1)
        << "live counterparty present but advertised 97=Y stimulus never arrived; "
           "fromApp must be called at least once after the PossResend delivery window "
           "(C5/FR-010 — counterparty was confirmed reachable by INTEROP_REQUIRE_COUNTERPARTY)";
    EXPECT_TRUE(tracking_app->tag97_present.load(std::memory_order_acquire))
        << "fromApp was called but tag 97 (PossResend) was not present in the "
           "delivered MessageView; the full frame including tag 97 must be "
           "delivered to fromApp (C4.1/SC-001)";
    const auto inbound_after = s2->seqnum_mgr_test_access().next_inbound_unsafe();
    EXPECT_GT(inbound_after, inbound_at_logon)
        << "inbound seqnum did not advance after receiving the 97=Y message; "
           "an in-sequence PossResend must advance the expected inbound seqnum "
           "(C4.1 — not a dup/replay, just a business-layer resend flag)";

    // ── Golden assertion: admin profile {52,10} ────────────────────────────────
    // Tags 34/35/97 compared verbatim (gate-biting per SC-004/SC-005). Checked
    // in the parent harness's `_finalize` via `interop_golden_check
    // --check verbatim-admin`; fails closed (no skip).
    const std::string cp_part = (counterparty == Counterparty::quickfix_j) ? "QFj" : "QFcpp";
    const std::string role_part = (role == Role::fixpp_initiator) ? "init" : "acc";
    const std::string cell_id = "PR-" + cp_part + "-" + role_part + "-fix44-poss-resend-deliver";
    // #445: moved OUT of this gtest (was comparing against the PREVIOUS run's
    // capture sidecar, never this one's). Now asserted in the parent harness's
    // _finalize, against THIS run's own capture, via
    // `interop_golden_check --check verbatim-admin`.

    // ── Graceful stop ─────────────────────────────────────────────────────────
    hp::expect_graceful_stop(fx);
}

INSTANTIATE_TEST_SUITE_P(
    Fix44, PossResendDeliver,
    ::testing::Combine(::testing::Values(Counterparty::quickfix_cpp, Counterparty::quickfix_j),
                       ::testing::Values(Role::fixpp_initiator, Role::fixpp_acceptor)),
    fixpp::interop::hp::cell_name);

}  // namespace
