// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_1677_3Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_1671Args.hpp"
#include "G_1669Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_1677_3Args {
    ::std::optional<char> list_update_action{};
    ::std::optional<::std::int64_t> risk_limit_status{};
    ::std::optional<::std::int64_t> risk_limit_result{};
    ::std::optional<::std::span<const G_1671Args>> party_details{};
    ::std::optional<::std::span<const G_1669Args>> risk_limits{};
    ::std::optional<::std::string_view> risk_limit_id{};
    ::std::optional<::std::int64_t> risk_limit_check_model_type{};
    ::std::optional<::std::string_view> reject_text{};
    ::std::optional<::std::string_view> encoded_reject_text{};
    ::std::optional<::std::int64_t> party_risk_limit_status{};
};

}  // namespace fixpp::vlatest::groups
