// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_2059Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_2059Args {
    ::std::optional<::std::int64_t> leg_event_type{};
    ::std::optional<::std::string_view> leg_event_date{};
    ::std::optional<::std::string_view> leg_event_time{};
    ::std::optional<::std::string_view> leg_event_time_unit{};
    ::std::optional<::std::int64_t> leg_event_time_period{};
    ::std::optional<::std::string_view> leg_event_month_year{};
    ::std::optional<::fixpp::decimal_t> leg_event_px{};
    ::std::optional<::std::string_view> leg_event_text{};
    ::std::optional<::std::string_view> encoded_leg_event_text{};
};

}  // namespace fixpp::vlatest::groups
