// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_2104Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_2113Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_2104Args {
    ::std::optional<::std::string_view> attachment_name{};
    ::std::optional<::std::string_view> attachment_media_type{};
    ::std::optional<::std::string_view> attachment_classification{};
    ::std::optional<::std::string_view> attachment_external_url{};
    ::std::optional<::std::int64_t> attachment_encoding_type{};
    ::std::optional<::std::int64_t> unencoded_attachment_len{};
    ::std::optional<::std::string_view> encoded_attachment{};
    ::std::optional<::std::span<const G_2113Args>> attachment_keywords{};
};

}  // namespace fixpp::vlatest::groups
