// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_2639Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_2639Args {
    ::std::optional<::fixpp::decimal_t> commission_amount{};
    ::std::optional<::std::int64_t> commission_amount_type{};
    ::std::optional<::std::int64_t> commission_amount_sub_type{};
    ::std::optional<char> commission_basis{};
    ::std::optional<::std::string_view> commission_currency{};
    ::std::optional<::std::string_view> commission_currency_code_source{};
    ::std::optional<::std::string_view> commission_unit_of_measure{};
    ::std::optional<::std::string_view> commission_unit_of_measure_currency{};
    ::std::optional<::std::string_view> commission_unit_of_measure_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> commission_rate{};
    ::std::optional<bool> commission_shared_indicator{};
    ::std::optional<::fixpp::decimal_t> commission_amount_shared{};
    ::std::optional<::std::string_view> commission_leg_ref_id{};
    ::std::optional<::std::string_view> commission_desc{};
    ::std::optional<::std::string_view> encoded_commission_desc{};
};

}  // namespace fixpp::vlatest::groups
