// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_2633Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_2633Args {
    ::std::optional<::std::string_view> misc_fee_sub_type{};
    ::std::optional<::fixpp::decimal_t> misc_fee_sub_type_amt{};
    ::std::optional<::std::string_view> misc_fee_sub_type_desc{};
    ::std::optional<::std::string_view> encoded_misc_fee_sub_type_desc{};
};

}  // namespace fixpp::vlatest::groups
