// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_2772Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_2772Args {
    ::std::optional<::std::int64_t> match_exception_type{};
    ::std::optional<::std::int64_t> match_exception_element_type{};
    ::std::optional<::std::string_view> match_exception_element_name{};
    ::std::optional<::std::string_view> match_exception_alloc_value{};
    ::std::optional<::std::string_view> match_exception_confirm_value{};
    ::std::optional<::fixpp::decimal_t> match_exception_tolerance_value{};
    ::std::optional<::std::int64_t> match_exception_tolerance_value_type{};
    ::std::optional<::std::string_view> match_exception_text{};
    ::std::optional<::std::string_view> encoded_match_exception_text{};
};

}  // namespace fixpp::vlatest::groups
