// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_386_2Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_1237Args.hpp"
#include "G_1239Args.hpp"
#include "G_1232Args.hpp"
#include "G_2548Args.hpp"
#include "G_1235Args.hpp"
#include "G_1141Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_386_2Args {
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> trading_session_sub_id{};
    ::std::optional<char> trad_ses_update_action{};
    ::std::optional<::std::string_view> security_exchange{};
    ::std::optional<::std::string_view> market_id{};
    ::std::optional<::std::string_view> market_segment_id{};
    ::std::optional<::std::string_view> trading_session_desc{};
    ::std::optional<::std::int64_t> trad_ses_method{};
    ::std::optional<::std::int64_t> trad_ses_mode{};
    ::std::optional<bool> unsolicited_indicator{};
    ::std::optional<::std::int64_t> trad_ses_status{};
    ::std::optional<::std::int64_t> trad_ses_status_rej_reason{};
    ::std::optional<::std::string_view> trad_ses_start_time{};
    ::std::optional<::std::string_view> trad_ses_open_time{};
    ::std::optional<::std::string_view> trad_ses_pre_close_time{};
    ::std::optional<::std::string_view> trad_ses_close_time{};
    ::std::optional<::std::string_view> trad_ses_end_time{};
    ::std::optional<::fixpp::decimal_t> total_volume_traded{};
    ::std::optional<::std::span<const G_1237Args>> ord_type_rules{};
    ::std::optional<::std::span<const G_1239Args>> time_in_force_rules{};
    ::std::optional<::std::span<const G_1232Args>> exec_inst_rules{};
    ::std::optional<::std::span<const G_2548Args>> auction_type_rules{};
    ::std::optional<::std::span<const G_1235Args>> match_rules{};
    ::std::optional<::std::span<const G_1141Args>> md_feed_types{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
};

}  // namespace fixpp::vlatest::groups
