// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_40000Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_40000Args {
    ::std::optional<::std::string_view> additional_term_bond_security_id{};
    ::std::optional<::std::string_view> additional_term_bond_security_id_source{};
    ::std::optional<::std::string_view> additional_term_bond_desc{};
    ::std::optional<::std::string_view> encoded_additional_term_bond_desc{};
    ::std::optional<::std::string_view> additional_term_bond_currency{};
    ::std::optional<::std::string_view> additional_term_bond_issuer{};
    ::std::optional<::std::string_view> encoded_additional_term_bond_issuer{};
    ::std::optional<::std::string_view> additional_term_bond_seniority{};
    ::std::optional<::std::int64_t> additional_term_bond_coupon_type{};
    ::std::optional<::fixpp::decimal_t> additional_term_bond_coupon_rate{};
    ::std::optional<::std::string_view> additional_term_bond_maturity_date{};
    ::std::optional<::fixpp::decimal_t> additional_term_bond_par_value{};
    ::std::optional<::fixpp::decimal_t> additional_term_bond_current_total_issued_amount{};
    ::std::optional<::std::int64_t> additional_term_bond_coupon_frequency_period{};
    ::std::optional<::std::string_view> additional_term_bond_coupon_frequency_unit{};
    ::std::optional<::std::int64_t> additional_term_bond_day_count{};
};

}  // namespace fixpp::vlatest::groups
