// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_420_2Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_420_2Args {
    ::std::optional<::fixpp::decimal_t> commission{};
    ::std::optional<char> comm_type{};
    ::std::optional<::std::string_view> comm_currency{};
    ::std::optional<::std::string_view> comm_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> comm_rate{};
    ::std::optional<::std::string_view> comm_unit_of_measure{};
    ::std::optional<char> fund_renew_waiv{};
    ::std::optional<::std::string_view> list_id{};
    ::std::optional<::std::string_view> country{};
    ::std::optional<char> side{};
    ::std::optional<::fixpp::decimal_t> price{};
    ::std::optional<::std::int64_t> price_type{};
    ::std::optional<::fixpp::decimal_t> fair_value{};
    ::std::optional<::std::int64_t> net_gross_ind{};
    ::std::optional<::std::string_view> settl_type{};
    ::std::optional<::std::string_view> settl_date{};
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> trading_session_sub_id{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
};

}  // namespace fixpp::vlatest::groups
