// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_42149Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_42190Args.hpp"
#include "G_42182Args.hpp"
#include "G_42184Args.hpp"
#include "G_42112Args.hpp"
#include "G_42186Args.hpp"
#include "G_42188Args.hpp"
#include "G_42180Args.hpp"
#include "G_42099Args.hpp"
#include "G_42173Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_42149Args {
    ::std::optional<::std::int64_t> underlying_provision_type{};
    ::std::optional<::std::string_view> underlying_provision_date_unadjusted{};
    ::std::optional<::std::int64_t> underlying_provision_date_business_day_convention{};
    ::std::optional<::std::span<const G_42190Args>> underlying_provision_date_business_centers{};
    ::std::optional<::std::string_view> underlying_provision_date_adjusted{};
    ::std::optional<::std::int64_t> underlying_provision_date_tenor_period{};
    ::std::optional<::std::string_view> underlying_provision_date_tenor_unit{};
    ::std::optional<::std::int64_t> underlying_provision_break_fee_election{};
    ::std::optional<::fixpp::decimal_t> underlying_provision_break_fee_rate{};
    ::std::optional<::std::int64_t> underlying_provision_calculation_agent{};
    ::std::optional<::std::int64_t> underlying_provision_option_single_party_buyer_side{};
    ::std::optional<::std::int64_t> underlying_provision_option_single_party_seller_side{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_value_time{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_value_time_business_center{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_value_date_business_day_convention{};
    ::std::optional<::std::span<const G_42182Args>> underlying_provision_cash_settl_value_date_business_centers{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_value_date_relative_to{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_value_date_offset_period{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_value_date_offset_unit{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_value_date_offset_day_type{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_value_date_adjusted{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_business_day_convention{};
    ::std::optional<::std::span<const G_42184Args>> underlying_provision_option_exercise_business_centers{};
    ::std::optional<::std::span<const G_42112Args>> underlying_provision_option_exercise_fixed_dates{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_earliest_date_offset_period{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_earliest_date_offset_unit{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_frequency_period{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_frequency_unit{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_start_date_unadjusted{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_start_date_relative_to{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_start_date_offset_period{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_start_date_offset_unit{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_start_date_offset_day_type{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_start_date_adjusted{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_period_skip{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_bounds_first_date_unadjusted{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_bounds_last_date_unadjusted{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_earliest_time{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_earliest_time_business_center{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_latest_time{};
    ::std::optional<::std::string_view> underlying_provision_option_exercise_latest_time_business_center{};
    ::std::optional<::std::string_view> underlying_provision_option_expiration_date_unadjusted{};
    ::std::optional<::std::int64_t> underlying_provision_option_expiration_date_business_day_convention{};
    ::std::optional<::std::span<const G_42186Args>> underlying_provision_option_expiration_date_business_centers{};
    ::std::optional<::std::int64_t> underlying_provision_option_expiration_date_relative_to{};
    ::std::optional<::std::int64_t> underlying_provision_option_expiration_date_offset_period{};
    ::std::optional<::std::string_view> underlying_provision_option_expiration_date_offset_unit{};
    ::std::optional<::std::int64_t> underlying_provision_option_expiration_date_offset_day_type{};
    ::std::optional<::std::string_view> underlying_provision_option_expiration_date_adjusted{};
    ::std::optional<::std::string_view> underlying_provision_option_expiration_time{};
    ::std::optional<::std::string_view> underlying_provision_option_expiration_time_business_center{};
    ::std::optional<::std::string_view> underlying_provision_option_relevant_underlying_date_unadjusted{};
    ::std::optional<::std::int64_t> underlying_provision_option_relevant_underlying_date_biz_day_convention{};
    ::std::optional<::std::span<const G_42188Args>> underlying_provision_option_relevant_underlying_date_business_centers{};
    ::std::optional<::std::int64_t> underlying_provision_option_relevant_underlying_date_relative_to{};
    ::std::optional<::std::int64_t> underlying_provision_option_relevant_underlying_date_offset_period{};
    ::std::optional<::std::string_view> underlying_provision_option_relevant_underlying_date_offset_unit{};
    ::std::optional<::std::int64_t> underlying_provision_option_relevant_underlying_date_offset_day_type{};
    ::std::optional<::std::string_view> underlying_provision_option_relevant_underlying_date_adjusted{};
    ::std::optional<::std::int64_t> underlying_provision_option_exercise_style{};
    ::std::optional<::fixpp::decimal_t> underlying_provision_option_exercise_multiple_notional{};
    ::std::optional<::fixpp::decimal_t> underlying_provision_option_exercise_minimum_notional{};
    ::std::optional<::fixpp::decimal_t> underlying_provision_option_exercise_maximum_notional{};
    ::std::optional<::std::int64_t> underlying_provision_option_minimum_number{};
    ::std::optional<::std::int64_t> underlying_provision_option_maximum_number{};
    ::std::optional<bool> underlying_provision_option_exercise_confirmation{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_payment_date_business_day_convention{};
    ::std::optional<::std::span<const G_42180Args>> underlying_provision_cash_settl_payment_date_business_centers{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_payment_date_relative_to{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_payment_date_offset_period{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_payment_date_offset_unit{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_payment_date_offset_day_type{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_payment_date_range_first{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_payment_date_range_last{};
    ::std::optional<::std::span<const G_42099Args>> underlying_provision_cash_settl_payment_dates{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_method{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_currency{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_currency2{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_quote_type{};
    ::std::optional<::std::int64_t> underlying_provision_cash_settl_quote_source{};
    ::std::optional<::std::string_view> underlying_provision_cash_settl_quote_reference_page{};
    ::std::optional<::std::string_view> underlying_provision_text{};
    ::std::optional<::std::string_view> encoded_underlying_provision_text{};
    ::std::optional<::std::span<const G_42173Args>> underlying_provision_party_i_ds{};
};

}  // namespace fixpp::vlatest::groups
