// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_555_8Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_604Args.hpp"
#include "G_2076Args.hpp"
#include "G_2308Args.hpp"
#include "G_2059Args.hpp"
#include "G_2254Args.hpp"
#include "G_2218Args.hpp"
#include "G_40923Args.hpp"
#include "G_41607Args.hpp"
#include "G_41467Args.hpp"
#include "G_41469Args.hpp"
#include "G_41471Args.hpp"
#include "G_42581Args.hpp"
#include "G_41491Args.hpp"
#include "G_41512Args.hpp"
#include "G_41515Args.hpp"
#include "G_41527Args.hpp"
#include "G_40241Args.hpp"
#include "G_40448Args.hpp"
#include "G_41335Args.hpp"
#include "G_41616Args.hpp"
#include "G_41344Args.hpp"
#include "G_41599Args.hpp"
#include "G_42388Args.hpp"
#include "G_683Args.hpp"
#include "G_539Args.hpp"
#include "G_3116Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_555_8Args {
    ::std::optional<::std::string_view> leg_symbol{};
    ::std::optional<::std::string_view> leg_symbol_sfx{};
    ::std::optional<::std::string_view> leg_security_id{};
    ::std::optional<::std::string_view> leg_security_id_source{};
    ::std::optional<::std::span<const G_604Args>> leg_security_alt_id{};
    ::std::optional<::std::string_view> leg_id{};
    ::std::optional<::std::int64_t> leg_product{};
    ::std::optional<::std::string_view> leg_security_group{};
    ::std::optional<::std::string_view> leg_cfi_code{};
    ::std::optional<::std::string_view> leg_upi_code{};
    ::std::optional<::std::string_view> leg_security_type{};
    ::std::optional<::std::string_view> leg_security_sub_type{};
    ::std::optional<::std::string_view> leg_maturity_month_year{};
    ::std::optional<::std::string_view> leg_maturity_date{};
    ::std::optional<::std::string_view> leg_maturity_time{};
    ::std::optional<::std::string_view> leg_maturity_frequency_unit{};
    ::std::optional<::std::int64_t> leg_maturity_frequency_period{};
    ::std::optional<::std::string_view> leg_settle_on_open_flag{};
    ::std::optional<char> leg_instrmt_assignment_method{};
    ::std::optional<::std::string_view> leg_security_status{};
    ::std::optional<::std::string_view> leg_coupon_payment_date{};
    ::std::optional<::std::string_view> leg_restructuring_type{};
    ::std::optional<::std::string_view> leg_seniority{};
    ::std::optional<::fixpp::decimal_t> leg_notional_percentage_outstanding{};
    ::std::optional<::fixpp::decimal_t> leg_original_notional_percentage_outstanding{};
    ::std::optional<::fixpp::decimal_t> leg_attachment_point{};
    ::std::optional<::fixpp::decimal_t> leg_detachment_point{};
    ::std::optional<::std::string_view> leg_obligation_type{};
    ::std::optional<::std::int64_t> leg_asset_group{};
    ::std::optional<::std::int64_t> leg_asset_class{};
    ::std::optional<::std::int64_t> leg_asset_sub_class{};
    ::std::optional<::std::string_view> leg_asset_type{};
    ::std::optional<::std::string_view> leg_asset_sub_type{};
    ::std::optional<::std::span<const G_2076Args>> leg_secondary_asset_classes{};
    ::std::optional<::std::span<const G_2308Args>> leg_asset_attributes{};
    ::std::optional<::std::string_view> leg_swap_class{};
    ::std::optional<::std::string_view> leg_swap_sub_class{};
    ::std::optional<::std::int64_t> leg_nth_to_default{};
    ::std::optional<::std::int64_t> leg_mth_to_default{};
    ::std::optional<::std::string_view> leg_settled_entity_matrix_source{};
    ::std::optional<::std::string_view> leg_settled_entity_matrix_publication_date{};
    ::std::optional<::std::int64_t> leg_coupon_type{};
    ::std::optional<::fixpp::decimal_t> leg_total_issued_amount{};
    ::std::optional<::std::int64_t> leg_coupon_frequency_period{};
    ::std::optional<::std::string_view> leg_coupon_frequency_unit{};
    ::std::optional<::std::int64_t> leg_coupon_day_count{};
    ::std::optional<::std::string_view> leg_coupon_other_day_count{};
    ::std::optional<::std::string_view> leg_convertible_bond_equity_id{};
    ::std::optional<::std::string_view> leg_convertible_bond_equity_id_source{};
    ::std::optional<::std::string_view> leg_contract_price_ref_month{};
    ::std::optional<::std::int64_t> leg_lien_seniority{};
    ::std::optional<::std::int64_t> leg_loan_facility{};
    ::std::optional<::std::int64_t> leg_reference_entity_type{};
    ::std::optional<::std::int64_t> leg_index_series{};
    ::std::optional<::std::int64_t> leg_index_annex_version{};
    ::std::optional<::std::string_view> leg_index_annex_date{};
    ::std::optional<::std::string_view> leg_index_annex_source{};
    ::std::optional<::std::string_view> leg_settl_rate_index{};
    ::std::optional<::std::string_view> leg_settl_rate_index_location{};
    ::std::optional<::std::string_view> leg_option_expiration_desc{};
    ::std::optional<::std::string_view> encoded_leg_option_expiration_desc{};
    ::std::optional<::std::string_view> leg_issue_date{};
    ::std::optional<::std::string_view> leg_repo_collateral_security_type{};
    ::std::optional<::std::int64_t> leg_repurchase_term{};
    ::std::optional<::fixpp::decimal_t> leg_repurchase_rate{};
    ::std::optional<::fixpp::decimal_t> leg_factor{};
    ::std::optional<::std::string_view> leg_credit_rating{};
    ::std::optional<::std::string_view> leg_instr_registry{};
    ::std::optional<::std::string_view> leg_country_of_issue{};
    ::std::optional<::std::string_view> leg_state_or_province_of_issue{};
    ::std::optional<::std::string_view> leg_locale_of_issue{};
    ::std::optional<::std::string_view> leg_redemption_date{};
    ::std::optional<::fixpp::decimal_t> leg_strike_price{};
    ::std::optional<::std::string_view> leg_strike_currency{};
    ::std::optional<::std::string_view> leg_strike_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> leg_strike_multiplier{};
    ::std::optional<::fixpp::decimal_t> leg_strike_value{};
    ::std::optional<::std::string_view> leg_strike_unit_of_measure{};
    ::std::optional<::std::string_view> leg_strike_index{};
    ::std::optional<::std::string_view> leg_strike_index_curve_point{};
    ::std::optional<::fixpp::decimal_t> leg_strike_index_spread{};
    ::std::optional<::std::int64_t> leg_strike_index_quote{};
    ::std::optional<::std::int64_t> leg_strike_price_determination_method{};
    ::std::optional<::std::int64_t> leg_strike_price_boundary_method{};
    ::std::optional<::fixpp::decimal_t> leg_strike_price_boundary_precision{};
    ::std::optional<::std::int64_t> leg_underlying_price_determination_method{};
    ::std::optional<char> leg_opt_attribute{};
    ::std::optional<::fixpp::decimal_t> leg_contract_multiplier{};
    ::std::optional<::std::int64_t> leg_contract_multiplier_unit{};
    ::std::optional<::std::int64_t> leg_trading_unit_period_multiplier{};
    ::std::optional<::std::int64_t> leg_flow_schedule_type{};
    ::std::optional<::fixpp::decimal_t> leg_min_price_increment{};
    ::std::optional<::fixpp::decimal_t> leg_min_price_increment_amount{};
    ::std::optional<::std::string_view> leg_unit_of_measure{};
    ::std::optional<::fixpp::decimal_t> leg_unit_of_measure_qty{};
    ::std::optional<::std::string_view> leg_unit_of_measure_currency{};
    ::std::optional<::std::string_view> leg_unit_of_measure_currency_code_source{};
    ::std::optional<::std::string_view> leg_price_unit_of_measure{};
    ::std::optional<::fixpp::decimal_t> leg_price_unit_of_measure_qty{};
    ::std::optional<::std::string_view> leg_price_unit_of_measure_currency{};
    ::std::optional<::std::string_view> leg_price_unit_of_measure_currency_code_source{};
    ::std::optional<::std::string_view> leg_settl_method{};
    ::std::optional<::std::string_view> leg_time_unit{};
    ::std::optional<::std::int64_t> leg_exercise_style{};
    ::std::optional<::std::int64_t> leg_opt_payout_type{};
    ::std::optional<::fixpp::decimal_t> leg_opt_payout_amount{};
    ::std::optional<::std::int64_t> leg_return_trigger{};
    ::std::optional<::std::string_view> leg_price_quote_method{};
    ::std::optional<::std::string_view> leg_valuation_method{};
    ::std::optional<::std::string_view> leg_valuation_source{};
    ::std::optional<::std::string_view> leg_valuation_reference_model{};
    ::std::optional<::std::string_view> leg_price_quote_currency{};
    ::std::optional<::std::string_view> leg_price_quote_currency_code_source{};
    ::std::optional<::std::int64_t> leg_list_method{};
    ::std::optional<::fixpp::decimal_t> leg_cap_price{};
    ::std::optional<::fixpp::decimal_t> leg_floor_price{};
    ::std::optional<bool> leg_flexible_indicator{};
    ::std::optional<bool> leg_flex_product_eligibility_indicator{};
    ::std::optional<::fixpp::decimal_t> leg_coupon_rate{};
    ::std::optional<::std::string_view> leg_security_exchange{};
    ::std::optional<::std::int64_t> leg_position_limit{};
    ::std::optional<::std::int64_t> leg_nt_position_limit{};
    ::std::optional<::std::string_view> leg_issuer{};
    ::std::optional<::std::string_view> encoded_leg_issuer{};
    ::std::optional<::std::string_view> leg_financial_instrument_short_name{};
    ::std::optional<::std::string_view> leg_financial_instrument_full_name{};
    ::std::optional<::std::string_view> encoded_leg_financial_instrument_full_name{};
    ::std::optional<::std::string_view> leg_security_desc{};
    ::std::optional<::std::string_view> encoded_leg_security_desc{};
    ::std::optional<::std::string_view> leg_security_xml{};
    ::std::optional<::std::string_view> leg_security_xml_schema{};
    ::std::optional<::std::int64_t> leg_cp_program{};
    ::std::optional<::std::string_view> leg_cp_reg_type{};
    ::std::optional<::fixpp::decimal_t> leg_ratio_qty{};
    ::std::optional<char> leg_side{};
    ::std::optional<::std::string_view> leg_currency{};
    ::std::optional<::std::string_view> leg_currency_code_source{};
    ::std::optional<::std::string_view> leg_pool{};
    ::std::optional<::std::string_view> leg_dated_date{};
    ::std::optional<::std::string_view> leg_contract_settl_month{};
    ::std::optional<::std::string_view> leg_interest_accrual_date{};
    ::std::optional<::std::int64_t> leg_put_or_call{};
    ::std::optional<::std::int64_t> leg_in_the_money_condition{};
    ::std::optional<bool> leg_contrary_instruction_eligibility_indicator{};
    ::std::optional<::fixpp::decimal_t> leg_option_ratio{};
    ::std::optional<::fixpp::decimal_t> leg_price{};
    ::std::optional<::std::span<const G_2059Args>> leg_events{};
    ::std::optional<::std::span<const G_2254Args>> leg_instrument_parties{};
    ::std::optional<::std::int64_t> leg_short_sale_restriction{};
    ::std::optional<::std::span<const G_2218Args>> leg_complex_events{};
    ::std::optional<::std::string_view> leg_strategy_type{};
    ::std::optional<bool> leg_common_pricing_indicator{};
    ::std::optional<::std::int64_t> leg_settl_disruption_provision{};
    ::std::optional<::std::string_view> leg_delivery_route_or_charter{};
    ::std::optional<char> leg_instrument_rounding_direction{};
    ::std::optional<::std::int64_t> leg_instrument_rounding_precision{};
    ::std::optional<::std::int64_t> leg_business_day_convention{};
    ::std::optional<::std::span<const G_40923Args>> leg_business_centers{};
    ::std::optional<::std::string_view> leg_date_roll_convention{};
    ::std::optional<::std::string_view> leg_pricing_date_unadjusted{};
    ::std::optional<::std::int64_t> leg_pricing_date_business_day_convention{};
    ::std::optional<::std::span<const G_41607Args>> leg_pricing_date_business_centers{};
    ::std::optional<::std::string_view> leg_pricing_date_adjusted{};
    ::std::optional<::std::string_view> leg_pricing_time{};
    ::std::optional<::std::string_view> leg_pricing_time_business_center{};
    ::std::optional<::std::int64_t> leg_market_disruption_provision{};
    ::std::optional<::std::span<const G_41467Args>> leg_market_disruption_events{};
    ::std::optional<::std::int64_t> leg_market_disruption_fallback_provision{};
    ::std::optional<::std::span<const G_41469Args>> leg_market_disruption_fallbacks{};
    ::std::optional<::std::span<const G_41471Args>> leg_market_disruption_fallback_reference_prices{};
    ::std::optional<::std::int64_t> leg_market_disruption_maximum_days{};
    ::std::optional<::fixpp::decimal_t> leg_market_disruption_materiality_percentage{};
    ::std::optional<::std::int64_t> leg_market_disruption_minimum_futures_contracts{};
    ::std::optional<::std::string_view> leg_exercise_desc{};
    ::std::optional<::std::string_view> encoded_leg_exercise_desc{};
    ::std::optional<bool> leg_automatic_exercise_indicator{};
    ::std::optional<::fixpp::decimal_t> leg_automatic_exercise_threshold_rate{};
    ::std::optional<::std::int64_t> leg_exercise_confirmation_method{};
    ::std::optional<::std::string_view> leg_manual_notice_business_center{};
    ::std::optional<bool> leg_fallback_exercise_indicator{};
    ::std::optional<bool> leg_limit_right_to_confirm_indicator{};
    ::std::optional<bool> leg_exercise_split_ticket_indicator{};
    ::std::optional<::std::int64_t> leg_settl_method_electing_party_side{};
    ::std::optional<::std::string_view> leg_settl_method_election_date_unadjusted{};
    ::std::optional<::std::int64_t> leg_settl_method_election_date_business_day_convention{};
    ::std::optional<::std::span<const G_42581Args>> leg_settl_method_election_date_business_centers{};
    ::std::optional<::std::int64_t> leg_settl_method_election_date_relative_to{};
    ::std::optional<::std::int64_t> leg_settl_method_election_date_offset_period{};
    ::std::optional<::std::string_view> leg_settl_method_election_date_offset_unit{};
    ::std::optional<::std::int64_t> leg_settl_method_election_date_offset_day_type{};
    ::std::optional<::std::string_view> leg_settl_method_election_date_adjusted{};
    ::std::optional<::std::int64_t> leg_option_exercise_business_day_convention{};
    ::std::optional<::std::span<const G_41491Args>> leg_option_exercise_business_centers{};
    ::std::optional<::std::span<const G_41512Args>> leg_option_exercise_dates{};
    ::std::optional<::std::int64_t> leg_option_exercise_earliest_date_offset_day_type{};
    ::std::optional<::std::int64_t> leg_option_exercise_earliest_date_offset_period{};
    ::std::optional<::std::string_view> leg_option_exercise_earliest_date_offset_unit{};
    ::std::optional<::std::int64_t> leg_option_exercise_frequency_period{};
    ::std::optional<::std::string_view> leg_option_exercise_frequency_unit{};
    ::std::optional<::std::string_view> leg_option_exercise_start_date_unadjusted{};
    ::std::optional<::std::int64_t> leg_option_exercise_start_date_relative_to{};
    ::std::optional<::std::int64_t> leg_option_exercise_start_date_offset_period{};
    ::std::optional<::std::string_view> leg_option_exercise_start_date_offset_unit{};
    ::std::optional<::std::int64_t> leg_option_exercise_start_date_offset_day_type{};
    ::std::optional<::std::string_view> leg_option_exercise_start_date_adjusted{};
    ::std::optional<::std::int64_t> leg_option_exercise_skip{};
    ::std::optional<::std::string_view> leg_option_exercise_nomination_deadline{};
    ::std::optional<::std::string_view> leg_option_exercise_first_date_unadjusted{};
    ::std::optional<::std::string_view> leg_option_exercise_last_date_unadjusted{};
    ::std::optional<::std::string_view> leg_option_exercise_earliest_time{};
    ::std::optional<::std::string_view> leg_option_exercise_latest_time{};
    ::std::optional<::std::string_view> leg_option_exercise_time_business_center{};
    ::std::optional<::std::int64_t> leg_option_exercise_expiration_date_business_day_convention{};
    ::std::optional<::std::span<const G_41515Args>> leg_option_exercise_expiration_date_business_centers{};
    ::std::optional<::std::span<const G_41527Args>> leg_option_exercise_expiration_dates{};
    ::std::optional<::std::int64_t> leg_option_exercise_expiration_date_relative_to{};
    ::std::optional<::std::int64_t> leg_option_exercise_expiration_date_offset_period{};
    ::std::optional<::std::string_view> leg_option_exercise_expiration_date_offset_unit{};
    ::std::optional<::std::int64_t> leg_option_exercise_expiration_frequency_period{};
    ::std::optional<::std::string_view> leg_option_exercise_expiration_frequency_unit{};
    ::std::optional<::std::string_view> leg_option_exercise_expiration_roll_convention{};
    ::std::optional<::std::int64_t> leg_option_exercise_expiration_date_offset_day_type{};
    ::std::optional<::std::string_view> leg_option_exercise_expiration_time{};
    ::std::optional<::std::string_view> leg_option_exercise_expiration_time_business_center{};
    ::std::optional<::std::string_view> leg_make_whole_date{};
    ::std::optional<::fixpp::decimal_t> leg_make_whole_amount{};
    ::std::optional<::std::string_view> leg_make_whole_benchmark_curve_name{};
    ::std::optional<::std::string_view> leg_make_whole_benchmark_curve_point{};
    ::std::optional<::fixpp::decimal_t> leg_make_whole_recall_spread{};
    ::std::optional<::std::int64_t> leg_make_whole_benchmark_quote{};
    ::std::optional<::std::int64_t> leg_make_whole_interpolation_method{};
    ::std::optional<::std::span<const G_40241Args>> leg_streams{};
    ::std::optional<::std::span<const G_40448Args>> leg_provisions{};
    ::std::optional<::std::span<const G_41335Args>> leg_additional_terms{};
    ::std::optional<::std::span<const G_41616Args>> leg_protection_terms{};
    ::std::optional<::std::span<const G_41344Args>> leg_cash_settl_terms{};
    ::std::optional<::std::span<const G_41599Args>> leg_physical_settl_terms{};
    ::std::optional<::std::span<const G_42388Args>> leg_extraordinary_events{};
    ::std::optional<::std::int64_t> leg_extraordinary_event_adjustment_method{};
    ::std::optional<bool> leg_exchange_look_alike{};
    ::std::optional<::fixpp::decimal_t> leg_order_qty{};
    ::std::optional<::fixpp::decimal_t> leg_qty{};
    ::std::optional<::fixpp::decimal_t> leg_mid_px{};
    ::std::optional<::std::int64_t> leg_swap_type{};
    ::std::optional<::std::string_view> leg_settl_type{};
    ::std::optional<::std::string_view> leg_settl_date{};
    ::std::optional<::std::span<const G_683Args>> leg_stipulations{};
    ::std::optional<::std::span<const G_539Args>> nested_party_i_ds{};
    ::std::optional<::std::int64_t> leg_price_type{};
    ::std::optional<::fixpp::decimal_t> leg_bid_px{};
    ::std::optional<::fixpp::decimal_t> leg_offer_px{};
    ::std::optional<::std::string_view> leg_benchmark_curve_currency{};
    ::std::optional<::std::string_view> leg_benchmark_curve_currency_code_source{};
    ::std::optional<::std::string_view> leg_benchmark_curve_name{};
    ::std::optional<::std::string_view> leg_benchmark_curve_point{};
    ::std::optional<::fixpp::decimal_t> leg_benchmark_price{};
    ::std::optional<::std::int64_t> leg_benchmark_price_type{};
    ::std::optional<::std::string_view> leg_ref_id{};
    ::std::optional<::fixpp::decimal_t> leg_bid_forward_points{};
    ::std::optional<::fixpp::decimal_t> leg_offer_forward_points{};
    ::std::optional<::std::span<const G_3116Args>> leg_rate_sources{};
};

}  // namespace fixpp::vlatest::groups
