// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_552_2Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_453Args.hpp"
#include "G_1630Args.hpp"
#include "G_576Args.hpp"
#include "G_2639Args.hpp"
#include "G_518Args.hpp"
#include "G_232Args.hpp"
#include "G_136Args.hpp"
#include "G_1158Args.hpp"
#include "G_78_3Args.hpp"
#include "G_73_1Args.hpp"
#include "G_1624Args.hpp"
#include "G_2593Args.hpp"
#include "G_1016Args.hpp"
#include "G_1855Args.hpp"
#include "G_1861Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_552_2Args {
    ::std::optional<char> side{};
    ::std::optional<::std::string_view> side_exec_id{};
    ::std::optional<::std::string_view> side_trade_id{};
    ::std::optional<::std::string_view> side_orig_trade_id{};
    ::std::optional<::std::int64_t> order_delay{};
    ::std::optional<::std::int64_t> order_delay_unit{};
    ::std::optional<::std::span<const G_453Args>> party_i_ds{};
    ::std::optional<::std::string_view> account{};
    ::std::optional<::std::int64_t> acct_id_source{};
    ::std::optional<::std::int64_t> account_type{};
    ::std::optional<::std::span<const G_1630Args>> limit_amts{};
    ::std::optional<char> process_code{};
    ::std::optional<bool> odd_lot{};
    ::std::optional<::std::span<const G_576Args>> clearing_instructions{};
    ::std::optional<::std::int64_t> side_trade_reporting_indicator{};
    ::std::optional<::std::string_view> trade_input_source{};
    ::std::optional<::std::string_view> trade_input_device{};
    ::std::optional<::std::string_view> compliance_id{};
    ::std::optional<::std::string_view> compliance_text{};
    ::std::optional<::std::string_view> encoded_compliance_text{};
    ::std::optional<bool> solicited_flag{};
    ::std::optional<::std::int64_t> cust_order_capacity{};
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> trading_session_sub_id{};
    ::std::optional<::std::string_view> time_bracket{};
    ::std::optional<::std::int64_t> net_gross_ind{};
    ::std::optional<::std::string_view> side_currency{};
    ::std::optional<::std::string_view> side_currency_code_source{};
    ::std::optional<::std::string_view> side_settl_currency{};
    ::std::optional<::std::string_view> side_settl_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> commission{};
    ::std::optional<char> comm_type{};
    ::std::optional<::std::string_view> comm_currency{};
    ::std::optional<::std::string_view> comm_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> comm_rate{};
    ::std::optional<::std::string_view> comm_unit_of_measure{};
    ::std::optional<char> fund_renew_waiv{};
    ::std::optional<::std::span<const G_2639Args>> commissions{};
    ::std::optional<::std::int64_t> num_days_interest{};
    ::std::optional<::std::string_view> ex_date{};
    ::std::optional<::fixpp::decimal_t> accrued_interest_rate{};
    ::std::optional<::fixpp::decimal_t> accrued_interest_amt{};
    ::std::optional<::fixpp::decimal_t> interest_at_maturity{};
    ::std::optional<::fixpp::decimal_t> end_accrued_interest_amt{};
    ::std::optional<::fixpp::decimal_t> start_cash{};
    ::std::optional<::fixpp::decimal_t> end_cash{};
    ::std::optional<::fixpp::decimal_t> concession{};
    ::std::optional<::fixpp::decimal_t> total_takedown{};
    ::std::optional<::fixpp::decimal_t> net_money{};
    ::std::optional<::fixpp::decimal_t> settl_curr_amt{};
    ::std::optional<::fixpp::decimal_t> settl_curr_fx_rate{};
    ::std::optional<char> settl_curr_fx_rate_calc{};
    ::std::optional<char> position_effect{};
    ::std::optional<::std::int64_t> side_multi_leg_reporting_type{};
    ::std::optional<::std::span<const G_518Args>> cont_amts{};
    ::std::optional<::std::span<const G_232Args>> stipulations{};
    ::std::optional<::std::span<const G_136Args>> misc_fees{};
    ::std::optional<::std::string_view> exchange_rule{};
    ::std::optional<::std::span<const G_1158Args>> settl_details{};
    ::std::optional<::std::int64_t> trade_alloc_indicator{};
    ::std::optional<::std::string_view> alloc_group_id{};
    ::std::optional<::std::string_view> previous_alloc_group_id{};
    ::std::optional<::std::string_view> firm_group_id{};
    ::std::optional<::fixpp::decimal_t> group_amount{};
    ::std::optional<::std::int64_t> alloc_group_status{};
    ::std::optional<::std::int64_t> side_avg_px_indicator{};
    ::std::optional<::std::string_view> side_avg_px_group_id{};
    ::std::optional<::fixpp::decimal_t> side_avg_px{};
    ::std::optional<char> prealloc_method{};
    ::std::optional<::std::string_view> alloc_id{};
    ::std::optional<::std::string_view> secondary_alloc_id{};
    ::std::optional<::std::span<const G_78_3Args>> allocs{};
    ::std::optional<::fixpp::decimal_t> side_gross_trade_amt{};
    ::std::optional<bool> aggressor_indicator{};
    ::std::optional<::fixpp::decimal_t> side_last_qty{};
    ::std::optional<::std::string_view> side_trade_report_id{};
    ::std::optional<::std::string_view> side_fill_station_cd{};
    ::std::optional<::std::string_view> side_reason_cd{};
    ::std::optional<::std::int64_t> rpt_seq{};
    ::std::optional<::std::int64_t> side_trd_sub_type{};
    ::std::optional<char> order_category{};
    ::std::optional<::std::string_view> strategy_link_id{};
    ::std::optional<::std::string_view> order_id{};
    ::std::optional<::std::string_view> secondary_order_id{};
    ::std::optional<::std::string_view> cl_ord_id{};
    ::std::optional<::std::string_view> secondary_cl_ord_id{};
    ::std::optional<::std::string_view> list_id{};
    ::std::optional<::std::string_view> ref_order_id{};
    ::std::optional<char> ref_order_id_source{};
    ::std::optional<::std::int64_t> ref_ord_id_reason{};
    ::std::optional<::std::span<const G_73_1Args>> orders{};
    ::std::optional<bool> pre_trade_anonymity{};
    ::std::optional<char> ord_type{};
    ::std::optional<::fixpp::decimal_t> price{};
    ::std::optional<::fixpp::decimal_t> stop_px{};
    ::std::optional<char> exec_inst{};
    ::std::optional<char> ord_status{};
    ::std::optional<::fixpp::decimal_t> order_qty{};
    ::std::optional<::fixpp::decimal_t> cash_order_qty{};
    ::std::optional<::fixpp::decimal_t> order_percent{};
    ::std::optional<char> rounding_direction{};
    ::std::optional<::fixpp::decimal_t> rounding_modulus{};
    ::std::optional<::fixpp::decimal_t> leaves_qty{};
    ::std::optional<::fixpp::decimal_t> cum_qty{};
    ::std::optional<char> time_in_force{};
    ::std::optional<::std::string_view> expire_time{};
    ::std::optional<::std::span<const G_1624Args>> match_inst{};
    ::std::optional<::std::string_view> self_match_prevention_id{};
    ::std::optional<::std::int64_t> self_match_prevention_instruction{};
    ::std::optional<::std::int64_t> exposure_duration{};
    ::std::optional<::std::int64_t> exposure_duration_unit{};
    ::std::optional<::fixpp::decimal_t> display_qty{};
    ::std::optional<::fixpp::decimal_t> secondary_display_qty{};
    ::std::optional<::fixpp::decimal_t> initial_display_qty{};
    ::std::optional<::fixpp::decimal_t> current_display_price{};
    ::std::optional<char> display_when{};
    ::std::optional<char> display_method{};
    ::std::optional<::fixpp::decimal_t> display_low_qty{};
    ::std::optional<::fixpp::decimal_t> display_high_qty{};
    ::std::optional<::fixpp::decimal_t> display_min_incr{};
    ::std::optional<::fixpp::decimal_t> refresh_qty{};
    ::std::optional<char> order_capacity{};
    ::std::optional<char> order_restrictions{};
    ::std::optional<::std::int64_t> booking_type{};
    ::std::optional<::std::int64_t> orig_cust_order_capacity{};
    ::std::optional<::std::int64_t> order_origination{};
    ::std::optional<::std::span<const G_2593Args>> order_attributes{};
    ::std::optional<::std::int64_t> ex_destination_type{};
    ::std::optional<::std::string_view> order_input_device{};
    ::std::optional<char> lot_type{};
    ::std::optional<::std::string_view> trans_bkd_time{};
    ::std::optional<::std::string_view> orig_ord_mod_time{};
    ::std::optional<::fixpp::decimal_t> order_percent_of_total_volume{};
    ::std::optional<::std::span<const G_1016Args>> side_trd_reg_ts{};
    ::std::optional<::std::string_view> cust_order_handling_inst{};
    ::std::optional<::std::int64_t> order_handling_inst_source{};
    ::std::optional<::std::span<const G_1855Args>> related_trades{};
    ::std::optional<::std::span<const G_1861Args>> related_positions{};
    ::std::optional<::std::int64_t> side_risk_limit_check_status{};
};

}  // namespace fixpp::vlatest::groups
