// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_78_4Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_3099Args.hpp"
#include "G_1908Args.hpp"
#include "G_3008Args.hpp"
#include "G_539Args.hpp"
#include "G_2653Args.hpp"
#include "G_136Args.hpp"
#include "G_576Args.hpp"
#include "G_85Args.hpp"
#include "G_1844Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_78_4Args {
    ::std::optional<::std::string_view> alloc_account{};
    ::std::optional<::std::int64_t> alloc_acct_id_source{};
    ::std::optional<char> match_status{};
    ::std::optional<::fixpp::decimal_t> alloc_price{};
    ::std::optional<::fixpp::decimal_t> alloc_qty{};
    ::std::optional<::fixpp::decimal_t> alloc_calculated_ccy_qty{};
    ::std::optional<::std::string_view> custodial_lot_id{};
    ::std::optional<::std::string_view> versus_purchase_date{};
    ::std::optional<::fixpp::decimal_t> versus_purchase_price{};
    ::std::optional<::fixpp::decimal_t> current_cost_basis{};
    ::std::optional<::std::string_view> individual_alloc_id{};
    ::std::optional<::std::span<const G_3099Args>> individual_alloc_sub_qty_attributes{};
    ::std::optional<::std::string_view> firm_mnemonic{};
    ::std::optional<::std::string_view> parent_alloc_id{};
    ::std::optional<::std::string_view> alloc_leg_ref_id{};
    ::std::optional<::std::span<const G_1908Args>> alloc_regulatory_trade_i_ds{};
    ::std::optional<::std::span<const G_3008Args>> alloc_trd_reg_timestamps{};
    ::std::optional<char> process_code{};
    ::std::optional<::std::string_view> secondary_individual_alloc_id{};
    ::std::optional<::std::int64_t> alloc_method{};
    ::std::optional<::std::int64_t> allocation_rollup_instruction{};
    ::std::optional<::std::string_view> alloc_customer_capacity{};
    ::std::optional<char> alloc_position_effect{};
    ::std::optional<::std::int64_t> individual_alloc_type{};
    ::std::optional<::std::span<const G_539Args>> nested_party_i_ds{};
    ::std::optional<bool> notify_broker_of_credit{};
    ::std::optional<::std::int64_t> alloc_handl_inst{};
    ::std::optional<::std::string_view> alloc_text{};
    ::std::optional<::std::string_view> encoded_alloc_text{};
    ::std::optional<::std::string_view> firm_alloc_text{};
    ::std::optional<::std::string_view> encoded_firm_alloc_text{};
    ::std::optional<::fixpp::decimal_t> commission{};
    ::std::optional<char> comm_type{};
    ::std::optional<::std::string_view> comm_currency{};
    ::std::optional<::std::string_view> comm_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> comm_rate{};
    ::std::optional<::std::string_view> comm_unit_of_measure{};
    ::std::optional<char> fund_renew_waiv{};
    ::std::optional<::std::span<const G_2653Args>> alloc_commissions{};
    ::std::optional<::fixpp::decimal_t> alloc_avg_px{};
    ::std::optional<::fixpp::decimal_t> alloc_net_money{};
    ::std::optional<::fixpp::decimal_t> settl_curr_amt{};
    ::std::optional<::fixpp::decimal_t> alloc_gross_trade_amt{};
    ::std::optional<::fixpp::decimal_t> alloc_settl_curr_amt{};
    ::std::optional<::std::string_view> settl_currency{};
    ::std::optional<::std::string_view> alloc_settl_currency{};
    ::std::optional<::std::string_view> alloc_settl_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> settl_curr_fx_rate{};
    ::std::optional<char> settl_curr_fx_rate_calc{};
    ::std::optional<::fixpp::decimal_t> alloc_accrued_interest_amt{};
    ::std::optional<::fixpp::decimal_t> alloc_interest_at_maturity{};
    ::std::optional<::std::span<const G_136Args>> misc_fees{};
    ::std::optional<::std::span<const G_576Args>> clearing_instructions{};
    ::std::optional<::std::string_view> clearing_fee_indicator{};
    ::std::optional<::std::int64_t> alloc_settl_inst_type{};
    ::std::optional<::std::int64_t> settl_delivery_type{};
    ::std::optional<::std::int64_t> stand_inst_db_type{};
    ::std::optional<::std::string_view> stand_inst_db_name{};
    ::std::optional<::std::string_view> stand_inst_db_id{};
    ::std::optional<::std::span<const G_85Args>> dlvy_inst{};
    ::std::optional<::std::string_view> alloc_ref_risk_limit_check_id{};
    ::std::optional<::std::int64_t> alloc_ref_risk_limit_check_id_type{};
    ::std::optional<::std::int64_t> alloc_risk_limit_check_status{};
    ::std::optional<::fixpp::decimal_t> alloc_group_amount{};
    ::std::optional<::std::string_view> alloc_avg_px_group_id{};
    ::std::optional<::std::int64_t> alloc_avg_px_indicator{};
    ::std::optional<::std::span<const G_1844Args>> trade_alloc_amts{};
};

}  // namespace fixpp::vlatest::groups
