// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_864Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_864Args {
    ::std::optional<::std::int64_t> event_type{};
    ::std::optional<::std::string_view> event_date{};
    ::std::optional<::std::string_view> event_time{};
    ::std::optional<::std::string_view> event_time_unit{};
    ::std::optional<::std::int64_t> event_time_period{};
    ::std::optional<::std::string_view> event_month_year{};
    ::std::optional<::fixpp::decimal_t> event_px{};
    ::std::optional<::std::string_view> event_text{};
    ::std::optional<::std::string_view> encoded_event_text{};
};

}  // namespace fixpp::vlatest::groups
