// SPDX-License-Identifier: AGPL-3.0-or-later
//
// tests/interop/thorny/framing/022-allow-pos-dup-strip-send_test.cpp
//   — 022 T011 [P] live AllowPosDup wire-capture interop cell.
//
// Scenario: both engines (QuickFIX-cpp, QuickFIX-J) × both roles (fixpp-initiator,
// fixpp-acceptor). fixpp uses the DEFAULT SessionConfig (allow_pos_dup == false).
// A business-message application payload that contains caller-supplied
// PossDupFlag(43)=Y and OrigSendingTime(122)=<ts> is sent via Engine::send.
// The 022 send-path strip MUST remove 43 and 122 before framing. The counterparty
// MUST accept the message and the session MUST stay Active (no Reject/Logout/
// disconnect from the counterparty).
//
// In-process witnesses:
//   (a) Engine::send returns success (the strip ran; no app_payload_malformed).
//   (b) FSM stays Active after the send (the counterparty did not log out or disconnect).
//   (c) Outbound seqnum advanced by one (the message was transmitted).
//
// None of (a)-(c) can see a session-level Reject(35=3) from the counterparty: a Reject
// leaves fixpp Active with its seqnum already advanced (fixpp#442). That the counterparty
// ACCEPTED the message is witnessed by the parent harness, which fails the cell on a
// Reject in the counterparty's transcript (run_interop_cell.py,
// check_no_unexpected_peer_reject).
//
// Golden assertion: diff using admin_profile {52,10}; structural tags 34/35
// compared verbatim (gate-biting). Golden captured by
// `run_interop_cell.py --update-goldens` at first paired live run; absent → skip.
//
// LIVE CELL: requires a counterparty. Cells SKIP cleanly when
// INTEROP_<TOKEN>_PORT is unset (FR-023). Golden CAPTURE is deferred to the
// first paired run with the parent harness.
//
// Anchors: tasks.md T011; contracts/session-send-possdup.md §C5;
//          quickstart.md "Live interop cells";
//          specs/022-possresend-allowpossdup-send/ (FR-010/SC-005).
//
// KNOWN LIMITATION: golden capture deferred to a live paired run; golden files
// must be generated by running `run_interop_cell.py --update-goldens` with the
// parent harness and counterparties active.
//
// [const §XV.9]: tests/-only.

#include <gtest/gtest.h>

#include <array>
#include <asio/co_spawn.hpp>
#include <asio/io_context.hpp>
#include <asio/use_future.hpp>
#include <atomic>
#include <chrono>
#include <fixpp/core/engine_config.hpp>
#include <fixpp/core/error.hpp>
#include <fixpp/session/engine.hpp>
#include <fixpp/session/session.hpp>
#include <fixpp/session/session_fsm.hpp>
#include <span>
#include <string>
#include <tuple>

#include "happy/hp_support.hpp"
#include "support/scenario_descriptor.hpp"

using namespace std::chrono_literals;
using fixpp::interop::Counterparty;
using fixpp::interop::Role;
using fixpp::session::fsm_state;

namespace {

// ── SC-005 gate-bite negative tests — standalone, no live counterparty ────────
//
// Mutate a COMPARED tag (34 or 35) in a synthetic outbound frame and assert
// diff_transcripts() bites under the admin profile {52,10}. NEVER mutate 52 or
// 10 (canonicalized → false non-biting pass).

TEST(AllowPosDupStripSendGateBite, MutatedTag35MsgTypeCausesGateBite) {
    // Synthetic stripped NewOrderSingle (35=D) carrying no PossDupFlag or
    // OrigSendingTime (the strip ran successfully).
    const char* expected_text =
        "> 8=FIX.4.4\\x0135=D\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=2\\x0111=ORD001\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";
    // Actual: MsgType mutated from D to 8 (ExecutionReport).
    const char* actual_text =
        "> 8=FIX.4.4\\x0135=8\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=2\\x0111=ORD001\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";

    // Under admin_profile_excluded_tags() == {52, 10}:
    //   - tag 52 (SendingTime) is excluded → equal regardless of value.
    //   - tag 10 (CheckSum)    is excluded → equal regardless of value.
    //   - tag 35 (MsgType)     is INCLUDED → must match verbatim → MISMATCH.
    fixpp::interop::hp::expect_gate_bite_on_tag(expected_text, actual_text, "35");
}

TEST(AllowPosDupStripSendGateBite, MutatedTag34MsgSeqNumCausesGateBite) {
    // Synthetic stripped NewOrderSingle — mutate MsgSeqNum(34) which is COMPARED.
    const char* expected_text =
        "> 8=FIX.4.4\\x0135=D\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=2\\x0111=ORD001\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";
    // Actual: MsgSeqNum mutated from 2 to 3.
    const char* actual_text =
        "> 8=FIX.4.4\\x0135=D\\x0149=FIXPP_INIT\\x0156=CPTY_ACC"
        "\\x0134=3\\x0111=ORD001\\x0152=20260605-10:00:00.000\\x0110=001\\x01\n";

    fixpp::interop::hp::expect_gate_bite_on_tag(expected_text, actual_text, "34");
}

// ── T011 live cell: both engines × both roles ──────────────────────────────────
//
// Scenario: fixpp (default allow_pos_dup==false) sends an application message
// whose payload contains caller-supplied PossDupFlag(43)=Y and
// OrigSendingTime(122). The 022 send-path scanner/excision strips both tags
// before framing. The counterparty MUST accept the stripped frame and the
// session MUST stay Active (C5/SC-005/FR-010).
//
// In-process witnesses:
//   (a) Engine::send returns success (strip ran; no 131 malformed).
//   (b) FSM stays Active after the send.
//   (c) Outbound seqnum advanced by one.
//
// The golden assertion verifies the outbound bytes contain no boundary 43/122
// in the application portion (deferred to first paired live run; absent → skip).

class AllowPosDupStripSend : public ::testing::TestWithParam<std::tuple<Counterparty, Role>> {};

TEST_P(AllowPosDupStripSend, StripDefaultSends43Free_CounterpartyAccepts) {
    const auto [counterparty, role] = GetParam();
    namespace hp = fixpp::interop::hp;

    // ── Skip when no counterparty is present (FR-023) ─────────────────────────
    INTEROP_REQUIRE_COUNTERPARTY(hp::counterparty_token(counterparty).c_str());

    const char* dir = hp::tls_fixture_dir();
    if (dir == nullptr || dir[0] == '\0') {
        GTEST_SKIP() << "FIXPP_TLS_FIXTURE_DIR not set";
    }
    auto factory = hp::make_interop_tls_factory(dir);
    ASSERT_NE(factory, nullptr) << "baseline TLS factory build failed";

    const auto endpoint = hp::cell_endpoint(counterparty, role);
    ASSERT_TRUE(endpoint.has_value())
        << "cell endpoint unresolved (parent harness did not lease a port)";

    fixpp::interop::InteropEngineFixture fx;
    // Default SessionConfig: allow_pos_dup == false (the strip is ON by default).
    auto cfg =
        hp::make_session_config(role, "FIX.4.4", factory, fx.ioc().get_executor(), *endpoint);
    // Verify the default: allow_pos_dup must be false (C2.1/SC-005).
    ASSERT_FALSE(cfg.allow_pos_dup) << "allow_pos_dup default must be false (C1/C2.1)";

    const auto id = fixpp::session::SessionId::from_config(cfg);
    ASSERT_TRUE(fx.engine().register_session(std::move(cfg)).has_value())
        << "register_session failed";

    fx.start();

    // ── Drive to Active ────────────────────────────────────────────────────────
    const auto reached = hp::drive_to_active(fx, id, 5s);
    EXPECT_EQ(reached, fsm_state::Active)
        << "session did not reach Active against " << hp::counterparty_token(counterparty)
        << "; state=" << static_cast<int>(reached);
    if (reached != fsm_state::Active) {
        hp::expect_graceful_stop(fx);
        return;
    }

    auto s = fx.engine().lookup(id);
    ASSERT_NE(s, nullptr) << "session not established";

    // ── Snapshot outbound seqnum before the send ───────────────────────────────
    const auto seqnum_before = s->seqnum_mgr_test_access().next_outbound_unsafe();

    // ── Build a payload that contains caller-supplied 43=Y and 122 ────────────
    // The 022 send-path strip must excise these before framing. The payload is a
    // minimal NewOrderSingle (35=D) with deliberately injected 43=Y+122.
    // The counterparty should accept the stripped frame (no 43/122 on wire).
    // (INV-2 injection-safety — a literal "43=" inside a field value is NOT
    // excised — is covered by the W3 unit hostile witness in
    // tests/session/test_send_allow_pos_dup_strip.cpp; this live cell exercises
    // only the boundary-field strip.)
    const std::string payload =
        "35=D\x01"
        "11=ORD001\x01"
        "54=1\x01"                        // Side=Buy
        "44=100.00\x01"                   // Price
        "38=10\x01"                       // OrderQty
        "40=2\x01"                        // OrdType=Limit
        "55=SYMB\x01"                     // Symbol
        "43=Y\x01"                        // PossDupFlag — MUST be stripped (C2.1)
        "122=20260605-10:00:00.000\x01";  // OrigSendingTime — MUST be stripped

    std::vector<std::byte> payload_bytes;
    payload_bytes.reserve(payload.size());
    for (char c : payload) payload_bytes.push_back(static_cast<std::byte>(c));

    // ── Send the payload via Engine::send (any-thread, exec-hop) ──────────────
    // Engine::send is an asio awaitable; we co_spawn it and run via use_future.
    // A 5-second internal deadline (the fixture's run_until) prevents hanging.
    std::atomic<bool> send_called{false};
    std::atomic<bool> send_succeeded{false};

    asio::co_spawn(
        fx.ioc().get_executor(), fx.engine().send(id, payload_bytes),
        [&send_called, &send_succeeded](std::exception_ptr ep, fixpp::core::expected_t<void> r) {
            if (!ep) {
                send_succeeded.store(r.has_value(), std::memory_order_release);
            }
            send_called.store(true, std::memory_order_release);
        });

    // ── Wait for the send to complete (up to 5 s) ─────────────────────────────
    fx.run_until([&send_called] { return send_called.load(std::memory_order_acquire); }, 5s);

    // ── In-process witness (a): Engine::send returned success (C5/SC-005) ─────
    EXPECT_TRUE(send_called.load(std::memory_order_acquire))
        << "Engine::send did not complete within the 5-second deadline";
    EXPECT_TRUE(send_succeeded.load(std::memory_order_acquire))
        << "Engine::send failed — strip may have returned 131 (app_payload_malformed) "
           "or the session is not Active; the payload must be a well-formed, "
           "strippable application payload";

    // ── Wait for the counterparty to receive (up to 5 s) ─────────────────────
    // The counterparty must not Reject or disconnect. Give it time to process.
    fx.run_until(
        [&] {
            auto ss = fx.engine().lookup(id);
            return ss == nullptr || ss->state() != fsm_state::Active;
        },
        5s);

    s = fx.engine().lookup(id);
    ASSERT_NE(s, nullptr) << "session disappeared after send";

    // ── In-process witness (b): FSM stays Active (C5/SC-005) ─────────────────
    EXPECT_EQ(s->state(), fsm_state::Active)
        << "fixpp session left Active after sending a stripped 43=Y+122 payload; "
           "counterparty must accept the stripped (43/122-free) frame (C5/SC-005)";

    // ── In-process witness (c): outbound seqnum advanced by one ───────────────
    const auto seqnum_after = s->seqnum_mgr_test_access().next_outbound_unsafe();
    EXPECT_EQ(seqnum_after, seqnum_before + 1U)
        << "outbound seqnum did not advance by one after the send; "
           "expected="
        << (seqnum_before + 1U) << " got=" << seqnum_after;

    // ── Golden assertion: admin profile {52,10} ───────────────────────────────
    // Tags 34/35 compared verbatim (gate-biting per SC-004). The golden is
    // captured by `run_interop_cell.py --update-goldens` at first paired run.
    // The golden MUST NOT contain boundary 43= or 122= in the app portion
    // (the parent harness verifies this at capture time). Absent → skip.
    const std::string cp_part = (counterparty == Counterparty::quickfix_j) ? "QFj" : "QFcpp";
    const std::string role_part = (role == Role::fixpp_initiator) ? "init" : "acc";
    const std::string cell_id =
        "APDS-" + cp_part + "-" + role_part + "-fix44-allow-pos-dup-strip-send";
    // #445: moved OUT of this gtest (was comparing against the PREVIOUS run's
    // capture sidecar, never this one's). Now asserted in the parent harness's
    // _finalize, against THIS run's own capture, via
    // `interop_golden_check --check verbatim-admin`.

    // ── Graceful stop ─────────────────────────────────────────────────────────
    hp::expect_graceful_stop(fx);
}

INSTANTIATE_TEST_SUITE_P(
    Fix44, AllowPosDupStripSend,
    ::testing::Combine(::testing::Values(Counterparty::quickfix_cpp, Counterparty::quickfix_j),
                       ::testing::Values(Role::fixpp_initiator, Role::fixpp_acceptor)),
    fixpp::interop::hp::cell_name);

}  // namespace
