// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/AlgoCertificateReportAck.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct AlgoCertificateReportAckArgs {
    ::std::optional<::std::string_view> reject_text{};
    ::std::optional<::std::string_view> encoded_reject_text{};
    ::std::optional<::std::string_view> algo_certificate_report_id{};
    ::std::optional<::std::int64_t> algo_certificate_report_status{};
    ::std::optional<::std::int64_t> algo_certificate_report_type{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_AlgoCertificateReportAck)
#include "AlgoCertificateReportAck.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_AlgoCertificateReportAck(::std::span<::std::byte> out, AlgoCertificateReportAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_AlgoCertificateReportAck)
#include "AlgoCertificateReportAck.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_AlgoCertificateReportAck(AlgoCertificateReportAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
