// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/AlgoCertificateReport.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_453Args.hpp"
#include "../groups/G_957Args.hpp"
#include "../groups/G_3025Args.hpp"
#include "../groups/G_3028Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct AlgoCertificateReportArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> effective_time{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::span<const groups::G_453Args> party_i_ds{};
    ::std::optional<::std::string_view> last_update_time{};
    ::std::optional<::std::span<const groups::G_957Args>> strategy_parameters{};
    ::std::optional<::std::string_view> algo_certificate_id{};
    ::std::optional<::std::string_view> algo_certificate_desc{};
    ::std::optional<::std::string_view> algo_certificate_request_id{};
    ::std::optional<::std::string_view> algo_certificate_report_id{};
    ::std::optional<::std::string_view> algo_certificate_report_ref_id{};
    ::std::optional<::std::int64_t> algo_certificate_report_trans_type{};
    ::std::optional<::std::int64_t> algo_certificate_status{};
    ::std::optional<::std::string_view> approval_time{};
    ::std::optional<::std::string_view> algo_test_desc{};
    ::std::optional<::std::span<const groups::G_3025Args>> algo_system_modules{};
    ::std::optional<::std::span<const groups::G_3028Args>> test_scenarios{};
    ::std::optional<::std::int64_t> test_suite_status{};
    ::std::optional<::std::int64_t> algo_certificate_report_type{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_AlgoCertificateReport)
#include "AlgoCertificateReport.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_AlgoCertificateReport(::std::span<::std::byte> out, AlgoCertificateReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_AlgoCertificateReport)
#include "AlgoCertificateReport.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_AlgoCertificateReport(AlgoCertificateReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
