// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/AlgoCertificateRequest.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "AlgoCertificateRequest.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_AlgoCertificateRequest(::std::span<::std::byte> out, AlgoCertificateRequestArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"EH"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.effective_time) {
        auto r = bb.field(168, *args.effective_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.party_i_ds) {
        auto gh0 = bb.group_begin(453, 448);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_id) {
        auto r = eh0.set_string(448, *item0.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_id_source) {
        auto r = eh0.set_char(447, *item0.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role) {
        auto r = eh0.set_int(452, *item0.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role_qualifier) {
        auto r = eh0.set_int(2376, *item0.party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_sub_i_ds) {
        auto gh1 = eh0.group_begin(802, 523);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_sub_id) {
        auto r = eh1.set_string(523, *item1.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_sub_id_type) {
        auto r = eh1.set_int(803, *item1.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.target_party_i_ds) {
        auto gh2 = bb.group_begin(1461, 1462);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *args.target_party_i_ds) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.target_party_id) {
        auto r = eh2.set_string(1462, *item2.target_party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.target_party_id_source) {
        auto r = eh2.set_char(1463, *item2.target_party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.target_party_role) {
        auto r = eh2.set_int(1464, *item2.target_party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.target_party_role_qualifier) {
        auto r = eh2.set_int(1818, *item2.target_party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.target_party_sub_i_ds) {
        auto gh3 = eh2.group_begin(2433, 2434);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *item2.target_party_sub_i_ds) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.target_party_sub_id) {
        auto r = eh3.set_string(2434, *item3.target_party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.target_party_sub_id_type) {
        auto r = eh3.set_int(2435, *item3.target_party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    if (args.algo_certificate_id) {
        auto r = bb.field(3012, *args.algo_certificate_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.algo_certificate_desc) {
        auto r = bb.field(3013, *args.algo_certificate_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.algo_certificate_request_id) {
        auto r = bb.field(3014, *args.algo_certificate_request_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.algo_certificate_request_ref_id) {
        auto r = bb.field(3015, *args.algo_certificate_request_ref_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.algo_certificate_request_trans_type) {
        auto r = bb.field(3016, *args.algo_certificate_request_trans_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.algo_certificate_status) {
        auto r = bb.field(3022, *args.algo_certificate_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.approval_time) {
        auto r = bb.field(3023, *args.approval_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.test_scenarios) {
        auto gh4 = bb.group_begin(3028, 3029);
        if (!gh4) return ::std::unexpected(gh4.error());
        for (auto const& item4 : *args.test_scenarios) {
            auto en4 = gh4->add_entry();
            if (!en4) return ::std::unexpected(en4.error());
            auto& eh4 = *en4;
    if (item4.test_scenario_id) {
        auto r = eh4.set_string(3029, *item4.test_scenario_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.test_scenario_status) {
        auto r = eh4.set_int(3030, *item4.test_scenario_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.test_scenario_start_time) {
        auto r = eh4.set_string(3031, *item4.test_scenario_start_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.test_scenario_end_time) {
        auto r = eh4.set_string(3032, *item4.test_scenario_end_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.test_scenario_parameters) {
        auto gh5 = eh4.group_begin(3130, 3131);
        if (!gh5) return ::std::unexpected(gh5.error());
        for (auto const& item5 : *item4.test_scenario_parameters) {
            auto en5 = gh5->add_entry();
            if (!en5) return ::std::unexpected(en5.error());
            auto& eh5 = *en5;
    if (item5.test_scenario_parameter_name) {
        auto r = eh5.set_string(3131, *item5.test_scenario_parameter_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.test_scenario_parameter_type) {
        auto r = eh5.set_int(3132, *item5.test_scenario_parameter_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.test_scenario_parameter_value) {
        auto r = eh5.set_string(3133, *item5.test_scenario_parameter_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge5 = bb.group_end(*gh5);
        if (!ge5) return ::std::unexpected(ge5.error());
    }
    if (item4.nested_party_i_ds) {
        auto gh6 = eh4.group_begin(539, 524);
        if (!gh6) return ::std::unexpected(gh6.error());
        for (auto const& item6 : *item4.nested_party_i_ds) {
            auto en6 = gh6->add_entry();
            if (!en6) return ::std::unexpected(en6.error());
            auto& eh6 = *en6;
    if (item6.nested_party_id) {
        auto r = eh6.set_string(524, *item6.nested_party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.nested_party_id_source) {
        auto r = eh6.set_char(525, *item6.nested_party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.nested_party_role) {
        auto r = eh6.set_int(538, *item6.nested_party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.nested_party_role_qualifier) {
        auto r = eh6.set_int(2384, *item6.nested_party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.nested_party_sub_i_ds) {
        auto gh7 = eh6.group_begin(804, 545);
        if (!gh7) return ::std::unexpected(gh7.error());
        for (auto const& item7 : *item6.nested_party_sub_i_ds) {
            auto en7 = gh7->add_entry();
            if (!en7) return ::std::unexpected(en7.error());
            auto& eh7 = *en7;
    if (item7.nested_party_sub_id) {
        auto r = eh7.set_string(545, *item7.nested_party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.nested_party_sub_id_type) {
        auto r = eh7.set_int(805, *item7.nested_party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge7 = bb.group_end(*gh7);
        if (!ge7) return ::std::unexpected(ge7.error());
    }
        }
        auto ge6 = bb.group_end(*gh6);
        if (!ge6) return ::std::unexpected(ge6.error());
    }
    if (item4.instrument_scopes) {
        auto gh8 = eh4.group_begin(1656, 1535);
        if (!gh8) return ::std::unexpected(gh8.error());
        for (auto const& item8 : *item4.instrument_scopes) {
            auto en8 = gh8->add_entry();
            if (!en8) return ::std::unexpected(en8.error());
            auto& eh8 = *en8;
    if (item8.instrument_scope_operator) {
        auto r = eh8.set_int(1535, *item8.instrument_scope_operator);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_symbol) {
        auto r = eh8.set_string(1536, *item8.instrument_scope_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_symbol_sfx) {
        auto r = eh8.set_string(1537, *item8.instrument_scope_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_id) {
        auto r = eh8.set_string(1538, *item8.instrument_scope_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_id_source) {
        auto r = eh8.set_string(1539, *item8.instrument_scope_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_alt_id) {
        auto gh9 = eh8.group_begin(1540, 1541);
        if (!gh9) return ::std::unexpected(gh9.error());
        for (auto const& item9 : *item8.instrument_scope_security_alt_id) {
            auto en9 = gh9->add_entry();
            if (!en9) return ::std::unexpected(en9.error());
            auto& eh9 = *en9;
    if (item9.instrument_scope_security_alt_id) {
        auto r = eh9.set_string(1541, *item9.instrument_scope_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item9.instrument_scope_security_alt_id_source) {
        auto r = eh9.set_string(1542, *item9.instrument_scope_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge9 = bb.group_end(*gh9);
        if (!ge9) return ::std::unexpected(ge9.error());
    }
    if (item8.instrument_scope_product) {
        auto r = eh8.set_int(1543, *item8.instrument_scope_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_product_complex) {
        auto r = eh8.set_string(1544, *item8.instrument_scope_product_complex);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_group) {
        auto r = eh8.set_string(1545, *item8.instrument_scope_security_group);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_cfi_code) {
        auto r = eh8.set_string(1546, *item8.instrument_scope_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_upi_code) {
        auto r = eh8.set_string(2895, *item8.instrument_scope_upi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_type) {
        auto r = eh8.set_string(1547, *item8.instrument_scope_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_sub_type) {
        auto r = eh8.set_string(1548, *item8.instrument_scope_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_maturity_month_year) {
        auto r = eh8.set_string(1549, *item8.instrument_scope_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_maturity_time) {
        auto r = eh8.set_string(1550, *item8.instrument_scope_maturity_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_restructuring_type) {
        auto r = eh8.set_string(1551, *item8.instrument_scope_restructuring_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_seniority) {
        auto r = eh8.set_string(1552, *item8.instrument_scope_seniority);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_put_or_call) {
        auto r = eh8.set_int(1553, *item8.instrument_scope_put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_flexible_indicator) {
        auto r = eh8.set_char(1554, (*item8.instrument_scope_flexible_indicator) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_coupon_rate) {
        auto r = eh8.set_decimal(1555, *item8.instrument_scope_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_exchange) {
        auto r = eh8.set_string(1616, *item8.instrument_scope_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_security_desc) {
        auto r = eh8.set_string(1556, *item8.instrument_scope_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.instrument_scope_encoded_security_desc) {
        auto r_len = eh8.set_int(1620, static_cast<::std::int64_t>(item8.instrument_scope_encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh8.set_string(1621, *item8.instrument_scope_encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item8.instrument_scope_settl_type) {
        auto r = eh8.set_string(1557, *item8.instrument_scope_settl_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge8 = bb.group_end(*gh8);
        if (!ge8) return ::std::unexpected(ge8.error());
    }
    if (item4.md_origin_type) {
        auto r = eh4.set_int(1024, *item4.md_origin_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.md_origin_desc) {
        auto r = eh4.set_string(3033, *item4.md_origin_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.md_origin_time) {
        auto r = eh4.set_string(3034, *item4.md_origin_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.test_step_group_id) {
        auto r = eh4.set_string(3035, *item4.test_step_group_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.test_steps) {
        auto gh10 = eh4.group_begin(3036, 3037);
        if (!gh10) return ::std::unexpected(gh10.error());
        for (auto const& item10 : *item4.test_steps) {
            auto en10 = gh10->add_entry();
            if (!en10) return ::std::unexpected(en10.error());
            auto& eh10 = *en10;
    if (item10.test_step_id) {
        auto r = eh10.set_string(3037, *item10.test_step_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_desc) {
        auto r = eh10.set_string(3038, *item10.test_step_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_start_time) {
        auto r = eh10.set_string(3039, *item10.test_step_start_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_start_offset_period) {
        auto r = eh10.set_int(3040, *item10.test_step_start_offset_period);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_start_offset_unit) {
        auto r = eh10.set_int(3041, *item10.test_step_start_offset_unit);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_end_time) {
        auto r = eh10.set_string(3042, *item10.test_step_end_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_end_offset_period) {
        auto r = eh10.set_int(3043, *item10.test_step_end_offset_period);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_end_offset_unit) {
        auto r = eh10.set_int(3044, *item10.test_step_end_offset_unit);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.test_step_parameters) {
        auto gh11 = eh10.group_begin(3045, 3046);
        if (!gh11) return ::std::unexpected(gh11.error());
        for (auto const& item11 : *item10.test_step_parameters) {
            auto en11 = gh11->add_entry();
            if (!en11) return ::std::unexpected(en11.error());
            auto& eh11 = *en11;
    if (item11.test_step_parameter_name) {
        auto r = eh11.set_string(3046, *item11.test_step_parameter_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item11.test_step_parameter_type) {
        auto r = eh11.set_int(3047, *item11.test_step_parameter_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item11.test_step_parameter_value) {
        auto r = eh11.set_string(3048, *item11.test_step_parameter_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge11 = bb.group_end(*gh11);
        if (!ge11) return ::std::unexpected(ge11.error());
    }
        }
        auto ge10 = bb.group_end(*gh10);
        if (!ge10) return ::std::unexpected(ge10.error());
    }
    if (item4.test_system_modules) {
        auto gh12 = eh4.group_begin(3049, 3050);
        if (!gh12) return ::std::unexpected(gh12.error());
        for (auto const& item12 : *item4.test_system_modules) {
            auto en12 = gh12->add_entry();
            if (!en12) return ::std::unexpected(en12.error());
            auto& eh12 = *en12;
    if (item12.test_system_module_name) {
        auto r = eh12.set_string(3050, *item12.test_system_module_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item12.test_system_module_version) {
        auto r = eh12.set_string(3051, *item12.test_system_module_version);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item12.test_system_module_last_update_time) {
        auto r = eh12.set_string(3081, *item12.test_system_module_last_update_time);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge12 = bb.group_end(*gh12);
        if (!ge12) return ::std::unexpected(ge12.error());
    }
    if (item4.test_measures) {
        auto gh13 = eh4.group_begin(3052, 3053);
        if (!gh13) return ::std::unexpected(gh13.error());
        for (auto const& item13 : *item4.test_measures) {
            auto en13 = gh13->add_entry();
            if (!en13) return ::std::unexpected(en13.error());
            auto& eh13 = *en13;
    if (item13.test_measure_name) {
        auto r = eh13.set_string(3053, *item13.test_measure_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_measure_desc) {
        auto r = eh13.set_string(3054, *item13.test_measure_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_measure_type) {
        auto r = eh13.set_int(3055, *item13.test_measure_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_measure_precision) {
        auto r = eh13.set_int(3056, *item13.test_measure_precision);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_measure_result) {
        auto r = eh13.set_int(3057, *item13.test_measure_result);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_threshold_type) {
        auto r = eh13.set_int(3058, *item13.test_threshold_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_warning_level_value) {
        auto r = eh13.set_decimal(3059, *item13.test_warning_level_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_fail_level_value) {
        auto r = eh13.set_decimal(3060, *item13.test_fail_level_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.test_peak_level_value) {
        auto r = eh13.set_decimal(3061, *item13.test_peak_level_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge13 = bb.group_end(*gh13);
        if (!ge13) return ::std::unexpected(ge13.error());
    }
    if (item4.test_orders) {
        auto gh14 = eh4.group_begin(3082, 3083);
        if (!gh14) return ::std::unexpected(gh14.error());
        for (auto const& item14 : *item4.test_orders) {
            auto en14 = gh14->add_entry();
            if (!en14) return ::std::unexpected(en14.error());
            auto& eh14 = *en14;
    if (item14.test_order_id) {
        auto r = eh14.set_string(3083, *item14.test_order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_symbol) {
        auto r = eh14.set_string(3084, *item14.test_order_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_security_id) {
        auto r = eh14.set_string(3085, *item14.test_order_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_security_id_source) {
        auto r = eh14.set_string(3086, *item14.test_order_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_price) {
        auto r = eh14.set_decimal(3087, *item14.test_order_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_price_type) {
        auto r = eh14.set_int(3088, *item14.test_order_price_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_qty) {
        auto r = eh14.set_decimal(3089, *item14.test_order_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_offset_period) {
        auto r = eh14.set_int(3090, *item14.test_order_offset_period);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.test_order_offset_unit) {
        auto r = eh14.set_int(3091, *item14.test_order_offset_unit);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge14 = bb.group_end(*gh14);
        if (!ge14) return ::std::unexpected(ge14.error());
    }
        }
        auto ge4 = bb.group_end(*gh4);
        if (!ge4) return ::std::unexpected(ge4.error());
    }
    if (args.algo_certificate_request_type) {
        auto r = bb.field(3077, *args.algo_certificate_request_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.test_scenario_group_id) {
        auto r = bb.field(3079, *args.test_scenario_group_id);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
