// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/AllocationInstructionAlertRequestAck.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "AllocationInstructionAlertRequestAck.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_AllocationInstructionAlertRequestAck(::std::span<::std::byte> out, AllocationInstructionAlertRequestAckArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"DV"};
    if (args.reject_text) {
        auto r = bb.field(1328, *args.reject_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_reject_text) {
        auto r_len = bb.field(1664, static_cast<::std::int64_t>(args.encoded_reject_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(1665, *args.encoded_reject_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.alloc_request_id) {
        auto r = bb.field(2758, *args.alloc_request_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.alloc_request_status) {
        auto r = bb.field(2768, *args.alloc_request_status);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
