// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/ApplicationMessageReport.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_1351_3Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct ApplicationMessageReportArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::string_view> appl_req_id{};
    ::std::optional<::std::span<const groups::G_1351_3Args>> appl_i_ds{};
    ::std::optional<::std::string_view> appl_report_id{};
    ::std::optional<::std::int64_t> appl_report_type{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_ApplicationMessageReport)
#include "ApplicationMessageReport.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_ApplicationMessageReport(::std::span<::std::byte> out, ApplicationMessageReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_ApplicationMessageReport)
#include "ApplicationMessageReport.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_ApplicationMessageReport(ApplicationMessageReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
