// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/ApplicationMessageReport.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "ApplicationMessageReport.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_ApplicationMessageReport(::std::span<::std::byte> out, ApplicationMessageReportArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"BY"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.appl_req_id) {
        auto r = bb.field(1346, *args.appl_req_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_i_ds) {
        auto gh0 = bb.group_begin(1351, 1355);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.appl_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.ref_appl_id) {
        auto r = eh0.set_string(1355, *item0.ref_appl_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.appl_new_seq_num) {
        auto r = eh0.set_int(1399, *item0.appl_new_seq_num);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.ref_appl_last_seq_num) {
        auto r = eh0.set_int(1357, *item0.ref_appl_last_seq_num);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.appl_report_id) {
        auto r = bb.field(1356, *args.appl_report_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_report_type) {
        auto r = bb.field(1426, *args.appl_report_type);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
