// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/ApplicationMessageRequestAck.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_453Args.hpp"
#include "../groups/G_1351_2Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct ApplicationMessageRequestAckArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::span<const groups::G_453Args>> party_i_ds{};
    ::std::optional<::std::string_view> appl_req_id{};
    ::std::optional<::std::int64_t> appl_req_type{};
    ::std::optional<::std::int64_t> appl_response_type{};
    ::std::optional<::std::int64_t> appl_total_message_count{};
    ::std::optional<::std::span<const groups::G_1351_2Args>> appl_i_ds{};
    ::std::optional<::std::string_view> appl_response_id{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_ApplicationMessageRequestAck)
#include "ApplicationMessageRequestAck.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_ApplicationMessageRequestAck(::std::span<::std::byte> out, ApplicationMessageRequestAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_ApplicationMessageRequestAck)
#include "ApplicationMessageRequestAck.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_ApplicationMessageRequestAck(ApplicationMessageRequestAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
