// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/BidResponse.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "BidResponse.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_BidResponse(::std::span<::std::byte> out, BidResponseArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"l"};
    if (args.bid_id) {
        auto r = bb.field(390, *args.bid_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.client_bid_id) {
        auto r = bb.field(391, *args.client_bid_id);
        if (!r) return ::std::unexpected(r.error());
    }
    {
        auto gh0 = bb.group_begin(420, 12);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : args.bid_components) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.commission) {
        auto r = eh0.set_decimal(12, *item0.commission);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.comm_type) {
        auto r = eh0.set_char(13, *item0.comm_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.comm_currency) {
        auto r = eh0.set_string(479, *item0.comm_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.comm_currency_code_source) {
        auto r = eh0.set_string(2922, *item0.comm_currency_code_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.comm_rate) {
        auto r = eh0.set_decimal(1233, *item0.comm_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.comm_unit_of_measure) {
        auto r = eh0.set_string(1238, *item0.comm_unit_of_measure);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.fund_renew_waiv) {
        auto r = eh0.set_char(497, *item0.fund_renew_waiv);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.list_id) {
        auto r = eh0.set_string(66, *item0.list_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.country) {
        auto r = eh0.set_string(421, *item0.country);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.side) {
        auto r = eh0.set_char(54, *item0.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.price) {
        auto r = eh0.set_decimal(44, *item0.price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.price_type) {
        auto r = eh0.set_int(423, *item0.price_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.fair_value) {
        auto r = eh0.set_decimal(406, *item0.fair_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.net_gross_ind) {
        auto r = eh0.set_int(430, *item0.net_gross_ind);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.settl_type) {
        auto r = eh0.set_string(63, *item0.settl_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.settl_date) {
        auto r = eh0.set_string(64, *item0.settl_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.trading_session_id) {
        auto r = eh0.set_string(336, *item0.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.trading_session_sub_id) {
        auto r = eh0.set_string(625, *item0.trading_session_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.text) {
        auto r = eh0.set_string(58, *item0.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_text) {
        auto r_len = eh0.set_int(354, static_cast<::std::int64_t>(item0.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(355, *item0.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
