// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/CollateralReportAck.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "CollateralReportAck.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_CollateralReportAck(::std::span<::std::byte> out, CollateralReportAckArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"DQ"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.party_i_ds) {
        auto gh0 = bb.group_begin(453, 448);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_id) {
        auto r = eh0.set_string(448, *item0.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_id_source) {
        auto r = eh0.set_char(447, *item0.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role) {
        auto r = eh0.set_int(452, *item0.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role_qualifier) {
        auto r = eh0.set_int(2376, *item0.party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_sub_i_ds) {
        auto gh1 = eh0.group_begin(802, 523);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_sub_id) {
        auto r = eh1.set_string(523, *item1.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_sub_id_type) {
        auto r = eh1.set_int(803, *item1.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.coll_rpt_id) {
        auto r = bb.field(908, *args.coll_rpt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.reject_text) {
        auto r = bb.field(1328, *args.reject_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_reject_text) {
        auto r_len = bb.field(1664, static_cast<::std::int64_t>(args.encoded_reject_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(1665, *args.encoded_reject_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.coll_rpt_reject_reason) {
        auto r = bb.field(2487, *args.coll_rpt_reject_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coll_rpt_status) {
        auto r = bb.field(2488, *args.coll_rpt_status);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
