// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/CollateralResponse.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_124_2Args.hpp"
#include "../groups/G_136Args.hpp"
#include "../groups/G_232Args.hpp"
#include "../groups/G_453Args.hpp"
#include "../groups/G_454Args.hpp"
#include "../groups/G_555_2Args.hpp"
#include "../groups/G_711_3Args.hpp"
#include "../groups/G_768Args.hpp"
#include "../groups/G_864Args.hpp"
#include "../groups/G_897Args.hpp"
#include "../groups/G_1018Args.hpp"
#include "../groups/G_1483Args.hpp"
#include "../groups/G_1703Args.hpp"
#include "../groups/G_1976Args.hpp"
#include "../groups/G_2304Args.hpp"
#include "../groups/G_40019Args.hpp"
#include "../groups/G_40022Args.hpp"
#include "../groups/G_40040Args.hpp"
#include "../groups/G_40042Args.hpp"
#include "../groups/G_40046Args.hpp"
#include "../groups/G_40049Args.hpp"
#include "../groups/G_40090Args.hpp"
#include "../groups/G_40181Args.hpp"
#include "../groups/G_40204Args.hpp"
#include "../groups/G_40278Args.hpp"
#include "../groups/G_41092Args.hpp"
#include "../groups/G_41094Args.hpp"
#include "../groups/G_41096Args.hpp"
#include "../groups/G_41116Args.hpp"
#include "../groups/G_41137Args.hpp"
#include "../groups/G_41140Args.hpp"
#include "../groups/G_41152Args.hpp"
#include "../groups/G_41230Args.hpp"
#include "../groups/G_42296Args.hpp"
#include "../groups/G_42775Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct CollateralResponseArgs {
    ::std::optional<::std::string_view> account{};
    ::std::optional<::std::string_view> cl_ord_id{};
    ::std::optional<::std::string_view> currency{};
    ::std::optional<::std::string_view> security_id_source{};
    ::std::optional<::std::string_view> order_id{};
    ::std::optional<::fixpp::decimal_t> price{};
    ::std::optional<::std::string_view> security_id{};
    ::std::optional<::fixpp::decimal_t> quantity{};
    ::std::optional<char> side{};
    ::std::optional<::std::string_view> symbol{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> settl_date{};
    ::std::optional<::std::string_view> symbol_sfx{};
    ::std::optional<::std::string_view> trade_date{};
    ::std::optional<::std::string_view> issuer{};
    ::std::optional<::std::string_view> security_desc{};
    ::std::optional<::std::span<const groups::G_124_2Args>> execs{};
    ::std::optional<::std::span<const groups::G_136Args>> misc_fees{};
    ::std::optional<::fixpp::decimal_t> accrued_interest_amt{};
    ::std::optional<::std::string_view> security_type{};
    ::std::optional<::std::string_view> secondary_order_id{};
    ::std::optional<::std::string_view> maturity_month_year{};
    ::std::optional<::std::int64_t> put_or_call{};
    ::std::optional<::fixpp::decimal_t> strike_price{};
    ::std::optional<char> opt_attribute{};
    ::std::optional<::std::string_view> security_exchange{};
    ::std::optional<::fixpp::decimal_t> spread{};
    ::std::optional<::std::string_view> benchmark_curve_currency{};
    ::std::optional<::std::string_view> benchmark_curve_name{};
    ::std::optional<::std::string_view> benchmark_curve_point{};
    ::std::optional<::fixpp::decimal_t> coupon_rate{};
    ::std::optional<::std::string_view> coupon_payment_date{};
    ::std::optional<::std::string_view> issue_date{};
    ::std::optional<::std::int64_t> repurchase_term{};
    ::std::optional<::fixpp::decimal_t> repurchase_rate{};
    ::std::optional<::fixpp::decimal_t> factor{};
    ::std::optional<::fixpp::decimal_t> contract_multiplier{};
    ::std::optional<::std::span<const groups::G_232Args>> stipulations{};
    ::std::optional<::std::string_view> repo_collateral_security_type{};
    ::std::optional<::std::string_view> redemption_date{};
    ::std::optional<::std::string_view> credit_rating{};
    ::std::optional<char> financial_status{};
    ::std::optional<::std::string_view> encoded_issuer{};
    ::std::optional<::std::string_view> encoded_security_desc{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::int64_t> price_type{};
    ::std::optional<::std::span<const groups::G_453Args>> party_i_ds{};
    ::std::optional<::std::span<const groups::G_454Args>> security_alt_id{};
    ::std::optional<::std::int64_t> product{};
    ::std::optional<::std::string_view> cfi_code{};
    ::std::optional<::std::string_view> country_of_issue{};
    ::std::optional<::std::string_view> state_or_province_of_issue{};
    ::std::optional<::std::string_view> locale_of_issue{};
    ::std::optional<::std::string_view> secondary_cl_ord_id{};
    ::std::optional<::std::string_view> maturity_date{};
    ::std::optional<::std::string_view> instr_registry{};
    ::std::optional<::std::span<const groups::G_555_2Args>> legs{};
    ::std::optional<::std::int64_t> account_type{};
    ::std::optional<::fixpp::decimal_t> benchmark_price{};
    ::std::optional<::std::int64_t> benchmark_price_type{};
    ::std::optional<::std::string_view> contract_settl_month{};
    ::std::optional<::std::string_view> pool{};
    ::std::optional<::std::string_view> benchmark_security_id{};
    ::std::optional<::std::span<const groups::G_711_3Args>> underlyings{};
    ::std::optional<::std::string_view> clearing_business_date{};
    ::std::optional<::std::string_view> benchmark_security_id_source{};
    ::std::optional<::std::string_view> security_sub_type{};
    ::std::optional<::std::span<const groups::G_768Args>> trd_reg_timestamps{};
    ::std::optional<::std::int64_t> termination_type{};
    ::std::optional<::std::int64_t> qty_type{};
    ::std::optional<::std::span<const groups::G_864Args>> events{};
    ::std::optional<::std::string_view> dated_date{};
    ::std::optional<::std::string_view> interest_accrual_date{};
    ::std::optional<::std::int64_t> cp_program{};
    ::std::optional<::std::string_view> cp_reg_type{};
    ::std::optional<::std::string_view> coll_req_id{};
    ::std::optional<::std::int64_t> coll_asgn_reason{};
    ::std::optional<::std::span<const groups::G_897Args>> trades{};
    ::std::optional<::fixpp::decimal_t> margin_ratio{};
    ::std::optional<::fixpp::decimal_t> margin_excess{};
    ::std::optional<::fixpp::decimal_t> total_net_value{};
    ::std::optional<::fixpp::decimal_t> cash_outstanding{};
    ::std::optional<::std::string_view> coll_asgn_id{};
    ::std::optional<::std::int64_t> coll_asgn_trans_type{};
    ::std::optional<::std::string_view> coll_resp_id{};
    ::std::optional<::std::int64_t> coll_asgn_resp_type{};
    ::std::optional<::std::int64_t> coll_asgn_reject_reason{};
    ::std::optional<::std::string_view> agreement_desc{};
    ::std::optional<::std::string_view> agreement_id{};
    ::std::optional<::std::string_view> agreement_date{};
    ::std::optional<::std::string_view> start_date{};
    ::std::optional<::std::string_view> end_date{};
    ::std::optional<::std::string_view> agreement_currency{};
    ::std::optional<::std::int64_t> delivery_type{};
    ::std::optional<::fixpp::decimal_t> end_accrued_interest_amt{};
    ::std::optional<::fixpp::decimal_t> start_cash{};
    ::std::optional<::fixpp::decimal_t> end_cash{};
    ::std::optional<::std::string_view> strike_currency{};
    ::std::optional<::std::string_view> security_status{};
    ::std::optional<::std::string_view> settle_on_open_flag{};
    ::std::optional<::fixpp::decimal_t> strike_multiplier{};
    ::std::optional<::fixpp::decimal_t> strike_value{};
    ::std::optional<::fixpp::decimal_t> min_price_increment{};
    ::std::optional<::std::int64_t> position_limit{};
    ::std::optional<::std::int64_t> nt_position_limit{};
    ::std::optional<::std::string_view> unit_of_measure{};
    ::std::optional<::std::string_view> time_unit{};
    ::std::optional<::std::span<const groups::G_1018Args>> instrument_parties{};
    ::std::optional<::std::int64_t> coll_appl_type{};
    ::std::optional<char> instrmt_assignment_method{};
    ::std::optional<::std::string_view> maturity_time{};
    ::std::optional<::fixpp::decimal_t> min_price_increment_amount{};
    ::std::optional<::fixpp::decimal_t> unit_of_measure_qty{};
    ::std::optional<::std::string_view> security_group{};
    ::std::optional<::std::string_view> security_xml{};
    ::std::optional<::std::string_view> security_xml_schema{};
    ::std::optional<::std::string_view> price_unit_of_measure{};
    ::std::optional<::fixpp::decimal_t> price_unit_of_measure_qty{};
    ::std::optional<::std::string_view> settl_method{};
    ::std::optional<::std::int64_t> exercise_style{};
    ::std::optional<::fixpp::decimal_t> opt_payout_amount{};
    ::std::optional<::std::string_view> price_quote_method{};
    ::std::optional<::std::string_view> valuation_method{};
    ::std::optional<::std::int64_t> list_method{};
    ::std::optional<::fixpp::decimal_t> cap_price{};
    ::std::optional<::fixpp::decimal_t> floor_price{};
    ::std::optional<::std::string_view> product_complex{};
    ::std::optional<bool> flex_product_eligibility_indicator{};
    ::std::optional<bool> flexible_indicator{};
    ::std::optional<::std::string_view> reject_text{};
    ::std::optional<::std::int64_t> contract_multiplier_unit{};
    ::std::optional<::std::int64_t> flow_schedule_type{};
    ::std::optional<::std::string_view> restructuring_type{};
    ::std::optional<::std::string_view> seniority{};
    ::std::optional<::fixpp::decimal_t> notional_percentage_outstanding{};
    ::std::optional<::fixpp::decimal_t> original_notional_percentage_outstanding{};
    ::std::optional<::fixpp::decimal_t> attachment_point{};
    ::std::optional<::fixpp::decimal_t> detachment_point{};
    ::std::optional<::std::int64_t> strike_price_determination_method{};
    ::std::optional<::std::int64_t> strike_price_boundary_method{};
    ::std::optional<::fixpp::decimal_t> strike_price_boundary_precision{};
    ::std::optional<::std::int64_t> underlying_price_determination_method{};
    ::std::optional<::std::int64_t> opt_payout_type{};
    ::std::optional<::std::span<const groups::G_1483Args>> complex_events{};
    ::std::optional<::std::string_view> documentation_text{};
    ::std::optional<::std::string_view> price_quote_currency{};
    ::std::optional<::std::string_view> encoded_documentation_text{};
    ::std::optional<::std::string_view> swap_sub_class{};
    ::std::optional<::std::string_view> settl_rate_index{};
    ::std::optional<::std::string_view> settl_rate_index_location{};
    ::std::optional<::std::string_view> option_expiration_desc{};
    ::std::optional<::std::string_view> encoded_reject_text{};
    ::std::optional<::std::string_view> encoded_option_expiration_desc{};
    ::std::optional<::std::int64_t> short_sale_restriction{};
    ::std::optional<::std::string_view> strike_unit_of_measure{};
    ::std::optional<::std::span<const groups::G_1703Args>> collateral_amounts{};
    ::std::optional<::std::string_view> unit_of_measure_currency{};
    ::std::optional<::std::string_view> price_unit_of_measure_currency{};
    ::std::optional<::std::string_view> obligation_type{};
    ::std::optional<::std::int64_t> ref_tick_table_id{};
    ::std::optional<::std::string_view> strike_index{};
    ::std::optional<::std::int64_t> asset_class{};
    ::std::optional<::std::int64_t> asset_sub_class{};
    ::std::optional<::std::string_view> asset_type{};
    ::std::optional<::std::string_view> swap_class{};
    ::std::optional<::std::int64_t> nth_to_default{};
    ::std::optional<::std::int64_t> mth_to_default{};
    ::std::optional<::std::string_view> settled_entity_matrix_source{};
    ::std::optional<::std::string_view> settled_entity_matrix_publication_date{};
    ::std::optional<::std::int64_t> coupon_type{};
    ::std::optional<::fixpp::decimal_t> total_issued_amount{};
    ::std::optional<::std::int64_t> coupon_frequency_period{};
    ::std::optional<::std::string_view> coupon_frequency_unit{};
    ::std::optional<::std::int64_t> coupon_day_count{};
    ::std::optional<::std::string_view> convertible_bond_equity_id{};
    ::std::optional<::std::string_view> convertible_bond_equity_id_source{};
    ::std::optional<::std::string_view> contract_price_ref_month{};
    ::std::optional<::std::int64_t> lien_seniority{};
    ::std::optional<::std::int64_t> loan_facility{};
    ::std::optional<::std::int64_t> reference_entity_type{};
    ::std::optional<::std::int64_t> index_series{};
    ::std::optional<::std::int64_t> index_annex_version{};
    ::std::optional<::std::string_view> index_annex_date{};
    ::std::optional<::std::string_view> index_annex_source{};
    ::std::optional<::std::string_view> agreement_version{};
    ::std::optional<::std::string_view> master_confirmation_desc{};
    ::std::optional<::std::string_view> master_confirmation_date{};
    ::std::optional<::std::string_view> master_confirmation_annex_desc{};
    ::std::optional<::std::string_view> master_confirmation_annex_date{};
    ::std::optional<::std::string_view> broker_confirmation_desc{};
    ::std::optional<::std::string_view> credit_support_agreement_desc{};
    ::std::optional<::std::string_view> credit_support_agreement_date{};
    ::std::optional<::std::string_view> credit_support_agreement_id{};
    ::std::optional<::std::string_view> governing_law{};
    ::std::optional<::std::span<const groups::G_1976Args>> secondary_asset_classes{};
    ::std::optional<::fixpp::decimal_t> strike_index_spread{};
    ::std::optional<::std::string_view> valuation_source{};
    ::std::optional<::std::string_view> valuation_reference_model{};
    ::std::optional<::std::string_view> strategy_type{};
    ::std::optional<bool> common_pricing_indicator{};
    ::std::optional<::std::int64_t> settl_disruption_provision{};
    ::std::optional<char> instrument_rounding_direction{};
    ::std::optional<::std::int64_t> instrument_rounding_precision{};
    ::std::optional<::std::int64_t> asset_group{};
    ::std::optional<::std::span<const groups::G_2304Args>> asset_attributes{};
    ::std::optional<::std::int64_t> trading_unit_period_multiplier{};
    ::std::optional<::std::string_view> firm_transaction_id{};
    ::std::optional<::std::string_view> transaction_id{};
    ::std::optional<::std::string_view> wire_reference{};
    ::std::optional<::std::string_view> collateral_request_instruction{};
    ::std::optional<::std::string_view> collateral_request_link_id{};
    ::std::optional<::std::int64_t> collateral_request_number{};
    ::std::optional<::std::int64_t> tot_num_collateral_requests{};
    ::std::optional<::std::string_view> warning_text{};
    ::std::optional<::std::string_view> encoded_warning_text{};
    ::std::optional<bool> low_exercise_price_option_indicator{};
    ::std::optional<bool> block_trade_eligibility_indicator{};
    ::std::optional<::std::int64_t> instrument_price_precision{};
    ::std::optional<::std::int64_t> strike_price_precision{};
    ::std::optional<::fixpp::decimal_t> orig_strike_price{};
    ::std::optional<::std::int64_t> settl_sub_method{};
    ::std::optional<::std::string_view> strike_index_curve_point{};
    ::std::optional<::std::int64_t> strike_index_quote{};
    ::std::optional<::std::int64_t> extraordinary_event_adjustment_method{};
    ::std::optional<bool> exchange_look_alike{};
    ::std::optional<::std::int64_t> in_the_money_condition{};
    ::std::optional<bool> contrary_instruction_eligibility_indicator{};
    ::std::optional<::std::string_view> financial_instrument_full_name{};
    ::std::optional<::std::string_view> encoded_financial_instrument_full_name{};
    ::std::optional<::std::string_view> asset_sub_type{};
    ::std::optional<::std::string_view> financial_instrument_short_name{};
    ::std::optional<::std::string_view> delivery_route_or_charter{};
    ::std::optional<::std::int64_t> return_trigger{};
    ::std::optional<::std::string_view> coupon_other_day_count{};
    ::std::optional<::std::string_view> upi_code{};
    ::std::optional<::std::string_view> currency_code_source{};
    ::std::optional<::std::string_view> strike_currency_code_source{};
    ::std::optional<::std::string_view> unit_of_measure_currency_code_source{};
    ::std::optional<::std::string_view> price_unit_of_measure_currency_code_source{};
    ::std::optional<::std::string_view> price_quote_currency_code_source{};
    ::std::optional<::std::string_view> benchmark_curve_currency_code_source{};
    ::std::optional<::std::string_view> agreement_currency_code_source{};
    ::std::optional<::std::string_view> security_reference_data_supplement{};
    ::std::optional<::std::string_view> maturity_frequency_unit{};
    ::std::optional<::std::int64_t> maturity_frequency_period{};
    ::std::optional<::fixpp::decimal_t> margin_price{};
    ::std::optional<::std::span<const groups::G_40019Args>> additional_terms{};
    ::std::optional<::std::span<const groups::G_40022Args>> cash_settl_terms{};
    ::std::optional<::std::span<const groups::G_40040Args>> contractual_definitions{};
    ::std::optional<::std::span<const groups::G_40042Args>> contractual_matrices{};
    ::std::optional<::std::span<const groups::G_40046Args>> financing_term_supplements{};
    ::std::optional<::std::span<const groups::G_40049Args>> streams{};
    ::std::optional<::std::span<const groups::G_40090Args>> provisions{};
    ::std::optional<::std::span<const groups::G_40181Args>> protection_terms{};
    ::std::optional<::std::span<const groups::G_40204Args>> physical_settl_terms{};
    ::std::optional<::std::span<const groups::G_40278Args>> business_centers{};
    ::std::optional<::std::int64_t> business_day_convention{};
    ::std::optional<::std::string_view> date_roll_convention{};
    ::std::optional<::std::int64_t> market_disruption_provision{};
    ::std::optional<::std::int64_t> market_disruption_fallback_provision{};
    ::std::optional<::std::int64_t> market_disruption_maximum_days{};
    ::std::optional<::fixpp::decimal_t> market_disruption_materiality_percentage{};
    ::std::optional<::std::int64_t> market_disruption_minimum_futures_contracts{};
    ::std::optional<::std::span<const groups::G_41092Args>> market_disruption_events{};
    ::std::optional<::std::span<const groups::G_41094Args>> market_disruption_fallbacks{};
    ::std::optional<::std::span<const groups::G_41096Args>> market_disruption_fallback_reference_prices{};
    ::std::optional<::std::string_view> exercise_desc{};
    ::std::optional<::std::string_view> encoded_exercise_desc{};
    ::std::optional<bool> automatic_exercise_indicator{};
    ::std::optional<::fixpp::decimal_t> automatic_exercise_threshold_rate{};
    ::std::optional<::std::int64_t> exercise_confirmation_method{};
    ::std::optional<::std::string_view> manual_notice_business_center{};
    ::std::optional<bool> fallback_exercise_indicator{};
    ::std::optional<bool> limited_right_to_confirm_indicator{};
    ::std::optional<bool> exercise_split_ticket_indicator{};
    ::std::optional<::std::span<const groups::G_41116Args>> option_exercise_business_centers{};
    ::std::optional<::std::int64_t> option_exercise_business_day_convention{};
    ::std::optional<::std::int64_t> option_exercise_earliest_date_offset_day_type{};
    ::std::optional<::std::int64_t> option_exercise_earliest_date_offset_period{};
    ::std::optional<::std::string_view> option_exercise_earliest_date_offset_unit{};
    ::std::optional<::std::int64_t> option_exercise_frequency_period{};
    ::std::optional<::std::string_view> option_exercise_frequency_unit{};
    ::std::optional<::std::string_view> option_exercise_start_date_unadjusted{};
    ::std::optional<::std::int64_t> option_exercise_start_date_relative_to{};
    ::std::optional<::std::int64_t> option_exercise_start_date_offset_period{};
    ::std::optional<::std::string_view> option_exercise_start_date_offset_unit{};
    ::std::optional<::std::int64_t> option_exercise_start_date_offset_day_type{};
    ::std::optional<::std::string_view> option_exercise_start_date_adjusted{};
    ::std::optional<::std::int64_t> option_exercise_skip{};
    ::std::optional<::std::string_view> option_exercise_nomination_deadline{};
    ::std::optional<::std::string_view> option_exercise_first_date_unadjusted{};
    ::std::optional<::std::string_view> option_exercise_last_date_unadjusted{};
    ::std::optional<::std::string_view> option_exercise_earliest_time{};
    ::std::optional<::std::string_view> option_exercise_latest_time{};
    ::std::optional<::std::string_view> option_exercise_time_business_center{};
    ::std::optional<::std::span<const groups::G_41137Args>> option_exercise_dates{};
    ::std::optional<::std::span<const groups::G_41140Args>> option_exercise_expiration_date_business_centers{};
    ::std::optional<::std::int64_t> option_exercise_expiration_date_business_day_convention{};
    ::std::optional<::std::int64_t> option_exercise_expiration_date_relative_to{};
    ::std::optional<::std::int64_t> option_exercise_expiration_date_offset_period{};
    ::std::optional<::std::string_view> option_exercise_expiration_date_offset_unit{};
    ::std::optional<::std::int64_t> option_exercise_expiration_frequency_period{};
    ::std::optional<::std::string_view> option_exercise_expiration_frequency_unit{};
    ::std::optional<::std::string_view> option_exercise_expiration_roll_convention{};
    ::std::optional<::std::int64_t> option_exercise_expiration_date_offset_day_type{};
    ::std::optional<::std::string_view> option_exercise_expiration_time{};
    ::std::optional<::std::string_view> option_exercise_expiration_time_business_center{};
    ::std::optional<::std::span<const groups::G_41152Args>> option_exercise_expiration_dates{};
    ::std::optional<::std::span<const groups::G_41230Args>> pricing_date_business_centers{};
    ::std::optional<::std::string_view> pricing_date_unadjusted{};
    ::std::optional<::std::int64_t> pricing_date_business_day_convention{};
    ::std::optional<::std::string_view> pricing_date_adjusted{};
    ::std::optional<::std::string_view> pricing_time{};
    ::std::optional<::std::string_view> pricing_time_business_center{};
    ::std::optional<::std::span<const groups::G_42296Args>> extraordinary_events{};
    ::std::optional<::std::int64_t> settl_method_electing_party_side{};
    ::std::optional<::std::string_view> make_whole_date{};
    ::std::optional<::fixpp::decimal_t> make_whole_amount{};
    ::std::optional<::std::string_view> make_whole_benchmark_curve_name{};
    ::std::optional<::std::string_view> make_whole_benchmark_curve_point{};
    ::std::optional<::fixpp::decimal_t> make_whole_recall_spread{};
    ::std::optional<::std::int64_t> make_whole_benchmark_quote{};
    ::std::optional<::std::int64_t> make_whole_interpolation_method{};
    ::std::optional<::std::span<const groups::G_42775Args>> settl_method_election_date_business_centers{};
    ::std::optional<::std::string_view> settl_method_election_date_unadjusted{};
    ::std::optional<::std::int64_t> settl_method_election_date_business_day_convention{};
    ::std::optional<::std::int64_t> settl_method_election_date_relative_to{};
    ::std::optional<::std::int64_t> settl_method_election_date_offset_period{};
    ::std::optional<::std::string_view> settl_method_election_date_offset_unit{};
    ::std::optional<::std::int64_t> settl_method_election_date_offset_day_type{};
    ::std::optional<::std::string_view> settl_method_election_date_adjusted{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_CollateralResponse)
#include "CollateralResponse.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_CollateralResponse(::std::span<::std::byte> out, CollateralResponseArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_CollateralResponse)
#include "CollateralResponse.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_CollateralResponse(CollateralResponseArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
