// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/ConfirmationAck.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "ConfirmationAck.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_ConfirmationAck(::std::span<::std::byte> out, ConfirmationAckArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"AU"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trade_date) {
        auto r = bb.field(75, *args.trade_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.match_status) {
        auto r = bb.field(573, *args.match_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.confirm_id) {
        auto r = bb.field(664, *args.confirm_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.confirm_rej_reason) {
        auto r = bb.field(774, *args.confirm_rej_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.affirm_status) {
        auto r = bb.field(940, *args.affirm_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.regulatory_trade_i_ds) {
        auto gh0 = bb.group_begin(1907, 1903);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.regulatory_trade_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.regulatory_trade_id) {
        auto r = eh0.set_string(1903, *item0.regulatory_trade_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.regulatory_trade_id_source) {
        auto r = eh0.set_string(1905, *item0.regulatory_trade_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.regulatory_trade_id_event) {
        auto r = eh0.set_int(1904, *item0.regulatory_trade_id_event);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.regulatory_trade_id_type) {
        auto r = eh0.set_int(1906, *item0.regulatory_trade_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.regulatory_leg_ref_id) {
        auto r = eh0.set_string(2411, *item0.regulatory_leg_ref_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.regulatory_trade_id_scope) {
        auto r = eh0.set_int(2397, *item0.regulatory_trade_id_scope);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.trade_confirmation_reference_id) {
        auto r = bb.field(2390, *args.trade_confirmation_reference_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.match_exceptions) {
        auto gh1 = bb.group_begin(2772, 2773);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *args.match_exceptions) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.match_exception_type) {
        auto r = eh1.set_int(2773, *item1.match_exception_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.match_exception_element_type) {
        auto r = eh1.set_int(2774, *item1.match_exception_element_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.match_exception_element_name) {
        auto r = eh1.set_string(2775, *item1.match_exception_element_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.match_exception_alloc_value) {
        auto r = eh1.set_string(2776, *item1.match_exception_alloc_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.match_exception_confirm_value) {
        auto r = eh1.set_string(2777, *item1.match_exception_confirm_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.match_exception_tolerance_value) {
        auto r = eh1.set_decimal(2778, *item1.match_exception_tolerance_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.match_exception_tolerance_value_type) {
        auto r = eh1.set_int(2779, *item1.match_exception_tolerance_value_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.match_exception_text) {
        auto r = eh1.set_string(2780, *item1.match_exception_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.encoded_match_exception_text) {
        auto r_len = eh1.set_int(2797, static_cast<::std::int64_t>(item1.encoded_match_exception_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh1.set_string(2798, *item1.encoded_match_exception_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
    if (args.matching_data_points) {
        auto gh2 = bb.group_begin(2781, 2782);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *args.matching_data_points) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.matching_data_point_indicator) {
        auto r = eh2.set_int(2782, *item2.matching_data_point_indicator);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.matching_data_point_value) {
        auto r = eh2.set_string(2783, *item2.matching_data_point_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.matching_data_point_type) {
        auto r = eh2.set_int(2784, *item2.matching_data_point_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.matching_data_point_name) {
        auto r = eh2.set_string(2785, *item2.matching_data_point_name);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
