// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/ListStatus.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "ListStatus.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_ListStatus(::std::span<::std::byte> out, ListStatusArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"N"};
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_id) {
        auto r = bb.field(66, *args.list_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.tot_no_orders) {
        auto r = bb.field(68, *args.tot_no_orders);
        if (!r) return ::std::unexpected(r.error());
    }
    {
        auto gh0 = bb.group_begin(73, 11);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : args.orders) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.cl_ord_id) {
        auto r = eh0.set_string(11, *item0.cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.order_id) {
        auto r = eh0.set_string(37, *item0.order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.secondary_cl_ord_id) {
        auto r = eh0.set_string(526, *item0.secondary_cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.cum_qty) {
        auto r = eh0.set_decimal(14, *item0.cum_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.ord_status) {
        auto r = eh0.set_char(39, *item0.ord_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.working_indicator) {
        auto r = eh0.set_char(636, (*item0.working_indicator) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.leaves_qty) {
        auto r = eh0.set_decimal(151, *item0.leaves_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.cxl_qty) {
        auto r = eh0.set_decimal(84, *item0.cxl_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.avg_px) {
        auto r = eh0.set_decimal(6, *item0.avg_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.ord_rej_reason) {
        auto r = eh0.set_int(103, *item0.ord_rej_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.text) {
        auto r = eh0.set_string(58, *item0.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_text) {
        auto r_len = eh0.set_int(354, static_cast<::std::int64_t>(item0.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(355, *item0.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.no_rpts) {
        auto r = bb.field(82, *args.no_rpts);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.rpt_seq) {
        auto r = bb.field(83, *args.rpt_seq);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_status_type) {
        auto r = bb.field(429, *args.list_status_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_order_status) {
        auto r = bb.field(431, *args.list_order_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_status_text) {
        auto r = bb.field(444, *args.list_status_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_list_status_text) {
        auto r_len = bb.field(445, static_cast<::std::int64_t>(args.encoded_list_status_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(446, *args.encoded_list_status_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.last_fragment) {
        auto r = bb.field(893, (*args.last_fragment) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contingency_type) {
        auto r = bb.field(1385, *args.contingency_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_reject_reason) {
        auto r = bb.field(1386, *args.list_reject_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
