// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/ListStatusRequest.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct ListStatusRequestArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> list_id{};
    ::std::optional<::std::string_view> encoded_text{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_ListStatusRequest)
#include "ListStatusRequest.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_ListStatusRequest(::std::span<::std::byte> out, ListStatusRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_ListStatusRequest)
#include "ListStatusRequest.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_ListStatusRequest(ListStatusRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
