// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/MarketDefinition.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_136Args.hpp"
#include "../groups/G_453Args.hpp"
#include "../groups/G_1141Args.hpp"
#include "../groups/G_1205Args.hpp"
#include "../groups/G_1232Args.hpp"
#include "../groups/G_1234Args.hpp"
#include "../groups/G_1235Args.hpp"
#include "../groups/G_1237Args.hpp"
#include "../groups/G_1239Args.hpp"
#include "../groups/G_1656Args.hpp"
#include "../groups/G_2545Args.hpp"
#include "../groups/G_2548Args.hpp"
#include "../groups/G_2550Args.hpp"
#include "../groups/G_2558Args.hpp"
#include "../groups/G_2560Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct MarketDefinitionArgs {
    ::std::optional<::std::string_view> currency{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::span<const groups::G_136Args>> misc_fees{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::int64_t> price_type{};
    ::std::optional<::std::span<const groups::G_453Args>> party_i_ds{};
    ::std::optional<::fixpp::decimal_t> round_lot{};
    ::std::optional<::fixpp::decimal_t> min_trade_vol{};
    ::std::optional<::std::int64_t> expiration_cycle{};
    ::std::optional<::fixpp::decimal_t> max_trade_vol{};
    ::std::optional<::std::span<const groups::G_1141Args>> md_feed_types{};
    ::std::optional<::fixpp::decimal_t> max_price_variation{};
    ::std::optional<::std::int64_t> implied_market_indicator{};
    ::std::optional<::fixpp::decimal_t> low_limit_price{};
    ::std::optional<::fixpp::decimal_t> high_limit_price{};
    ::std::optional<::fixpp::decimal_t> trading_reference_price{};
    ::std::optional<::std::string_view> appl_id{};
    ::std::optional<::std::int64_t> appl_seq_num{};
    ::std::optional<::std::span<const groups::G_1205Args>> tick_rules{};
    ::std::optional<::std::span<const groups::G_1232Args>> exec_inst_rules{};
    ::std::optional<::std::span<const groups::G_1234Args>> lot_type_rules{};
    ::std::optional<::std::span<const groups::G_1235Args>> match_rules{};
    ::std::optional<::std::span<const groups::G_1237Args>> ord_type_rules{};
    ::std::optional<::std::span<const groups::G_1239Args>> time_in_force_rules{};
    ::std::optional<::std::string_view> trading_currency{};
    ::std::optional<::std::string_view> market_segment_id{};
    ::std::optional<::std::string_view> market_id{};
    ::std::optional<::std::int64_t> price_limit_type{};
    ::std::optional<::std::string_view> parent_mkt_segm_id{};
    ::std::optional<::std::int64_t> appl_last_seq_num{};
    ::std::optional<bool> appl_resend_flag{};
    ::std::optional<::std::int64_t> multileg_model{};
    ::std::optional<::std::int64_t> multileg_price_method{};
    ::std::optional<::std::string_view> market_req_id{};
    ::std::optional<::std::string_view> market_report_id{};
    ::std::optional<::std::string_view> market_segment_desc{};
    ::std::optional<::std::string_view> encoded_mkt_segm_desc{};
    ::std::optional<::std::span<const groups::G_1656Args>> instrument_scopes{};
    ::std::optional<::std::int64_t> trade_vol_type{};
    ::std::optional<::std::string_view> effective_business_date{};
    ::std::optional<::std::int64_t> market_segment_status{};
    ::std::optional<::std::int64_t> market_segment_type{};
    ::std::optional<::std::int64_t> market_segment_sub_type{};
    ::std::optional<::std::span<const groups::G_2545Args>> related_market_segments{};
    ::std::optional<::std::span<const groups::G_2548Args>> auction_type_rules{};
    ::std::optional<::std::span<const groups::G_2550Args>> price_range_rules{};
    ::std::optional<::fixpp::decimal_t> fast_market_percentage{};
    ::std::optional<::std::span<const groups::G_2558Args>> quote_size_rules{};
    ::std::optional<bool> quote_side_indicator{};
    ::std::optional<::std::span<const groups::G_2560Args>> flex_product_eligibilities{};
    ::std::optional<::std::string_view> currency_code_source{};
    ::std::optional<::std::string_view> trading_currency_code_source{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_MarketDefinition)
#include "MarketDefinition.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_MarketDefinition(::std::span<::std::byte> out, MarketDefinitionArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_MarketDefinition)
#include "MarketDefinition.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_MarketDefinition(MarketDefinitionArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
