// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/MarketDataRequestReject.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "MarketDataRequestReject.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_MarketDataRequestReject(::std::span<::std::byte> out, MarketDataRequestRejectArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"Y"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.md_req_id) {
        auto r = bb.field(262, *args.md_req_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.md_req_rej_reason) {
        auto r = bb.field(281, *args.md_req_rej_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.party_i_ds) {
        auto gh0 = bb.group_begin(453, 448);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_id) {
        auto r = eh0.set_string(448, *item0.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_id_source) {
        auto r = eh0.set_char(447, *item0.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role) {
        auto r = eh0.set_int(452, *item0.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role_qualifier) {
        auto r = eh0.set_int(2376, *item0.party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_sub_i_ds) {
        auto gh1 = eh0.group_begin(802, 523);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_sub_id) {
        auto r = eh1.set_string(523, *item1.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_sub_id_type) {
        auto r = eh1.set_int(803, *item1.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.alt_md_source) {
        auto gh2 = bb.group_begin(816, 817);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *args.alt_md_source) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.alt_md_source_id) {
        auto r = eh2.set_string(817, *item2.alt_md_source_id);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
