// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/MarketDataRequestReject.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_453Args.hpp"
#include "../groups/G_816Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct MarketDataRequestRejectArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> md_req_id{};
    ::std::optional<char> md_req_rej_reason{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::span<const groups::G_453Args>> party_i_ds{};
    ::std::optional<::std::span<const groups::G_816Args>> alt_md_source{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_MarketDataRequestReject)
#include "MarketDataRequestReject.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_MarketDataRequestReject(::std::span<::std::byte> out, MarketDataRequestRejectArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_MarketDataRequestReject)
#include "MarketDataRequestReject.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_MarketDataRequestReject(MarketDataRequestRejectArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
