// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/MassQuoteAck.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_296_1Args.hpp"
#include "../groups/G_453Args.hpp"
#include "../groups/G_1461Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct MassQuoteAckArgs {
    ::std::optional<::std::string_view> account{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> quote_id{};
    ::std::optional<::std::string_view> quote_req_id{};
    ::std::optional<::std::span<const groups::G_296_1Args>> quote_sets{};
    ::std::optional<::std::int64_t> quote_status{};
    ::std::optional<::std::int64_t> quote_cancel_type{};
    ::std::optional<::std::int64_t> quote_reject_reason{};
    ::std::optional<::std::int64_t> quote_response_level{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::string_view> compliance_id{};
    ::std::optional<::std::span<const groups::G_453Args>> party_i_ds{};
    ::std::optional<::std::int64_t> quote_type{};
    ::std::optional<::std::int64_t> account_type{};
    ::std::optional<::std::int64_t> acct_id_source{};
    ::std::optional<::std::span<const groups::G_1461Args>> target_party_i_ds{};
    ::std::optional<::std::int64_t> throttle_status{};
    ::std::optional<::std::int64_t> throttle_inst{};
    ::std::optional<::std::int64_t> throttle_count_indicator{};
    ::std::optional<::std::string_view> encoded_compliance_text{};
    ::std::optional<::std::string_view> compliance_text{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_MassQuoteAck)
#include "MassQuoteAck.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_MassQuoteAck(::std::span<::std::byte> out, MassQuoteAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_MassQuoteAck)
#include "MassQuoteAck.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_MassQuoteAck(MassQuoteAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
