// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/OrderCancelReject.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "OrderCancelReject.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_OrderCancelReject(::std::span<::std::byte> out, OrderCancelRejectArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"9"};
    if (args.account) {
        auto r = bb.field(1, *args.account);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cl_ord_id) {
        auto r = bb.field(11, *args.cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.order_id) {
        auto r = bb.field(37, *args.order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.ord_status) {
        auto r = bb.field(39, *args.ord_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.orig_cl_ord_id) {
        auto r = bb.field(41, *args.orig_cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_id) {
        auto r = bb.field(66, *args.list_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trade_date) {
        auto r = bb.field(75, *args.trade_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.ex_destination) {
        auto r = bb.field(100, *args.ex_destination);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cxl_rej_reason) {
        auto r = bb.field(102, *args.cxl_rej_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.secondary_order_id) {
        auto r = bb.field(198, *args.secondary_order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trade_origination_date) {
        auto r = bb.field(229, *args.trade_origination_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.cxl_rej_response_to) {
        auto r = bb.field(434, *args.cxl_rej_response_to);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_i_ds) {
        auto gh0 = bb.group_begin(453, 448);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_id) {
        auto r = eh0.set_string(448, *item0.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_id_source) {
        auto r = eh0.set_char(447, *item0.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role) {
        auto r = eh0.set_int(452, *item0.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role_qualifier) {
        auto r = eh0.set_int(2376, *item0.party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_sub_i_ds) {
        auto gh1 = eh0.group_begin(802, 523);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_sub_id) {
        auto r = eh1.set_string(523, *item1.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_sub_id_type) {
        auto r = eh1.set_int(803, *item1.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.secondary_cl_ord_id) {
        auto r = bb.field(526, *args.secondary_cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.account_type) {
        auto r = bb.field(581, *args.account_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cl_ord_link_id) {
        auto r = bb.field(583, *args.cl_ord_link_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.orig_ord_mod_time) {
        auto r = bb.field(586, *args.orig_ord_mod_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.working_indicator) {
        auto r = bb.field(636, (*args.working_indicator) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.acct_id_source) {
        auto r = bb.field(660, *args.acct_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.ex_destination_id_source) {
        auto r = bb.field(1133, *args.ex_destination_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.reject_text) {
        auto r = bb.field(1328, *args.reject_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_reject_text) {
        auto r_len = bb.field(1664, static_cast<::std::int64_t>(args.encoded_reject_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(1665, *args.encoded_reject_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.order_request_id) {
        auto r = bb.field(2422, *args.order_request_id);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
