// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/PartyDetailsListReport.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "PartyDetailsListReport.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_PartyDetailsListReport(::std::span<::std::byte> out, PartyDetailsListReportArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"CG"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.last_fragment) {
        auto r = bb.field(893, (*args.last_fragment) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_id) {
        auto r = bb.field(1180, *args.appl_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_seq_num) {
        auto r = bb.field(1181, *args.appl_seq_num);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.reject_text) {
        auto r = bb.field(1328, *args.reject_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_last_seq_num) {
        auto r = bb.field(1350, *args.appl_last_seq_num);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_resend_flag) {
        auto r = bb.field(1352, (*args.appl_resend_flag) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_details_list_request_id) {
        auto r = bb.field(1505, *args.party_details_list_request_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_details_list_report_id) {
        auto r = bb.field(1510, *args.party_details_list_report_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.request_result) {
        auto r = bb.field(1511, *args.request_result);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.tot_no_parties) {
        auto r = bb.field(1512, *args.tot_no_parties);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_reject_text) {
        auto r_len = bb.field(1664, static_cast<::std::int64_t>(args.encoded_reject_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(1665, *args.encoded_reject_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.party_details) {
        auto gh0 = bb.group_begin(1671, 1691);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.party_details) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_detail_id) {
        auto r = eh0.set_string(1691, *item0.party_detail_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_detail_id_source) {
        auto r = eh0.set_char(1692, *item0.party_detail_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_detail_role) {
        auto r = eh0.set_int(1693, *item0.party_detail_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_detail_role_qualifier) {
        auto r = eh0.set_int(1674, *item0.party_detail_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_detail_sub_i_ds) {
        auto gh1 = eh0.group_begin(1694, 1695);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_detail_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_detail_sub_id) {
        auto r = eh1.set_string(1695, *item1.party_detail_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_detail_sub_id_type) {
        auto r = eh1.set_int(1696, *item1.party_detail_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
    if (item0.party_detail_alt_id) {
        auto gh2 = eh0.group_begin(1516, 1517);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *item0.party_detail_alt_id) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.party_detail_alt_id) {
        auto r = eh2.set_string(1517, *item2.party_detail_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.party_detail_alt_id_source) {
        auto r = eh2.set_char(1518, *item2.party_detail_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.party_detail_alt_sub_i_ds) {
        auto gh3 = eh2.group_begin(1519, 1520);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *item2.party_detail_alt_sub_i_ds) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.party_detail_alt_sub_id) {
        auto r = eh3.set_string(1520, *item3.party_detail_alt_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.party_detail_alt_sub_id_type) {
        auto r = eh3.set_int(1521, *item3.party_detail_alt_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    if (item0.related_party_detail_id) {
        auto gh4 = eh0.group_begin(1562, 1563);
        if (!gh4) return ::std::unexpected(gh4.error());
        for (auto const& item4 : *item0.related_party_detail_id) {
            auto en4 = gh4->add_entry();
            if (!en4) return ::std::unexpected(en4.error());
            auto& eh4 = *en4;
    if (item4.related_party_detail_id) {
        auto r = eh4.set_string(1563, *item4.related_party_detail_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.related_party_detail_id_source) {
        auto r = eh4.set_char(1564, *item4.related_party_detail_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.related_party_detail_role) {
        auto r = eh4.set_int(1565, *item4.related_party_detail_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.related_party_detail_role_qualifier) {
        auto r = eh4.set_int(1675, *item4.related_party_detail_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.related_party_detail_sub_i_ds) {
        auto gh5 = eh4.group_begin(1566, 1567);
        if (!gh5) return ::std::unexpected(gh5.error());
        for (auto const& item5 : *item4.related_party_detail_sub_i_ds) {
            auto en5 = gh5->add_entry();
            if (!en5) return ::std::unexpected(en5.error());
            auto& eh5 = *en5;
    if (item5.related_party_detail_sub_id) {
        auto r = eh5.set_string(1567, *item5.related_party_detail_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.related_party_detail_sub_id_type) {
        auto r = eh5.set_int(1568, *item5.related_party_detail_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge5 = bb.group_end(*gh5);
        if (!ge5) return ::std::unexpected(ge5.error());
    }
    if (item4.related_party_detail_alt_id) {
        auto gh6 = eh4.group_begin(1569, 1570);
        if (!gh6) return ::std::unexpected(gh6.error());
        for (auto const& item6 : *item4.related_party_detail_alt_id) {
            auto en6 = gh6->add_entry();
            if (!en6) return ::std::unexpected(en6.error());
            auto& eh6 = *en6;
    if (item6.related_party_detail_alt_id) {
        auto r = eh6.set_string(1570, *item6.related_party_detail_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.related_party_detail_alt_id_source) {
        auto r = eh6.set_char(1571, *item6.related_party_detail_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.related_party_detail_alt_sub_i_ds) {
        auto gh7 = eh6.group_begin(1572, 1573);
        if (!gh7) return ::std::unexpected(gh7.error());
        for (auto const& item7 : *item6.related_party_detail_alt_sub_i_ds) {
            auto en7 = gh7->add_entry();
            if (!en7) return ::std::unexpected(en7.error());
            auto& eh7 = *en7;
    if (item7.related_party_detail_alt_sub_id) {
        auto r = eh7.set_string(1573, *item7.related_party_detail_alt_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.related_party_detail_alt_sub_id_type) {
        auto r = eh7.set_int(1574, *item7.related_party_detail_alt_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge7 = bb.group_end(*gh7);
        if (!ge7) return ::std::unexpected(ge7.error());
    }
        }
        auto ge6 = bb.group_end(*gh6);
        if (!ge6) return ::std::unexpected(ge6.error());
    }
    if (item4.party_relationships) {
        auto gh8 = eh4.group_begin(1514, 1515);
        if (!gh8) return ::std::unexpected(gh8.error());
        for (auto const& item8 : *item4.party_relationships) {
            auto en8 = gh8->add_entry();
            if (!en8) return ::std::unexpected(en8.error());
            auto& eh8 = *en8;
    if (item8.party_relationship) {
        auto r = eh8.set_int(1515, *item8.party_relationship);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge8 = bb.group_end(*gh8);
        if (!ge8) return ::std::unexpected(ge8.error());
    }
        }
        auto ge4 = bb.group_end(*gh4);
        if (!ge4) return ::std::unexpected(ge4.error());
    }
    if (item0.party_detail_status) {
        auto r = eh0.set_int(1672, *item0.party_detail_status);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
