// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/PartyEntitlementsDefinitionRequest.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_1657Args.hpp"
#include "../groups/G_1772_2Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct PartyEntitlementsDefinitionRequestArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::span<const groups::G_1657Args>> requesting_party_i_ds{};
    ::std::optional<::std::string_view> entitlement_request_id{};
    ::std::span<const groups::G_1772_2Args> party_entitlements{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_PartyEntitlementsDefinitionRequest)
#include "PartyEntitlementsDefinitionRequest.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_PartyEntitlementsDefinitionRequest(::std::span<::std::byte> out, PartyEntitlementsDefinitionRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_PartyEntitlementsDefinitionRequest)
#include "PartyEntitlementsDefinitionRequest.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_PartyEntitlementsDefinitionRequest(PartyEntitlementsDefinitionRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
