// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/PartyActionReport.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "PartyActionReport.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_PartyActionReport(::std::span<::std::byte> out, PartyActionReportArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"DI"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    {
        auto gh0 = bb.group_begin(453, 448);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : args.party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_id) {
        auto r = eh0.set_string(448, *item0.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_id_source) {
        auto r = eh0.set_char(447, *item0.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role) {
        auto r = eh0.set_int(452, *item0.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role_qualifier) {
        auto r = eh0.set_int(2376, *item0.party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_sub_i_ds) {
        auto gh1 = eh0.group_begin(802, 523);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_sub_id) {
        auto r = eh1.set_string(523, *item1.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_sub_id_type) {
        auto r = eh1.set_int(803, *item1.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.copy_msg_indicator) {
        auto r = bb.field(797, (*args.copy_msg_indicator) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.market_segment_id) {
        auto r = bb.field(1300, *args.market_segment_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.market_id) {
        auto r = bb.field(1301, *args.market_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.reject_text) {
        auto r = bb.field(1328, *args.reject_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_symbol) {
        auto r = bb.field(1536, *args.instrument_scope_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_symbol_sfx) {
        auto r = bb.field(1537, *args.instrument_scope_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_security_id) {
        auto r = bb.field(1538, *args.instrument_scope_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_security_id_source) {
        auto r = bb.field(1539, *args.instrument_scope_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_security_alt_id) {
        auto gh2 = bb.group_begin(1540, 1541);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *args.instrument_scope_security_alt_id) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.instrument_scope_security_alt_id) {
        auto r = eh2.set_string(1541, *item2.instrument_scope_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.instrument_scope_security_alt_id_source) {
        auto r = eh2.set_string(1542, *item2.instrument_scope_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    if (args.instrument_scope_product) {
        auto r = bb.field(1543, *args.instrument_scope_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_product_complex) {
        auto r = bb.field(1544, *args.instrument_scope_product_complex);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_security_group) {
        auto r = bb.field(1545, *args.instrument_scope_security_group);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_cfi_code) {
        auto r = bb.field(1546, *args.instrument_scope_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_security_type) {
        auto r = bb.field(1547, *args.instrument_scope_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_security_sub_type) {
        auto r = bb.field(1548, *args.instrument_scope_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_maturity_month_year) {
        auto r = bb.field(1549, *args.instrument_scope_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_maturity_time) {
        auto r = bb.field(1550, *args.instrument_scope_maturity_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_restructuring_type) {
        auto r = bb.field(1551, *args.instrument_scope_restructuring_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_seniority) {
        auto r = bb.field(1552, *args.instrument_scope_seniority);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_put_or_call) {
        auto r = bb.field(1553, *args.instrument_scope_put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_flexible_indicator) {
        auto r = bb.field(1554, (*args.instrument_scope_flexible_indicator) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_coupon_rate) {
        auto r = bb.field(1555, *args.instrument_scope_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_security_desc) {
        auto r = bb.field(1556, *args.instrument_scope_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_settl_type) {
        auto r = bb.field(1557, *args.instrument_scope_settl_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.related_party_detail_id) {
        auto gh3 = bb.group_begin(1562, 1563);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *args.related_party_detail_id) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.related_party_detail_id) {
        auto r = eh3.set_string(1563, *item3.related_party_detail_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.related_party_detail_id_source) {
        auto r = eh3.set_char(1564, *item3.related_party_detail_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.related_party_detail_role) {
        auto r = eh3.set_int(1565, *item3.related_party_detail_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.related_party_detail_role_qualifier) {
        auto r = eh3.set_int(1675, *item3.related_party_detail_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.related_party_detail_sub_i_ds) {
        auto gh4 = eh3.group_begin(1566, 1567);
        if (!gh4) return ::std::unexpected(gh4.error());
        for (auto const& item4 : *item3.related_party_detail_sub_i_ds) {
            auto en4 = gh4->add_entry();
            if (!en4) return ::std::unexpected(en4.error());
            auto& eh4 = *en4;
    if (item4.related_party_detail_sub_id) {
        auto r = eh4.set_string(1567, *item4.related_party_detail_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.related_party_detail_sub_id_type) {
        auto r = eh4.set_int(1568, *item4.related_party_detail_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge4 = bb.group_end(*gh4);
        if (!ge4) return ::std::unexpected(ge4.error());
    }
    if (item3.related_party_detail_alt_id) {
        auto gh5 = eh3.group_begin(1569, 1570);
        if (!gh5) return ::std::unexpected(gh5.error());
        for (auto const& item5 : *item3.related_party_detail_alt_id) {
            auto en5 = gh5->add_entry();
            if (!en5) return ::std::unexpected(en5.error());
            auto& eh5 = *en5;
    if (item5.related_party_detail_alt_id) {
        auto r = eh5.set_string(1570, *item5.related_party_detail_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.related_party_detail_alt_id_source) {
        auto r = eh5.set_char(1571, *item5.related_party_detail_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.related_party_detail_alt_sub_i_ds) {
        auto gh6 = eh5.group_begin(1572, 1573);
        if (!gh6) return ::std::unexpected(gh6.error());
        for (auto const& item6 : *item5.related_party_detail_alt_sub_i_ds) {
            auto en6 = gh6->add_entry();
            if (!en6) return ::std::unexpected(en6.error());
            auto& eh6 = *en6;
    if (item6.related_party_detail_alt_sub_id) {
        auto r = eh6.set_string(1573, *item6.related_party_detail_alt_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.related_party_detail_alt_sub_id_type) {
        auto r = eh6.set_int(1574, *item6.related_party_detail_alt_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge6 = bb.group_end(*gh6);
        if (!ge6) return ::std::unexpected(ge6.error());
    }
        }
        auto ge5 = bb.group_end(*gh5);
        if (!ge5) return ::std::unexpected(ge5.error());
    }
    if (item3.party_relationships) {
        auto gh7 = eh3.group_begin(1514, 1515);
        if (!gh7) return ::std::unexpected(gh7.error());
        for (auto const& item7 : *item3.party_relationships) {
            auto en7 = gh7->add_entry();
            if (!en7) return ::std::unexpected(en7.error());
            auto& eh7 = *en7;
    if (item7.party_relationship) {
        auto r = eh7.set_int(1515, *item7.party_relationship);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge7 = bb.group_end(*gh7);
        if (!ge7) return ::std::unexpected(ge7.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
    if (args.instrument_scope_security_exchange) {
        auto r = bb.field(1616, *args.instrument_scope_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_encoded_security_desc) {
        auto r_len = bb.field(1620, static_cast<::std::int64_t>(args.instrument_scope_encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(1621, *args.instrument_scope_encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.requesting_party_i_ds) {
        auto gh8 = bb.group_begin(1657, 1658);
        if (!gh8) return ::std::unexpected(gh8.error());
        for (auto const& item8 : *args.requesting_party_i_ds) {
            auto en8 = gh8->add_entry();
            if (!en8) return ::std::unexpected(en8.error());
            auto& eh8 = *en8;
    if (item8.requesting_party_id) {
        auto r = eh8.set_string(1658, *item8.requesting_party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.requesting_party_id_source) {
        auto r = eh8.set_char(1659, *item8.requesting_party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.requesting_party_role) {
        auto r = eh8.set_int(1660, *item8.requesting_party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.requesting_party_role_qualifier) {
        auto r = eh8.set_int(2338, *item8.requesting_party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.requesting_party_sub_i_ds) {
        auto gh9 = eh8.group_begin(1661, 1662);
        if (!gh9) return ::std::unexpected(gh9.error());
        for (auto const& item9 : *item8.requesting_party_sub_i_ds) {
            auto en9 = gh9->add_entry();
            if (!en9) return ::std::unexpected(en9.error());
            auto& eh9 = *en9;
    if (item9.requesting_party_sub_id) {
        auto r = eh9.set_string(1662, *item9.requesting_party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item9.requesting_party_sub_id_type) {
        auto r = eh9.set_int(1663, *item9.requesting_party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge9 = bb.group_end(*gh9);
        if (!ge9) return ::std::unexpected(ge9.error());
    }
        }
        auto ge8 = bb.group_end(*gh8);
        if (!ge8) return ::std::unexpected(ge8.error());
    }
    if (args.encoded_reject_text) {
        auto r_len = bb.field(1664, static_cast<::std::int64_t>(args.encoded_reject_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(1665, *args.encoded_reject_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.party_action_request_id) {
        auto r = bb.field(2328, *args.party_action_request_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_action_type) {
        auto r = bb.field(2329, *args.party_action_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_test_message_indicator) {
        auto r = bb.field(2330, (*args.appl_test_message_indicator) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_action_report_id) {
        auto r = bb.field(2331, *args.party_action_report_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_action_response) {
        auto r = bb.field(2332, *args.party_action_response);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_action_reject_reason) {
        auto r = bb.field(2333, *args.party_action_reject_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.effective_business_date) {
        auto r = bb.field(2400, *args.effective_business_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instrument_scope_upi_code) {
        auto r = bb.field(2895, *args.instrument_scope_upi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
