// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/PartyDetailsDefinitionRequest.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "PartyDetailsDefinitionRequest.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_PartyDetailsDefinitionRequest(::std::span<::std::byte> out, PartyDetailsDefinitionRequestArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"CX"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.party_details_list_request_id) {
        auto r = bb.field(1505, *args.party_details_list_request_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.requesting_party_i_ds) {
        auto gh0 = bb.group_begin(1657, 1658);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.requesting_party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.requesting_party_id) {
        auto r = eh0.set_string(1658, *item0.requesting_party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.requesting_party_id_source) {
        auto r = eh0.set_char(1659, *item0.requesting_party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.requesting_party_role) {
        auto r = eh0.set_int(1660, *item0.requesting_party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.requesting_party_role_qualifier) {
        auto r = eh0.set_int(2338, *item0.requesting_party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.requesting_party_sub_i_ds) {
        auto gh1 = eh0.group_begin(1661, 1662);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.requesting_party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.requesting_party_sub_id) {
        auto r = eh1.set_string(1662, *item1.requesting_party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.requesting_party_sub_id_type) {
        auto r = eh1.set_int(1663, *item1.requesting_party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    {
        auto gh2 = bb.group_begin(1676, 1324);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : args.party_updates) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.list_update_action) {
        auto r = eh2.set_char(1324, *item2.list_update_action);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.party_details) {
        auto gh3 = eh2.group_begin(1671, 1691);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *item2.party_details) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.party_detail_id) {
        auto r = eh3.set_string(1691, *item3.party_detail_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.party_detail_id_source) {
        auto r = eh3.set_char(1692, *item3.party_detail_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.party_detail_role) {
        auto r = eh3.set_int(1693, *item3.party_detail_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.party_detail_role_qualifier) {
        auto r = eh3.set_int(1674, *item3.party_detail_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.party_detail_sub_i_ds) {
        auto gh4 = eh3.group_begin(1694, 1695);
        if (!gh4) return ::std::unexpected(gh4.error());
        for (auto const& item4 : *item3.party_detail_sub_i_ds) {
            auto en4 = gh4->add_entry();
            if (!en4) return ::std::unexpected(en4.error());
            auto& eh4 = *en4;
    if (item4.party_detail_sub_id) {
        auto r = eh4.set_string(1695, *item4.party_detail_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.party_detail_sub_id_type) {
        auto r = eh4.set_int(1696, *item4.party_detail_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge4 = bb.group_end(*gh4);
        if (!ge4) return ::std::unexpected(ge4.error());
    }
    if (item3.party_detail_alt_id) {
        auto gh5 = eh3.group_begin(1516, 1517);
        if (!gh5) return ::std::unexpected(gh5.error());
        for (auto const& item5 : *item3.party_detail_alt_id) {
            auto en5 = gh5->add_entry();
            if (!en5) return ::std::unexpected(en5.error());
            auto& eh5 = *en5;
    if (item5.party_detail_alt_id) {
        auto r = eh5.set_string(1517, *item5.party_detail_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.party_detail_alt_id_source) {
        auto r = eh5.set_char(1518, *item5.party_detail_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.party_detail_alt_sub_i_ds) {
        auto gh6 = eh5.group_begin(1519, 1520);
        if (!gh6) return ::std::unexpected(gh6.error());
        for (auto const& item6 : *item5.party_detail_alt_sub_i_ds) {
            auto en6 = gh6->add_entry();
            if (!en6) return ::std::unexpected(en6.error());
            auto& eh6 = *en6;
    if (item6.party_detail_alt_sub_id) {
        auto r = eh6.set_string(1520, *item6.party_detail_alt_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.party_detail_alt_sub_id_type) {
        auto r = eh6.set_int(1521, *item6.party_detail_alt_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge6 = bb.group_end(*gh6);
        if (!ge6) return ::std::unexpected(ge6.error());
    }
        }
        auto ge5 = bb.group_end(*gh5);
        if (!ge5) return ::std::unexpected(ge5.error());
    }
    if (item3.related_party_detail_id) {
        auto gh7 = eh3.group_begin(1562, 1563);
        if (!gh7) return ::std::unexpected(gh7.error());
        for (auto const& item7 : *item3.related_party_detail_id) {
            auto en7 = gh7->add_entry();
            if (!en7) return ::std::unexpected(en7.error());
            auto& eh7 = *en7;
    if (item7.related_party_detail_id) {
        auto r = eh7.set_string(1563, *item7.related_party_detail_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.related_party_detail_id_source) {
        auto r = eh7.set_char(1564, *item7.related_party_detail_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.related_party_detail_role) {
        auto r = eh7.set_int(1565, *item7.related_party_detail_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.related_party_detail_role_qualifier) {
        auto r = eh7.set_int(1675, *item7.related_party_detail_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.related_party_detail_sub_i_ds) {
        auto gh8 = eh7.group_begin(1566, 1567);
        if (!gh8) return ::std::unexpected(gh8.error());
        for (auto const& item8 : *item7.related_party_detail_sub_i_ds) {
            auto en8 = gh8->add_entry();
            if (!en8) return ::std::unexpected(en8.error());
            auto& eh8 = *en8;
    if (item8.related_party_detail_sub_id) {
        auto r = eh8.set_string(1567, *item8.related_party_detail_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.related_party_detail_sub_id_type) {
        auto r = eh8.set_int(1568, *item8.related_party_detail_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge8 = bb.group_end(*gh8);
        if (!ge8) return ::std::unexpected(ge8.error());
    }
    if (item7.related_party_detail_alt_id) {
        auto gh9 = eh7.group_begin(1569, 1570);
        if (!gh9) return ::std::unexpected(gh9.error());
        for (auto const& item9 : *item7.related_party_detail_alt_id) {
            auto en9 = gh9->add_entry();
            if (!en9) return ::std::unexpected(en9.error());
            auto& eh9 = *en9;
    if (item9.related_party_detail_alt_id) {
        auto r = eh9.set_string(1570, *item9.related_party_detail_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item9.related_party_detail_alt_id_source) {
        auto r = eh9.set_char(1571, *item9.related_party_detail_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item9.related_party_detail_alt_sub_i_ds) {
        auto gh10 = eh9.group_begin(1572, 1573);
        if (!gh10) return ::std::unexpected(gh10.error());
        for (auto const& item10 : *item9.related_party_detail_alt_sub_i_ds) {
            auto en10 = gh10->add_entry();
            if (!en10) return ::std::unexpected(en10.error());
            auto& eh10 = *en10;
    if (item10.related_party_detail_alt_sub_id) {
        auto r = eh10.set_string(1573, *item10.related_party_detail_alt_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.related_party_detail_alt_sub_id_type) {
        auto r = eh10.set_int(1574, *item10.related_party_detail_alt_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge10 = bb.group_end(*gh10);
        if (!ge10) return ::std::unexpected(ge10.error());
    }
        }
        auto ge9 = bb.group_end(*gh9);
        if (!ge9) return ::std::unexpected(ge9.error());
    }
    if (item7.party_relationships) {
        auto gh11 = eh7.group_begin(1514, 1515);
        if (!gh11) return ::std::unexpected(gh11.error());
        for (auto const& item11 : *item7.party_relationships) {
            auto en11 = gh11->add_entry();
            if (!en11) return ::std::unexpected(en11.error());
            auto& eh11 = *en11;
    if (item11.party_relationship) {
        auto r = eh11.set_int(1515, *item11.party_relationship);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge11 = bb.group_end(*gh11);
        if (!ge11) return ::std::unexpected(ge11.error());
    }
        }
        auto ge7 = bb.group_end(*gh7);
        if (!ge7) return ::std::unexpected(ge7.error());
    }
    if (item3.party_detail_status) {
        auto r = eh3.set_int(1672, *item3.party_detail_status);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
