// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/PartyRiskLimitsDefinitionRequestAck.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_1657Args.hpp"
#include "../groups/G_1677_3Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct PartyRiskLimitsDefinitionRequestAckArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::span<const groups::G_1657Args>> requesting_party_i_ds{};
    ::std::optional<::std::string_view> risk_limit_request_id{};
    ::std::optional<::std::span<const groups::G_1677_3Args>> party_risk_limits{};
    ::std::optional<::std::int64_t> risk_limit_request_result{};
    ::std::optional<::std::int64_t> risk_limit_request_status{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_PartyRiskLimitsDefinitionRequestAck)
#include "PartyRiskLimitsDefinitionRequestAck.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_PartyRiskLimitsDefinitionRequestAck(::std::span<::std::byte> out, PartyRiskLimitsDefinitionRequestAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_PartyRiskLimitsDefinitionRequestAck)
#include "PartyRiskLimitsDefinitionRequestAck.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_PartyRiskLimitsDefinitionRequestAck(PartyRiskLimitsDefinitionRequestAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
