// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/PartyEntitlementsRequest.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "PartyEntitlementsRequest.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_PartyEntitlementsRequest(::std::span<::std::byte> out, PartyEntitlementsRequestArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"CU"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.subscription_request_type) {
        auto r = bb.field(263, *args.subscription_request_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.party_i_ds) {
        auto gh0 = bb.group_begin(453, 448);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_id) {
        auto r = eh0.set_string(448, *item0.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_id_source) {
        auto r = eh0.set_char(447, *item0.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role) {
        auto r = eh0.set_int(452, *item0.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role_qualifier) {
        auto r = eh0.set_int(2376, *item0.party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_sub_i_ds) {
        auto gh1 = eh0.group_begin(802, 523);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_sub_id) {
        auto r = eh1.set_string(523, *item1.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_sub_id_type) {
        auto r = eh1.set_int(803, *item1.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.market_segments) {
        auto gh2 = bb.group_begin(1310, 1301);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *args.market_segments) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.market_id) {
        auto r = eh2.set_string(1301, *item2.market_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.market_segment_id) {
        auto r = eh2.set_string(1300, *item2.market_segment_id);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    if (args.requested_party_roles) {
        auto gh3 = bb.group_begin(1508, 1509);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *args.requested_party_roles) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.requested_party_role) {
        auto r = eh3.set_int(1509, *item3.requested_party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.requested_party_role_qualifier) {
        auto r = eh3.set_int(2386, *item3.requested_party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
    if (args.instrument_scopes) {
        auto gh4 = bb.group_begin(1656, 1535);
        if (!gh4) return ::std::unexpected(gh4.error());
        for (auto const& item4 : *args.instrument_scopes) {
            auto en4 = gh4->add_entry();
            if (!en4) return ::std::unexpected(en4.error());
            auto& eh4 = *en4;
    if (item4.instrument_scope_operator) {
        auto r = eh4.set_int(1535, *item4.instrument_scope_operator);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_symbol) {
        auto r = eh4.set_string(1536, *item4.instrument_scope_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_symbol_sfx) {
        auto r = eh4.set_string(1537, *item4.instrument_scope_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_id) {
        auto r = eh4.set_string(1538, *item4.instrument_scope_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_id_source) {
        auto r = eh4.set_string(1539, *item4.instrument_scope_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_alt_id) {
        auto gh5 = eh4.group_begin(1540, 1541);
        if (!gh5) return ::std::unexpected(gh5.error());
        for (auto const& item5 : *item4.instrument_scope_security_alt_id) {
            auto en5 = gh5->add_entry();
            if (!en5) return ::std::unexpected(en5.error());
            auto& eh5 = *en5;
    if (item5.instrument_scope_security_alt_id) {
        auto r = eh5.set_string(1541, *item5.instrument_scope_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.instrument_scope_security_alt_id_source) {
        auto r = eh5.set_string(1542, *item5.instrument_scope_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge5 = bb.group_end(*gh5);
        if (!ge5) return ::std::unexpected(ge5.error());
    }
    if (item4.instrument_scope_product) {
        auto r = eh4.set_int(1543, *item4.instrument_scope_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_product_complex) {
        auto r = eh4.set_string(1544, *item4.instrument_scope_product_complex);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_group) {
        auto r = eh4.set_string(1545, *item4.instrument_scope_security_group);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_cfi_code) {
        auto r = eh4.set_string(1546, *item4.instrument_scope_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_upi_code) {
        auto r = eh4.set_string(2895, *item4.instrument_scope_upi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_type) {
        auto r = eh4.set_string(1547, *item4.instrument_scope_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_sub_type) {
        auto r = eh4.set_string(1548, *item4.instrument_scope_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_maturity_month_year) {
        auto r = eh4.set_string(1549, *item4.instrument_scope_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_maturity_time) {
        auto r = eh4.set_string(1550, *item4.instrument_scope_maturity_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_restructuring_type) {
        auto r = eh4.set_string(1551, *item4.instrument_scope_restructuring_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_seniority) {
        auto r = eh4.set_string(1552, *item4.instrument_scope_seniority);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_put_or_call) {
        auto r = eh4.set_int(1553, *item4.instrument_scope_put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_flexible_indicator) {
        auto r = eh4.set_char(1554, (*item4.instrument_scope_flexible_indicator) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_coupon_rate) {
        auto r = eh4.set_decimal(1555, *item4.instrument_scope_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_exchange) {
        auto r = eh4.set_string(1616, *item4.instrument_scope_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_security_desc) {
        auto r = eh4.set_string(1556, *item4.instrument_scope_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.instrument_scope_encoded_security_desc) {
        auto r_len = eh4.set_int(1620, static_cast<::std::int64_t>(item4.instrument_scope_encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh4.set_string(1621, *item4.instrument_scope_encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item4.instrument_scope_settl_type) {
        auto r = eh4.set_string(1557, *item4.instrument_scope_settl_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge4 = bb.group_end(*gh4);
        if (!ge4) return ::std::unexpected(ge4.error());
    }
    if (args.requesting_party_i_ds) {
        auto gh6 = bb.group_begin(1657, 1658);
        if (!gh6) return ::std::unexpected(gh6.error());
        for (auto const& item6 : *args.requesting_party_i_ds) {
            auto en6 = gh6->add_entry();
            if (!en6) return ::std::unexpected(en6.error());
            auto& eh6 = *en6;
    if (item6.requesting_party_id) {
        auto r = eh6.set_string(1658, *item6.requesting_party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.requesting_party_id_source) {
        auto r = eh6.set_char(1659, *item6.requesting_party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.requesting_party_role) {
        auto r = eh6.set_int(1660, *item6.requesting_party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.requesting_party_role_qualifier) {
        auto r = eh6.set_int(2338, *item6.requesting_party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.requesting_party_sub_i_ds) {
        auto gh7 = eh6.group_begin(1661, 1662);
        if (!gh7) return ::std::unexpected(gh7.error());
        for (auto const& item7 : *item6.requesting_party_sub_i_ds) {
            auto en7 = gh7->add_entry();
            if (!en7) return ::std::unexpected(en7.error());
            auto& eh7 = *en7;
    if (item7.requesting_party_sub_id) {
        auto r = eh7.set_string(1662, *item7.requesting_party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.requesting_party_sub_id_type) {
        auto r = eh7.set_int(1663, *item7.requesting_party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge7 = bb.group_end(*gh7);
        if (!ge7) return ::std::unexpected(ge7.error());
    }
        }
        auto ge6 = bb.group_end(*gh6);
        if (!ge6) return ::std::unexpected(ge6.error());
    }
    if (args.entitlement_request_id) {
        auto r = bb.field(1770, *args.entitlement_request_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.entitlement_platform) {
        auto r = bb.field(1784, *args.entitlement_platform);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.entitlement_status) {
        auto r = bb.field(1883, *args.entitlement_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.entitlement_types) {
        auto gh8 = bb.group_begin(2345, 1775);
        if (!gh8) return ::std::unexpected(gh8.error());
        for (auto const& item8 : *args.entitlement_types) {
            auto en8 = gh8->add_entry();
            if (!en8) return ::std::unexpected(en8.error());
            auto& eh8 = *en8;
    if (item8.entitlement_type) {
        auto r = eh8.set_int(1775, *item8.entitlement_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.entitlement_sub_type) {
        auto r = eh8.set_int(2402, *item8.entitlement_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge8 = bb.group_end(*gh8);
        if (!ge8) return ::std::unexpected(ge8.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
