// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/PartyDetailsListReport.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_1671Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct PartyDetailsListReportArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<bool> last_fragment{};
    ::std::optional<::std::string_view> appl_id{};
    ::std::optional<::std::int64_t> appl_seq_num{};
    ::std::optional<::std::string_view> reject_text{};
    ::std::optional<::std::int64_t> appl_last_seq_num{};
    ::std::optional<bool> appl_resend_flag{};
    ::std::optional<::std::string_view> party_details_list_request_id{};
    ::std::optional<::std::string_view> party_details_list_report_id{};
    ::std::optional<::std::int64_t> request_result{};
    ::std::optional<::std::int64_t> tot_no_parties{};
    ::std::optional<::std::string_view> encoded_reject_text{};
    ::std::optional<::std::span<const groups::G_1671Args>> party_details{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_PartyDetailsListReport)
#include "PartyDetailsListReport.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_PartyDetailsListReport(::std::span<::std::byte> out, PartyDetailsListReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_PartyDetailsListReport)
#include "PartyDetailsListReport.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_PartyDetailsListReport(PartyDetailsListReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
