// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/QuoteRequestReject.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_146_2Args.hpp"
#include "../groups/G_1116Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct QuoteRequestRejectArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> quote_req_id{};
    ::std::span<const groups::G_146_2Args> related_sym{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::string_view> rfq_req_id{};
    ::std::optional<::std::int64_t> quote_request_reject_reason{};
    ::std::optional<bool> pre_trade_anonymity{};
    ::std::optional<::std::span<const groups::G_1116Args>> root_party_i_ds{};
    ::std::optional<bool> private_quote{};
    ::std::optional<::std::int64_t> respondent_type{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_QuoteRequestReject)
#include "QuoteRequestReject.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_QuoteRequestReject(::std::span<::std::byte> out, QuoteRequestRejectArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_QuoteRequestReject)
#include "QuoteRequestReject.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_QuoteRequestReject(QuoteRequestRejectArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
