// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/SecurityTypeRequest.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct SecurityTypeRequestArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> security_type{};
    ::std::optional<::std::string_view> security_req_id{};
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::int64_t> product{};
    ::std::optional<::std::string_view> trading_session_sub_id{};
    ::std::optional<::std::string_view> security_sub_type{};
    ::std::optional<::std::string_view> market_segment_id{};
    ::std::optional<::std::string_view> market_id{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_SecurityTypeRequest)
#include "SecurityTypeRequest.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_SecurityTypeRequest(::std::span<::std::byte> out, SecurityTypeRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_SecurityTypeRequest)
#include "SecurityTypeRequest.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_SecurityTypeRequest(SecurityTypeRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
