// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/SecurityTypeRequest.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "SecurityTypeRequest.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_SecurityTypeRequest(::std::span<::std::byte> out, SecurityTypeRequestArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"v"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_type) {
        auto r = bb.field(167, *args.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_req_id) {
        auto r = bb.field(320, *args.security_req_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trading_session_id) {
        auto r = bb.field(336, *args.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.product) {
        auto r = bb.field(460, *args.product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trading_session_sub_id) {
        auto r = bb.field(625, *args.trading_session_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_sub_type) {
        auto r = bb.field(762, *args.security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.market_segment_id) {
        auto r = bb.field(1300, *args.market_segment_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.market_id) {
        auto r = bb.field(1301, *args.market_id);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
