// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/SecurityMassStatus.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_146_9Args.hpp"
#include "../groups/G_1540Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct SecurityMassStatusArgs {
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> trade_date{};
    ::std::optional<::std::span<const groups::G_146_9Args>> related_sym{};
    ::std::optional<::std::int64_t> market_depth{};
    ::std::optional<::std::string_view> security_status_req_id{};
    ::std::optional<bool> unsolicited_indicator{};
    ::std::optional<::std::int64_t> adjustment{};
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> trading_session_sub_id{};
    ::std::optional<::std::int64_t> md_book_type{};
    ::std::optional<::std::string_view> appl_id{};
    ::std::optional<::std::int64_t> appl_seq_num{};
    ::std::optional<::std::string_view> market_segment_id{};
    ::std::optional<::std::string_view> market_id{};
    ::std::optional<::std::int64_t> appl_last_seq_num{};
    ::std::optional<bool> appl_resend_flag{};
    ::std::optional<::std::string_view> security_list_id{};
    ::std::optional<::std::string_view> instrument_scope_symbol{};
    ::std::optional<::std::string_view> instrument_scope_symbol_sfx{};
    ::std::optional<::std::string_view> instrument_scope_security_id{};
    ::std::optional<::std::string_view> instrument_scope_security_id_source{};
    ::std::optional<::std::span<const groups::G_1540Args>> instrument_scope_security_alt_id{};
    ::std::optional<::std::int64_t> instrument_scope_product{};
    ::std::optional<::std::string_view> instrument_scope_product_complex{};
    ::std::optional<::std::string_view> instrument_scope_security_group{};
    ::std::optional<::std::string_view> instrument_scope_cfi_code{};
    ::std::optional<::std::string_view> instrument_scope_security_type{};
    ::std::optional<::std::string_view> instrument_scope_security_sub_type{};
    ::std::optional<::std::string_view> instrument_scope_maturity_month_year{};
    ::std::optional<::std::string_view> instrument_scope_maturity_time{};
    ::std::optional<::std::string_view> instrument_scope_restructuring_type{};
    ::std::optional<::std::string_view> instrument_scope_seniority{};
    ::std::optional<::std::int64_t> instrument_scope_put_or_call{};
    ::std::optional<bool> instrument_scope_flexible_indicator{};
    ::std::optional<::fixpp::decimal_t> instrument_scope_coupon_rate{};
    ::std::optional<::std::string_view> instrument_scope_security_desc{};
    ::std::optional<::std::string_view> instrument_scope_settl_type{};
    ::std::optional<::std::string_view> instrument_scope_security_exchange{};
    ::std::optional<::std::string_view> instrument_scope_encoded_security_desc{};
    ::std::optional<::std::int64_t> security_mass_trading_status{};
    ::std::optional<::std::int64_t> security_mass_trading_event{};
    ::std::optional<::std::int64_t> mass_halt_reason{};
    ::std::optional<bool> fast_market_indicator{};
    ::std::optional<::std::string_view> instrument_scope_upi_code{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_SecurityMassStatus)
#include "SecurityMassStatus.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_SecurityMassStatus(::std::span<::std::byte> out, SecurityMassStatusArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_SecurityMassStatus)
#include "SecurityMassStatus.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_SecurityMassStatus(SecurityMassStatusArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
