// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/SecurityTypes.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_558Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct SecurityTypesArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<char> subscription_request_type{};
    ::std::optional<::std::string_view> security_req_id{};
    ::std::optional<::std::string_view> security_response_id{};
    ::std::optional<::std::int64_t> security_response_type{};
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::int64_t> tot_no_security_types{};
    ::std::optional<::std::span<const groups::G_558Args>> security_types{};
    ::std::optional<::std::string_view> trading_session_sub_id{};
    ::std::optional<bool> last_fragment{};
    ::std::optional<::std::string_view> appl_id{};
    ::std::optional<::std::int64_t> appl_seq_num{};
    ::std::optional<::std::string_view> market_segment_id{};
    ::std::optional<::std::string_view> market_id{};
    ::std::optional<::std::int64_t> appl_last_seq_num{};
    ::std::optional<bool> appl_resend_flag{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_SecurityTypes)
#include "SecurityTypes.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_SecurityTypes(::std::span<::std::byte> out, SecurityTypesArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_SecurityTypes)
#include "SecurityTypes.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_SecurityTypes(SecurityTypesArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
