// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/SettlementObligationReport.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_1165Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct SettlementObligationReportArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::string_view> clearing_business_date{};
    ::std::optional<::std::int64_t> settlement_cycle_no{};
    ::std::optional<::std::int64_t> settl_oblig_mode{};
    ::std::optional<::std::string_view> settl_oblig_msg_id{};
    ::std::span<const groups::G_1165Args> settl_oblig{};
    ::std::optional<::std::string_view> appl_id{};
    ::std::optional<::std::int64_t> appl_seq_num{};
    ::std::optional<::std::int64_t> appl_last_seq_num{};
    ::std::optional<bool> appl_resend_flag{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_SettlementObligationReport)
#include "SettlementObligationReport.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_SettlementObligationReport(::std::span<::std::byte> out, SettlementObligationReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_SettlementObligationReport)
#include "SettlementObligationReport.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_SettlementObligationReport(SettlementObligationReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
