// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/StreamAssignmentReportACK.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "StreamAssignmentReportACK.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

::fixpp::core::expected_t<::std::span<::std::byte>> build_StreamAssignmentReportACK(::std::span<::std::byte> out, StreamAssignmentReportACKArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"CE"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.stream_asgn_rpt_id) {
        auto r = bb.field(1501, *args.stream_asgn_rpt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stream_asgn_rej_reason) {
        auto r = bb.field(1502, *args.stream_asgn_rej_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stream_asgn_ack_type) {
        auto r = bb.field(1503, *args.stream_asgn_ack_type);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
