// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/StreamAssignmentReportACK.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct StreamAssignmentReportACKArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::string_view> stream_asgn_rpt_id{};
    ::std::optional<::std::int64_t> stream_asgn_rej_reason{};
    ::std::optional<::std::int64_t> stream_asgn_ack_type{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_StreamAssignmentReportACK)
#include "StreamAssignmentReportACK.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_StreamAssignmentReportACK(::std::span<::std::byte> out, StreamAssignmentReportACKArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_StreamAssignmentReportACK)
#include "StreamAssignmentReportACK.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_StreamAssignmentReportACK(StreamAssignmentReportACKArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
