// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/TestActionReport.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_957Args.hpp"
#include "../groups/G_3025Args.hpp"
#include "../groups/G_3028Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct TestActionReportArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::span<const groups::G_957Args>> strategy_parameters{};
    ::std::optional<::std::span<const groups::G_3025Args>> algo_system_modules{};
    ::std::optional<::std::span<const groups::G_3028Args>> test_scenarios{};
    ::std::optional<::std::string_view> test_suite_request_id{};
    ::std::optional<::std::int64_t> test_suite_status{};
    ::std::optional<::std::string_view> test_action_report_id{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_TestActionReport)
#include "TestActionReport.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_TestActionReport(::std::span<::std::byte> out, TestActionReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_TestActionReport)
#include "TestActionReport.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_TestActionReport(TestActionReportArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
