// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/TestActionRequest.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_453Args.hpp"
#include "../groups/G_3028Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct TestActionRequestArgs {
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<::std::span<const groups::G_453Args>> party_i_ds{};
    ::std::optional<::std::span<const groups::G_3028Args>> test_scenarios{};
    ::std::optional<::std::string_view> test_suite_request_id{};
    ::std::optional<::std::string_view> test_action_request_id{};
    ::std::optional<::std::int64_t> test_action_type{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_TestActionRequest)
#include "TestActionRequest.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_TestActionRequest(::std::span<::std::byte> out, TestActionRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_TestActionRequest)
#include "TestActionRequest.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_TestActionRequest(TestActionRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
