// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/TestActionRequestAck.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct TestActionRequestAckArgs {
    ::std::optional<::std::string_view> reject_text{};
    ::std::optional<::std::string_view> encoded_reject_text{};
    ::std::optional<::std::string_view> test_suite_request_id{};
    ::std::optional<::std::string_view> test_action_request_id{};
    ::std::optional<::std::int64_t> test_action_request_status{};
    ::std::optional<::std::int64_t> test_suite_activity_state{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_TestActionRequestAck)
#include "TestActionRequestAck.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_TestActionRequestAck(::std::span<::std::byte> out, TestActionRequestAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_TestActionRequestAck)
#include "TestActionRequestAck.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_TestActionRequestAck(TestActionRequestAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
