// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/TradingSessionStatusAck.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct TradingSessionStatusAckArgs {
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::std::string_view> reject_text{};
    ::std::optional<::std::string_view> encoded_reject_text{};
    ::std::optional<::std::string_view> trading_session_status_report_id{};
    ::std::optional<::std::int64_t> report_status{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_TradingSessionStatusAck)
#include "TradingSessionStatusAck.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_TradingSessionStatusAck(::std::span<::std::byte> out, TradingSessionStatusAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_TradingSessionStatusAck)
#include "TradingSessionStatusAck.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_TradingSessionStatusAck(TradingSessionStatusAckArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
