// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/TradeMatchReportAck.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "TradeMatchReportAck.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_TradeMatchReportAck(::std::span<::std::byte> out, TradeMatchReportAckArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"DD"};
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.trd_match_id) {
        auto r = bb.field(880, *args.trd_match_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_id) {
        auto r = bb.field(1180, *args.appl_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_seq_num) {
        auto r = bb.field(1181, *args.appl_seq_num);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.reject_text) {
        auto r = bb.field(1328, *args.reject_text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_last_seq_num) {
        auto r = bb.field(1350, *args.appl_last_seq_num);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.appl_resend_flag) {
        auto r = bb.field(1352, (*args.appl_resend_flag) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_reject_text) {
        auto r_len = bb.field(1664, static_cast<::std::int64_t>(args.encoded_reject_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(1665, *args.encoded_reject_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.trade_match_ack_status) {
        auto r = bb.field(1896, *args.trade_match_ack_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trade_match_reject_reason) {
        auto r = bb.field(1897, *args.trade_match_reject_reason);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::vlatest
